//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using GroceryEcommerce.EntityClasses;
using GroceryEcommerce.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace GroceryEcommerce.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the AuditLog entity</summary>
		public EntityQuery<AuditLogEntity> AuditLog { get { return Create<AuditLogEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the RefreshToken entity</summary>
		public EntityQuery<RefreshTokenEntity> RefreshToken { get { return Create<RefreshTokenEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the User entity</summary>
		public EntityQuery<UserEntity> User { get { return Create<UserEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserAddress entity</summary>
		public EntityQuery<UserAddressEntity> UserAddress { get { return Create<UserAddressEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserRole entity</summary>
		public EntityQuery<UserRoleEntity> UserRole { get { return Create<UserRoleEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserRoleAssignment entity</summary>
		public EntityQuery<UserRoleAssignmentEntity> UserRoleAssignment { get { return Create<UserRoleAssignmentEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the UserSession entity</summary>
		public EntityQuery<UserSessionEntity> UserSession { get { return Create<UserSessionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the AbandonedCart entity</summary>
		public EntityQuery<AbandonedCartEntity> AbandonedCart { get { return Create<AbandonedCartEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ShoppingCart entity</summary>
		public EntityQuery<ShoppingCartEntity> ShoppingCart { get { return Create<ShoppingCartEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ShoppingCartItem entity</summary>
		public EntityQuery<ShoppingCartItemEntity> ShoppingCartItem { get { return Create<ShoppingCartItemEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Wishlist entity</summary>
		public EntityQuery<WishlistEntity> Wishlist { get { return Create<WishlistEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the WishlistItem entity</summary>
		public EntityQuery<WishlistItemEntity> WishlistItem { get { return Create<WishlistItemEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Brand entity</summary>
		public EntityQuery<BrandEntity> Brand { get { return Create<BrandEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Category entity</summary>
		public EntityQuery<CategoryEntity> Category { get { return Create<CategoryEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Product entity</summary>
		public EntityQuery<ProductEntity> Product { get { return Create<ProductEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProductAttribute entity</summary>
		public EntityQuery<ProductAttributeEntity> ProductAttribute { get { return Create<ProductAttributeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProductAttributeValue entity</summary>
		public EntityQuery<ProductAttributeValueEntity> ProductAttributeValue { get { return Create<ProductAttributeValueEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProductImage entity</summary>
		public EntityQuery<ProductImageEntity> ProductImage { get { return Create<ProductImageEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProductQuestion entity</summary>
		public EntityQuery<ProductQuestionEntity> ProductQuestion { get { return Create<ProductQuestionEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProductTag entity</summary>
		public EntityQuery<ProductTagEntity> ProductTag { get { return Create<ProductTagEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProductTagAssignment entity</summary>
		public EntityQuery<ProductTagAssignmentEntity> ProductTagAssignment { get { return Create<ProductTagAssignmentEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProductVariant entity</summary>
		public EntityQuery<ProductVariantEntity> ProductVariant { get { return Create<ProductVariantEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Shop entity</summary>
		public EntityQuery<ShopEntity> Shop { get { return Create<ShopEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the PurchaseOrder entity</summary>
		public EntityQuery<PurchaseOrderEntity> PurchaseOrder { get { return Create<PurchaseOrderEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the PurchaseOrderItem entity</summary>
		public EntityQuery<PurchaseOrderItemEntity> PurchaseOrderItem { get { return Create<PurchaseOrderItemEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Coupon entity</summary>
		public EntityQuery<CouponEntity> Coupon { get { return Create<CouponEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the CouponUsage entity</summary>
		public EntityQuery<CouponUsageEntity> CouponUsage { get { return Create<CouponUsageEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the GiftCard entity</summary>
		public EntityQuery<GiftCardEntity> GiftCard { get { return Create<GiftCardEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the RewardPoint entity</summary>
		public EntityQuery<RewardPointEntity> RewardPoint { get { return Create<RewardPointEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ProductReview entity</summary>
		public EntityQuery<ProductReviewEntity> ProductReview { get { return Create<ProductReviewEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ReviewImage entity</summary>
		public EntityQuery<ReviewImageEntity> ReviewImage { get { return Create<ReviewImageEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ReviewReport entity</summary>
		public EntityQuery<ReviewReportEntity> ReviewReport { get { return Create<ReviewReportEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ReviewVote entity</summary>
		public EntityQuery<ReviewVoteEntity> ReviewVote { get { return Create<ReviewVoteEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Order entity</summary>
		public EntityQuery<OrderEntity> Order { get { return Create<OrderEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the OrderItem entity</summary>
		public EntityQuery<OrderItemEntity> OrderItem { get { return Create<OrderItemEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the OrderPayment entity</summary>
		public EntityQuery<OrderPaymentEntity> OrderPayment { get { return Create<OrderPaymentEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the OrderRefund entity</summary>
		public EntityQuery<OrderRefundEntity> OrderRefund { get { return Create<OrderRefundEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the OrderShipment entity</summary>
		public EntityQuery<OrderShipmentEntity> OrderShipment { get { return Create<OrderShipmentEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the OrderStatusHistory entity</summary>
		public EntityQuery<OrderStatusHistoryEntity> OrderStatusHistory { get { return Create<OrderStatusHistoryEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ShipmentCarrier entity</summary>
		public EntityQuery<ShipmentCarrierEntity> ShipmentCarrier { get { return Create<ShipmentCarrierEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the ShipmentItem entity</summary>
		public EntityQuery<ShipmentItemEntity> ShipmentItem { get { return Create<ShipmentItemEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Currency entity</summary>
		public EntityQuery<CurrencyEntity> Currency { get { return Create<CurrencyEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the EmailTemplate entity</summary>
		public EntityQuery<EmailTemplateEntity> EmailTemplate { get { return Create<EmailTemplateEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the SystemSetting entity</summary>
		public EntityQuery<SystemSettingEntity> SystemSetting { get { return Create<SystemSettingEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}