using AutoMapper;
using GroceryEcommerce.Domain.Entities.Sales;
using GroceryEcommerce.EntityClasses;

namespace GroceryEcommerce.Infrastructure.Mapping;

public class SalesMappingProfile : Profile
{
    public SalesMappingProfile()
    {
        // Order mapping
        CreateMap<Order, OrderEntity>()
            .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.OrderId))
            .ForMember(dest => dest.OrderNumber, opt => opt.MapFrom(src => src.OrderNumber))
            .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
            .ForMember(dest => dest.OrderDate, opt => opt.MapFrom(src => src.OrderDate))
            .ForMember(dest => dest.SubTotal, opt => opt.MapFrom(src => src.SubTotal))
            .ForMember(dest => dest.TaxAmount, opt => opt.MapFrom(src => src.TaxAmount))
            .ForMember(dest => dest.ShippingAmount, opt => opt.MapFrom(src => src.ShippingAmount))
            .ForMember(dest => dest.DiscountAmount, opt => opt.MapFrom(src => src.DiscountAmount))
            .ForMember(dest => dest.TotalAmount, opt => opt.MapFrom(src => src.TotalAmount))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
            .ForMember(dest => dest.PaymentStatus, opt => opt.MapFrom(src => src.PaymentStatus))
            .ForMember(dest => dest.PaymentMethod, opt => opt.MapFrom(src => src.PaymentMethod))
            .ForMember(dest => dest.ShippingFirstName, opt => opt.MapFrom(src => src.ShippingFirstName))
            .ForMember(dest => dest.ShippingLastName, opt => opt.MapFrom(src => src.ShippingLastName))
            .ForMember(dest => dest.ShippingEmail, opt => opt.MapFrom(src => src.ShippingEmail))
            .ForMember(dest => dest.ShippingPhone, opt => opt.MapFrom(src => src.ShippingPhone))
            .ForMember(dest => dest.ShippingAddress, opt => opt.MapFrom(src => src.ShippingAddress))
            .ForMember(dest => dest.ShippingCity, opt => opt.MapFrom(src => src.ShippingCity))
            .ForMember(dest => dest.ShippingState, opt => opt.MapFrom(src => src.ShippingState))
            .ForMember(dest => dest.ShippingZipCode, opt => opt.MapFrom(src => src.ShippingZipCode))
            .ForMember(dest => dest.ShippingCountry, opt => opt.MapFrom(src => src.ShippingCountry))
            .ForMember(dest => dest.BillingFirstName, opt => opt.MapFrom(src => src.BillingFirstName))
            .ForMember(dest => dest.BillingLastName, opt => opt.MapFrom(src => src.BillingLastName))
            .ForMember(dest => dest.BillingEmail, opt => opt.MapFrom(src => src.BillingEmail))
            .ForMember(dest => dest.BillingPhone, opt => opt.MapFrom(src => src.BillingPhone))
            .ForMember(dest => dest.BillingAddress, opt => opt.MapFrom(src => src.BillingAddress))
            .ForMember(dest => dest.BillingCity, opt => opt.MapFrom(src => src.BillingCity))
            .ForMember(dest => dest.BillingState, opt => opt.MapFrom(src => src.BillingState))
            .ForMember(dest => dest.BillingZipCode, opt => opt.MapFrom(src => src.BillingZipCode))
            .ForMember(dest => dest.BillingCountry, opt => opt.MapFrom(src => src.BillingCountry))
            .ForMember(dest => dest.Notes, opt => opt.MapFrom(src => src.Notes))
            .ForMember(dest => dest.EstimatedDeliveryDate, opt => opt.MapFrom(src => src.EstimatedDeliveryDate))
            .ForMember(dest => dest.DeliveredAt, opt => opt.MapFrom(src => src.DeliveredAt))
            .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
            .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt))
            .ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy))
            .ForMember(dest => dest.User, opt => opt.Ignore())
            .ForMember(dest => dest.User1, opt => opt.Ignore())
            .ForMember(dest => dest.OrderItems, opt => opt.Ignore())
            .ForMember(dest => dest.OrderPayments, opt => opt.Ignore())
            .ForMember(dest => dest.OrderRefunds, opt => opt.Ignore())
            .ForMember(dest => dest.OrderShipments, opt => opt.Ignore())
            .ForMember(dest => dest.OrderStatusHistories, opt => opt.Ignore());

        CreateMap<OrderEntity, Order>()
            .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.OrderId))
            .ForMember(dest => dest.OrderNumber, opt => opt.MapFrom(src => src.OrderNumber))
            .ForMember(dest => dest.UserId, opt => opt.MapFrom(src => src.UserId))
            .ForMember(dest => dest.OrderDate, opt => opt.MapFrom(src => src.OrderDate))
            .ForMember(dest => dest.SubTotal, opt => opt.MapFrom(src => src.SubTotal))
            .ForMember(dest => dest.TaxAmount, opt => opt.MapFrom(src => src.TaxAmount))
            .ForMember(dest => dest.ShippingAmount, opt => opt.MapFrom(src => src.ShippingAmount))
            .ForMember(dest => dest.DiscountAmount, opt => opt.MapFrom(src => src.DiscountAmount))
            .ForMember(dest => dest.TotalAmount, opt => opt.MapFrom(src => src.TotalAmount))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
            .ForMember(dest => dest.PaymentStatus, opt => opt.MapFrom(src => src.PaymentStatus))
            .ForMember(dest => dest.PaymentMethod, opt => opt.MapFrom(src => src.PaymentMethod))
            .ForMember(dest => dest.ShippingFirstName, opt => opt.MapFrom(src => src.ShippingFirstName))
            .ForMember(dest => dest.ShippingLastName, opt => opt.MapFrom(src => src.ShippingLastName))
            .ForMember(dest => dest.ShippingEmail, opt => opt.MapFrom(src => src.ShippingEmail))
            .ForMember(dest => dest.ShippingPhone, opt => opt.MapFrom(src => src.ShippingPhone))
            .ForMember(dest => dest.ShippingAddress, opt => opt.MapFrom(src => src.ShippingAddress))
            .ForMember(dest => dest.ShippingCity, opt => opt.MapFrom(src => src.ShippingCity))
            .ForMember(dest => dest.ShippingState, opt => opt.MapFrom(src => src.ShippingState))
            .ForMember(dest => dest.ShippingZipCode, opt => opt.MapFrom(src => src.ShippingZipCode))
            .ForMember(dest => dest.ShippingCountry, opt => opt.MapFrom(src => src.ShippingCountry))
            .ForMember(dest => dest.BillingFirstName, opt => opt.MapFrom(src => src.BillingFirstName))
            .ForMember(dest => dest.BillingLastName, opt => opt.MapFrom(src => src.BillingLastName))
            .ForMember(dest => dest.BillingEmail, opt => opt.MapFrom(src => src.BillingEmail))
            .ForMember(dest => dest.BillingPhone, opt => opt.MapFrom(src => src.BillingPhone))
            .ForMember(dest => dest.BillingAddress, opt => opt.MapFrom(src => src.BillingAddress))
            .ForMember(dest => dest.BillingCity, opt => opt.MapFrom(src => src.BillingCity))
            .ForMember(dest => dest.BillingState, opt => opt.MapFrom(src => src.BillingState))
            .ForMember(dest => dest.BillingZipCode, opt => opt.MapFrom(src => src.BillingZipCode))
            .ForMember(dest => dest.BillingCountry, opt => opt.MapFrom(src => src.BillingCountry))
            .ForMember(dest => dest.Notes, opt => opt.MapFrom(src => src.Notes))
            .ForMember(dest => dest.EstimatedDeliveryDate, opt => opt.MapFrom(src => src.EstimatedDeliveryDate))
            .ForMember(dest => dest.DeliveredAt, opt => opt.MapFrom(src => src.DeliveredAt))
            .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
            .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt))
            .ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy))
            .ForMember(dest => dest.User, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedByUser, opt => opt.Ignore())
            .ForMember(dest => dest.OrderItems, opt => opt.Ignore())
            .ForMember(dest => dest.OrderPayments, opt => opt.Ignore())
            .ForMember(dest => dest.OrderRefunds, opt => opt.Ignore())
            .ForMember(dest => dest.OrderShipments, opt => opt.Ignore())
            .ForMember(dest => dest.OrderStatusHistories, opt => opt.Ignore());

        // OrderItem mapping
        CreateMap<OrderItem, OrderItemEntity>()
            .ForMember(dest => dest.OrderItemId, opt => opt.MapFrom(src => src.OrderItemId))
            .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.OrderId))
            .ForMember(dest => dest.ProductId, opt => opt.MapFrom(src => src.ProductId))
            .ForMember(dest => dest.ProductVariantId, opt => opt.MapFrom(src => src.ProductVariantId))
            .ForMember(dest => dest.ProductName, opt => opt.MapFrom(src => src.ProductName))
            .ForMember(dest => dest.ProductSku, opt => opt.MapFrom(src => src.ProductSku))
            .ForMember(dest => dest.Quantity, opt => opt.MapFrom(src => src.Quantity))
            .ForMember(dest => dest.UnitPrice, opt => opt.MapFrom(src => src.UnitPrice))
            .ForMember(dest => dest.TotalPrice, opt => opt.MapFrom(src => src.TotalPrice))
            .ForMember(dest => dest.Order, opt => opt.Ignore())
            .ForMember(dest => dest.Product, opt => opt.Ignore())
            .ForMember(dest => dest.ProductVariant, opt => opt.Ignore())
            .ForMember(dest => dest.ShipmentItems, opt => opt.Ignore());

        CreateMap<OrderItemEntity, OrderItem>()
            .ForMember(dest => dest.OrderItemId, opt => opt.MapFrom(src => src.OrderItemId))
            .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.OrderId))
            .ForMember(dest => dest.ProductId, opt => opt.MapFrom(src => src.ProductId))
            .ForMember(dest => dest.ProductVariantId, opt => opt.MapFrom(src => src.ProductVariantId))
            .ForMember(dest => dest.ProductName, opt => opt.MapFrom(src => src.ProductName))
            .ForMember(dest => dest.ProductSku, opt => opt.MapFrom(src => src.ProductSku))
            .ForMember(dest => dest.Quantity, opt => opt.MapFrom(src => src.Quantity))
            .ForMember(dest => dest.UnitPrice, opt => opt.MapFrom(src => src.UnitPrice))
            .ForMember(dest => dest.TotalPrice, opt => opt.MapFrom(src => src.TotalPrice))
            .ForMember(dest => dest.Order, opt => opt.Ignore())
            .ForMember(dest => dest.Product, opt => opt.Ignore())
            .ForMember(dest => dest.ProductVariant, opt => opt.Ignore())
            .ForMember(dest => dest.ShipmentItems, opt => opt.Ignore());

        // OrderPayment mapping
        CreateMap<OrderPayment, OrderPaymentEntity>()
            .ForMember(dest => dest.PaymentId, opt => opt.MapFrom(src => src.PaymentId))
            .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.OrderId))
            .ForMember(dest => dest.PaymentMethod, opt => opt.MapFrom(src => src.PaymentMethod))
            .ForMember(dest => dest.TransactionId, opt => opt.MapFrom(src => src.TransactionId))
            .ForMember(dest => dest.GatewayResponse, opt => opt.MapFrom(src => src.GatewayResponse))
            .ForMember(dest => dest.Amount, opt => opt.MapFrom(src => src.Amount))
            .ForMember(dest => dest.Currency, opt => opt.MapFrom(src => src.Currency))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
            .ForMember(dest => dest.PaidAt, opt => opt.MapFrom(src => src.PaidAt))
            .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
            .ForMember(dest => dest.Order, opt => opt.Ignore())
            .ForMember(dest => dest.OrderRefunds, opt => opt.Ignore());

        CreateMap<OrderPaymentEntity, OrderPayment>()
            .ForMember(dest => dest.PaymentId, opt => opt.MapFrom(src => src.PaymentId))
            .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.OrderId))
            .ForMember(dest => dest.PaymentMethod, opt => opt.MapFrom(src => src.PaymentMethod))
            .ForMember(dest => dest.TransactionId, opt => opt.MapFrom(src => src.TransactionId))
            .ForMember(dest => dest.GatewayResponse, opt => opt.MapFrom(src => src.GatewayResponse))
            .ForMember(dest => dest.Amount, opt => opt.MapFrom(src => src.Amount))
            .ForMember(dest => dest.Currency, opt => opt.MapFrom(src => src.Currency))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
            .ForMember(dest => dest.PaidAt, opt => opt.MapFrom(src => src.PaidAt))
            .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
            .ForMember(dest => dest.Order, opt => opt.Ignore())
            .ForMember(dest => dest.OrderRefunds, opt => opt.Ignore());

        // OrderRefund mapping
        CreateMap<OrderRefund, OrderRefundEntity>()
            .ForMember(dest => dest.RefundId, opt => opt.MapFrom(src => src.RefundId))
            .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.OrderId))
            .ForMember(dest => dest.PaymentId, opt => opt.MapFrom(src => src.PaymentId))
            .ForMember(dest => dest.Amount, opt => opt.MapFrom(src => src.Amount))
            .ForMember(dest => dest.Reason, opt => opt.MapFrom(src => src.Reason))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
            .ForMember(dest => dest.RequestedAt, opt => opt.MapFrom(src => src.RequestedAt))
            .ForMember(dest => dest.ProcessedAt, opt => opt.MapFrom(src => src.ProcessedAt))
            .ForMember(dest => dest.ProcessedBy, opt => opt.MapFrom(src => src.ProcessedBy))
            .ForMember(dest => dest.Order, opt => opt.Ignore())
            .ForMember(dest => dest.OrderPayment, opt => opt.Ignore())
            .ForMember(dest => dest.User, opt => opt.Ignore());

        CreateMap<OrderRefundEntity, OrderRefund>()
            .ForMember(dest => dest.RefundId, opt => opt.MapFrom(src => src.RefundId))
            .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.OrderId))
            .ForMember(dest => dest.PaymentId, opt => opt.MapFrom(src => src.PaymentId))
            .ForMember(dest => dest.Amount, opt => opt.MapFrom(src => src.Amount))
            .ForMember(dest => dest.Reason, opt => opt.MapFrom(src => src.Reason))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
            .ForMember(dest => dest.RequestedAt, opt => opt.MapFrom(src => src.RequestedAt))
            .ForMember(dest => dest.ProcessedAt, opt => opt.MapFrom(src => src.ProcessedAt))
            .ForMember(dest => dest.ProcessedBy, opt => opt.MapFrom(src => src.ProcessedBy))
            .ForMember(dest => dest.Order, opt => opt.Ignore())
            .ForMember(dest => dest.OrderPayment, opt => opt.Ignore())
            .ForMember(dest => dest.ProcessedByUser, opt => opt.Ignore());

        // OrderShipment mapping
        CreateMap<OrderShipment, OrderShipmentEntity>()
            .ForMember(dest => dest.ShipmentId, opt => opt.MapFrom(src => src.ShipmentId))
            .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.OrderId))
            .ForMember(dest => dest.ShipmentNumber, opt => opt.MapFrom(src => src.ShipmentNumber))
            .ForMember(dest => dest.CarrierId, opt => opt.MapFrom(src => src.CarrierId))
            .ForMember(dest => dest.TrackingNumber, opt => opt.MapFrom(src => src.TrackingNumber))
            .ForMember(dest => dest.ShippedAt, opt => opt.MapFrom(src => src.ShippedAt))
            .ForMember(dest => dest.DeliveredAt, opt => opt.MapFrom(src => src.DeliveredAt))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
            .ForMember(dest => dest.ShippingCost, opt => opt.MapFrom(src => src.ShippingCost))
            .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
            .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt))
            .ForMember(dest => dest.Order, opt => opt.Ignore())
            .ForMember(dest => dest.ShipmentCarrier, opt => opt.Ignore())
            .ForMember(dest => dest.ShipmentItems, opt => opt.Ignore());

        CreateMap<OrderShipmentEntity, OrderShipment>()
            .ForMember(dest => dest.ShipmentId, opt => opt.MapFrom(src => src.ShipmentId))
            .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.OrderId))
            .ForMember(dest => dest.ShipmentNumber, opt => opt.MapFrom(src => src.ShipmentNumber))
            .ForMember(dest => dest.CarrierId, opt => opt.MapFrom(src => src.CarrierId))
            .ForMember(dest => dest.TrackingNumber, opt => opt.MapFrom(src => src.TrackingNumber))
            .ForMember(dest => dest.ShippedAt, opt => opt.MapFrom(src => src.ShippedAt))
            .ForMember(dest => dest.DeliveredAt, opt => opt.MapFrom(src => src.DeliveredAt))
            .ForMember(dest => dest.Status, opt => opt.MapFrom(src => src.Status))
            .ForMember(dest => dest.ShippingCost, opt => opt.MapFrom(src => src.ShippingCost))
            .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
            .ForMember(dest => dest.UpdatedAt, opt => opt.MapFrom(src => src.UpdatedAt))
            .ForMember(dest => dest.Order, opt => opt.Ignore())
            .ForMember(dest => dest.ShipmentCarrier, opt => opt.Ignore())
            .ForMember(dest => dest.ShipmentItems, opt => opt.Ignore());

        // OrderStatusHistory mapping
        CreateMap<OrderStatusHistory, OrderStatusHistoryEntity>()
            .ForMember(dest => dest.HistoryId, opt => opt.MapFrom(src => src.HistoryId))
            .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.OrderId))
            .ForMember(dest => dest.FromStatus, opt => opt.MapFrom(src => src.FromStatus))
            .ForMember(dest => dest.ToStatus, opt => opt.MapFrom(src => src.ToStatus))
            .ForMember(dest => dest.Comment, opt => opt.MapFrom(src => src.Comment))
            .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
            .ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy))
            .ForMember(dest => dest.Order, opt => opt.Ignore())
            .ForMember(dest => dest.User, opt => opt.Ignore());

        CreateMap<OrderStatusHistoryEntity, OrderStatusHistory>()
            .ForMember(dest => dest.HistoryId, opt => opt.MapFrom(src => src.HistoryId))
            .ForMember(dest => dest.OrderId, opt => opt.MapFrom(src => src.OrderId))
            .ForMember(dest => dest.FromStatus, opt => opt.MapFrom(src => src.FromStatus))
            .ForMember(dest => dest.ToStatus, opt => opt.MapFrom(src => src.ToStatus))
            .ForMember(dest => dest.Comment, opt => opt.MapFrom(src => src.Comment))
            .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
            .ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy))
            .ForMember(dest => dest.Order, opt => opt.Ignore())
            .ForMember(dest => dest.CreatedByUser, opt => opt.Ignore());

        // ShipmentCarrier mapping
        CreateMap<ShipmentCarrier, ShipmentCarrierEntity>()
            .ForMember(dest => dest.CarrierId, opt => opt.MapFrom(src => src.CarrierId))
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
            .ForMember(dest => dest.Code, opt => opt.MapFrom(src => src.Code))
            .ForMember(dest => dest.Website, opt => opt.MapFrom(src => src.Website))
            .ForMember(dest => dest.Phone, opt => opt.MapFrom(src => src.Phone))
            .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
            .ForMember(dest => dest.OrderShipments, opt => opt.Ignore());

        CreateMap<ShipmentCarrierEntity, ShipmentCarrier>()
            .ForMember(dest => dest.CarrierId, opt => opt.MapFrom(src => src.CarrierId))
            .ForMember(dest => dest.Name, opt => opt.MapFrom(src => src.Name))
            .ForMember(dest => dest.Code, opt => opt.MapFrom(src => src.Code))
            .ForMember(dest => dest.Website, opt => opt.MapFrom(src => src.Website))
            .ForMember(dest => dest.Phone, opt => opt.MapFrom(src => src.Phone))
            .ForMember(dest => dest.CreatedAt, opt => opt.MapFrom(src => src.CreatedAt))
            .ForMember(dest => dest.OrderShipments, opt => opt.Ignore());

        // ShipmentItem mapping
        CreateMap<ShipmentItem, ShipmentItemEntity>()
            .ForMember(dest => dest.ShipmentItemId, opt => opt.MapFrom(src => src.ShipmentItemId))
            .ForMember(dest => dest.ShipmentId, opt => opt.MapFrom(src => src.ShipmentId))
            .ForMember(dest => dest.OrderItemId, opt => opt.MapFrom(src => src.OrderItemId))
            .ForMember(dest => dest.Quantity, opt => opt.MapFrom(src => src.Quantity))
            .ForMember(dest => dest.OrderShipment, opt => opt.Ignore())
            .ForMember(dest => dest.OrderItem, opt => opt.Ignore());

        CreateMap<ShipmentItemEntity, ShipmentItem>()
            .ForMember(dest => dest.ShipmentItemId, opt => opt.MapFrom(src => src.ShipmentItemId))
            .ForMember(dest => dest.ShipmentId, opt => opt.MapFrom(src => src.ShipmentId))
            .ForMember(dest => dest.OrderItemId, opt => opt.MapFrom(src => src.OrderItemId))
            .ForMember(dest => dest.Quantity, opt => opt.MapFrom(src => src.Quantity))
            .ForMember(dest => dest.OrderShipment, opt => opt.Ignore())
            .ForMember(dest => dest.OrderItem, opt => opt.Ignore());
    }
}
