//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'AuditLog'.<br/><br/></summary>
	[Serializable]
	public partial class AuditLogEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private UserEntity _user;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static AuditLogEntityStaticMetaData _staticMetaData = new AuditLogEntityStaticMetaData();
		private static AuditLogRelations _relationsFactory = new AuditLogRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class AuditLogEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public AuditLogEntityStaticMetaData()
			{
				SetEntityCoreInfo("AuditLogEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.AuditLogEntity, typeof(AuditLogEntity), typeof(AuditLogEntityFactory), false);
				AddNavigatorMetaData<AuditLogEntity, UserEntity>("User", "AuditLogs", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, GroceryEcommerce.RelationClasses.StaticAuditLogRelations.UserEntityUsingUserIdStatic, ()=>new AuditLogRelations().UserEntityUsingUserId, null, new int[] { (int)AuditLogFieldIndex.UserId }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static AuditLogEntity()
		{
		}

		/// <summary> CTor</summary>
		public AuditLogEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public AuditLogEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this AuditLogEntity</param>
		public AuditLogEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="auditId">PK value for AuditLog which data should be fetched into this AuditLog object</param>
		public AuditLogEntity(System.Guid auditId) : this(auditId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="auditId">PK value for AuditLog which data should be fetched into this AuditLog object</param>
		/// <param name="validator">The custom validator object for this AuditLogEntity</param>
		public AuditLogEntity(System.Guid auditId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.AuditId = auditId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected AuditLogEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this AuditLogEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static AuditLogRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The Action property of the Entity AuditLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "audit_logs"."action".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 200.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Action
		{
			get { return (System.String)GetValue((int)AuditLogFieldIndex.Action, true); }
			set { SetValue((int)AuditLogFieldIndex.Action, value); }
		}

		/// <summary>The AuditId property of the Entity AuditLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "audit_logs"."audit_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid AuditId
		{
			get { return (System.Guid)GetValue((int)AuditLogFieldIndex.AuditId, true); }
			set { SetValue((int)AuditLogFieldIndex.AuditId, value); }
		}

		/// <summary>The CreatedAt property of the Entity AuditLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "audit_logs"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)AuditLogFieldIndex.CreatedAt, true); }
			set { SetValue((int)AuditLogFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Detail property of the Entity AuditLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "audit_logs"."detail".<br/>Table field type characteristics (type, precision, scale, length): Jsonb, 0, 0, 2147483647.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Detail
		{
			get { return (System.String)GetValue((int)AuditLogFieldIndex.Detail, true); }
			set { SetValue((int)AuditLogFieldIndex.Detail, value); }
		}

		/// <summary>The Entity property of the Entity AuditLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "audit_logs"."entity".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Entity
		{
			get { return (System.String)GetValue((int)AuditLogFieldIndex.Entity, true); }
			set { SetValue((int)AuditLogFieldIndex.Entity, value); }
		}

		/// <summary>The EntityId property of the Entity AuditLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "audit_logs"."entity_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> EntityId
		{
			get { return (Nullable<System.Guid>)GetValue((int)AuditLogFieldIndex.EntityId, false); }
			set { SetValue((int)AuditLogFieldIndex.EntityId, value); }
		}

		/// <summary>The UserId property of the Entity AuditLog<br/><br/></summary>
		/// <remarks>Mapped on  table field: "audit_logs"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> UserId
		{
			get { return (Nullable<System.Guid>)GetValue((int)AuditLogFieldIndex.UserId, false); }
			set { SetValue((int)AuditLogFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace GroceryEcommerce
{
	public enum AuditLogFieldIndex
	{
		///<summary>Action. </summary>
		Action,
		///<summary>AuditId. </summary>
		AuditId,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Detail. </summary>
		Detail,
		///<summary>Entity. </summary>
		Entity,
		///<summary>EntityId. </summary>
		EntityId,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: AuditLog. </summary>
	public partial class AuditLogRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between AuditLogEntity and UserEntity over the m:1 relation they have, using the relation between the fields: AuditLog.UserId - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.UserId, AuditLogFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticAuditLogRelations
	{
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new AuditLogRelations().UserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticAuditLogRelations() { }
	}
}
