//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Coupon'.<br/><br/></summary>
	[Serializable]
	public partial class CouponEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<CouponUsageEntity> _couponUsages;
		private UserEntity _user;
		private UserEntity _user1;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static CouponEntityStaticMetaData _staticMetaData = new CouponEntityStaticMetaData();
		private static CouponRelations _relationsFactory = new CouponRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
			/// <summary>Member name User1</summary>
			public static readonly string User1 = "User1";
			/// <summary>Member name CouponUsages</summary>
			public static readonly string CouponUsages = "CouponUsages";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CouponEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CouponEntityStaticMetaData()
			{
				SetEntityCoreInfo("CouponEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.CouponEntity, typeof(CouponEntity), typeof(CouponEntityFactory), false);
				AddNavigatorMetaData<CouponEntity, EntityCollection<CouponUsageEntity>>("CouponUsages", a => a._couponUsages, (a, b) => a._couponUsages = b, a => a.CouponUsages, () => new CouponRelations().CouponUsageEntityUsingCouponId, typeof(CouponUsageEntity), (int)GroceryEcommerce.EntityType.CouponUsageEntity);
				AddNavigatorMetaData<CouponEntity, UserEntity>("User", "Coupons", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, GroceryEcommerce.RelationClasses.StaticCouponRelations.UserEntityUsingCreatedByStatic, ()=>new CouponRelations().UserEntityUsingCreatedBy, null, new int[] { (int)CouponFieldIndex.CreatedBy }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
				AddNavigatorMetaData<CouponEntity, UserEntity>("User1", "Coupons1", (a, b) => a._user1 = b, a => a._user1, (a, b) => a.User1 = b, GroceryEcommerce.RelationClasses.StaticCouponRelations.UserEntityUsingUpdatedByStatic, ()=>new CouponRelations().UserEntityUsingUpdatedBy, null, new int[] { (int)CouponFieldIndex.UpdatedBy }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static CouponEntity()
		{
		}

		/// <summary> CTor</summary>
		public CouponEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CouponEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CouponEntity</param>
		public CouponEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="couponId">PK value for Coupon which data should be fetched into this Coupon object</param>
		public CouponEntity(System.Guid couponId) : this(couponId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="couponId">PK value for Coupon which data should be fetched into this Coupon object</param>
		/// <param name="validator">The custom validator object for this CouponEntity</param>
		public CouponEntity(System.Guid couponId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.CouponId = couponId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CouponEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: Code .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCCode()
		{
			var filter = new PredicateExpression();
			filter.Add(GroceryEcommerce.HelperClasses.CouponFields.Code == this.Fields.GetCurrentValue((int)CouponFieldIndex.Code));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'CouponUsage' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCouponUsages() { return CreateRelationInfoForNavigator("CouponUsages"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser1() { return CreateRelationInfoForNavigator("User1"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CouponEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CouponRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CouponUsage' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCouponUsages { get { return _staticMetaData.GetPrefetchPathElement("CouponUsages", CommonEntityBase.CreateEntityCollection<CouponUsageEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser1 { get { return _staticMetaData.GetPrefetchPathElement("User1", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The Code property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Code
		{
			get { return (System.String)GetValue((int)CouponFieldIndex.Code, true); }
			set { SetValue((int)CouponFieldIndex.Code, value); }
		}

		/// <summary>The CouponId property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."coupon_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid CouponId
		{
			get { return (System.Guid)GetValue((int)CouponFieldIndex.CouponId, true); }
			set { SetValue((int)CouponFieldIndex.CouponId, value); }
		}

		/// <summary>The CreatedAt property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)CouponFieldIndex.CreatedAt, true); }
			set { SetValue((int)CouponFieldIndex.CreatedAt, value); }
		}

		/// <summary>The CreatedBy property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."created_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid CreatedBy
		{
			get { return (System.Guid)GetValue((int)CouponFieldIndex.CreatedBy, true); }
			set { SetValue((int)CouponFieldIndex.CreatedBy, value); }
		}

		/// <summary>The Description property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."description".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)CouponFieldIndex.Description, true); }
			set { SetValue((int)CouponFieldIndex.Description, value); }
		}

		/// <summary>The DiscountType property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."discount_type".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 DiscountType
		{
			get { return (System.Int16)GetValue((int)CouponFieldIndex.DiscountType, true); }
			set { SetValue((int)CouponFieldIndex.DiscountType, value); }
		}

		/// <summary>The DiscountValue property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."discount_value".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal DiscountValue
		{
			get { return (System.Decimal)GetValue((int)CouponFieldIndex.DiscountValue, true); }
			set { SetValue((int)CouponFieldIndex.DiscountValue, value); }
		}

		/// <summary>The MaxDiscountAmount property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."max_discount_amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> MaxDiscountAmount
		{
			get { return (Nullable<System.Decimal>)GetValue((int)CouponFieldIndex.MaxDiscountAmount, false); }
			set { SetValue((int)CouponFieldIndex.MaxDiscountAmount, value); }
		}

		/// <summary>The MinOrderAmount property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."min_order_amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> MinOrderAmount
		{
			get { return (Nullable<System.Decimal>)GetValue((int)CouponFieldIndex.MinOrderAmount, false); }
			set { SetValue((int)CouponFieldIndex.MinOrderAmount, value); }
		}

		/// <summary>The Name property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)CouponFieldIndex.Name, true); }
			set { SetValue((int)CouponFieldIndex.Name, value); }
		}

		/// <summary>The Status property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."status".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 Status
		{
			get { return (System.Int16)GetValue((int)CouponFieldIndex.Status, true); }
			set { SetValue((int)CouponFieldIndex.Status, value); }
		}

		/// <summary>The UpdatedAt property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)CouponFieldIndex.UpdatedAt, false); }
			set { SetValue((int)CouponFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UpdatedBy property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."updated_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> UpdatedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)CouponFieldIndex.UpdatedBy, false); }
			set { SetValue((int)CouponFieldIndex.UpdatedBy, value); }
		}

		/// <summary>The UsageCount property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."usage_count".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 UsageCount
		{
			get { return (System.Int32)GetValue((int)CouponFieldIndex.UsageCount, true); }
			set { SetValue((int)CouponFieldIndex.UsageCount, value); }
		}

		/// <summary>The UsageLimit property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."usage_limit".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> UsageLimit
		{
			get { return (Nullable<System.Int32>)GetValue((int)CouponFieldIndex.UsageLimit, false); }
			set { SetValue((int)CouponFieldIndex.UsageLimit, value); }
		}

		/// <summary>The UserUsageLimit property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."user_usage_limit".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Int32> UserUsageLimit
		{
			get { return (Nullable<System.Int32>)GetValue((int)CouponFieldIndex.UserUsageLimit, false); }
			set { SetValue((int)CouponFieldIndex.UserUsageLimit, value); }
		}

		/// <summary>The ValidFrom property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."valid_from".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime ValidFrom
		{
			get { return (System.DateTime)GetValue((int)CouponFieldIndex.ValidFrom, true); }
			set { SetValue((int)CouponFieldIndex.ValidFrom, value); }
		}

		/// <summary>The ValidTo property of the Entity Coupon<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupons"."valid_to".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime ValidTo
		{
			get { return (System.DateTime)GetValue((int)CouponFieldIndex.ValidTo, true); }
			set { SetValue((int)CouponFieldIndex.ValidTo, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'CouponUsageEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(CouponUsageEntity))]
		public virtual EntityCollection<CouponUsageEntity> CouponUsages { get { return GetOrCreateEntityCollection<CouponUsageEntity, CouponUsageEntityFactory>("Coupon", true, false, ref _couponUsages); } }

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User1
		{
			get { return _user1; }
			set { SetSingleRelatedEntityNavigator(value, "User1"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace GroceryEcommerce
{
	public enum CouponFieldIndex
	{
		///<summary>Code. </summary>
		Code,
		///<summary>CouponId. </summary>
		CouponId,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>CreatedBy. </summary>
		CreatedBy,
		///<summary>Description. </summary>
		Description,
		///<summary>DiscountType. </summary>
		DiscountType,
		///<summary>DiscountValue. </summary>
		DiscountValue,
		///<summary>MaxDiscountAmount. </summary>
		MaxDiscountAmount,
		///<summary>MinOrderAmount. </summary>
		MinOrderAmount,
		///<summary>Name. </summary>
		Name,
		///<summary>Status. </summary>
		Status,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UpdatedBy. </summary>
		UpdatedBy,
		///<summary>UsageCount. </summary>
		UsageCount,
		///<summary>UsageLimit. </summary>
		UsageLimit,
		///<summary>UserUsageLimit. </summary>
		UserUsageLimit,
		///<summary>ValidFrom. </summary>
		ValidFrom,
		///<summary>ValidTo. </summary>
		ValidTo,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Coupon. </summary>
	public partial class CouponRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between CouponEntity and CouponUsageEntity over the 1:n relation they have, using the relation between the fields: Coupon.CouponId - CouponUsage.CouponId</summary>
		public virtual IEntityRelation CouponUsageEntityUsingCouponId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "CouponUsages", true, new[] { CouponFields.CouponId, CouponUsageFields.CouponId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between CouponEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Coupon.CreatedBy - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingCreatedBy
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.UserId, CouponFields.CreatedBy }); }
		}

		/// <summary>Returns a new IEntityRelation object, between CouponEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Coupon.UpdatedBy - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingUpdatedBy
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User1", false, new[] { UserFields.UserId, CouponFields.UpdatedBy }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCouponRelations
	{
		internal static readonly IEntityRelation CouponUsageEntityUsingCouponIdStatic = new CouponRelations().CouponUsageEntityUsingCouponId;
		internal static readonly IEntityRelation UserEntityUsingCreatedByStatic = new CouponRelations().UserEntityUsingCreatedBy;
		internal static readonly IEntityRelation UserEntityUsingUpdatedByStatic = new CouponRelations().UserEntityUsingUpdatedBy;

		/// <summary>CTor</summary>
		static StaticCouponRelations() { }
	}
}
