//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'CouponUsage'.<br/><br/></summary>
	[Serializable]
	public partial class CouponUsageEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private UserEntity _user;
		private CouponEntity _coupon;
		private OrderEntity _order;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static CouponUsageEntityStaticMetaData _staticMetaData = new CouponUsageEntityStaticMetaData();
		private static CouponUsageRelations _relationsFactory = new CouponUsageRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
			/// <summary>Member name Coupon</summary>
			public static readonly string Coupon = "Coupon";
			/// <summary>Member name Order</summary>
			public static readonly string Order = "Order";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class CouponUsageEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public CouponUsageEntityStaticMetaData()
			{
				SetEntityCoreInfo("CouponUsageEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.CouponUsageEntity, typeof(CouponUsageEntity), typeof(CouponUsageEntityFactory), false);
				AddNavigatorMetaData<CouponUsageEntity, UserEntity>("User", "CouponUsages", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, GroceryEcommerce.RelationClasses.StaticCouponUsageRelations.UserEntityUsingUserIdStatic, ()=>new CouponUsageRelations().UserEntityUsingUserId, null, new int[] { (int)CouponUsageFieldIndex.UserId }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
				AddNavigatorMetaData<CouponUsageEntity, CouponEntity>("Coupon", "CouponUsages", (a, b) => a._coupon = b, a => a._coupon, (a, b) => a.Coupon = b, GroceryEcommerce.RelationClasses.StaticCouponUsageRelations.CouponEntityUsingCouponIdStatic, ()=>new CouponUsageRelations().CouponEntityUsingCouponId, null, new int[] { (int)CouponUsageFieldIndex.CouponId }, null, true, (int)GroceryEcommerce.EntityType.CouponEntity);
				AddNavigatorMetaData<CouponUsageEntity, OrderEntity>("Order", "CouponUsages", (a, b) => a._order = b, a => a._order, (a, b) => a.Order = b, GroceryEcommerce.RelationClasses.StaticCouponUsageRelations.OrderEntityUsingOrderIdStatic, ()=>new CouponUsageRelations().OrderEntityUsingOrderId, null, new int[] { (int)CouponUsageFieldIndex.OrderId }, null, true, (int)GroceryEcommerce.EntityType.OrderEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static CouponUsageEntity()
		{
		}

		/// <summary> CTor</summary>
		public CouponUsageEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public CouponUsageEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this CouponUsageEntity</param>
		public CouponUsageEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="usageId">PK value for CouponUsage which data should be fetched into this CouponUsage object</param>
		public CouponUsageEntity(System.Guid usageId) : this(usageId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="usageId">PK value for CouponUsage which data should be fetched into this CouponUsage object</param>
		/// <param name="validator">The custom validator object for this CouponUsageEntity</param>
		public CouponUsageEntity(System.Guid usageId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.UsageId = usageId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected CouponUsageEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Coupon' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCoupon() { return CreateRelationInfoForNavigator("Coupon"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Order' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrder() { return CreateRelationInfoForNavigator("Order"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this CouponUsageEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static CouponUsageRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Coupon' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCoupon { get { return _staticMetaData.GetPrefetchPathElement("Coupon", CommonEntityBase.CreateEntityCollection<CouponEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Order' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrder { get { return _staticMetaData.GetPrefetchPathElement("Order", CommonEntityBase.CreateEntityCollection<OrderEntity>()); } }

		/// <summary>The CouponId property of the Entity CouponUsage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupon_usages"."coupon_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid CouponId
		{
			get { return (System.Guid)GetValue((int)CouponUsageFieldIndex.CouponId, true); }
			set { SetValue((int)CouponUsageFieldIndex.CouponId, value); }
		}

		/// <summary>The DiscountAmount property of the Entity CouponUsage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupon_usages"."discount_amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal DiscountAmount
		{
			get { return (System.Decimal)GetValue((int)CouponUsageFieldIndex.DiscountAmount, true); }
			set { SetValue((int)CouponUsageFieldIndex.DiscountAmount, value); }
		}

		/// <summary>The OrderId property of the Entity CouponUsage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupon_usages"."order_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid OrderId
		{
			get { return (System.Guid)GetValue((int)CouponUsageFieldIndex.OrderId, true); }
			set { SetValue((int)CouponUsageFieldIndex.OrderId, value); }
		}

		/// <summary>The UsageId property of the Entity CouponUsage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupon_usages"."usage_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid UsageId
		{
			get { return (System.Guid)GetValue((int)CouponUsageFieldIndex.UsageId, true); }
			set { SetValue((int)CouponUsageFieldIndex.UsageId, value); }
		}

		/// <summary>The UsedAt property of the Entity CouponUsage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupon_usages"."used_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime UsedAt
		{
			get { return (System.DateTime)GetValue((int)CouponUsageFieldIndex.UsedAt, true); }
			set { SetValue((int)CouponUsageFieldIndex.UsedAt, value); }
		}

		/// <summary>The UserId property of the Entity CouponUsage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "coupon_usages"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)CouponUsageFieldIndex.UserId, true); }
			set { SetValue((int)CouponUsageFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		/// <summary>Gets / sets related entity of type 'CouponEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CouponEntity Coupon
		{
			get { return _coupon; }
			set { SetSingleRelatedEntityNavigator(value, "Coupon"); }
		}

		/// <summary>Gets / sets related entity of type 'OrderEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual OrderEntity Order
		{
			get { return _order; }
			set { SetSingleRelatedEntityNavigator(value, "Order"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace GroceryEcommerce
{
	public enum CouponUsageFieldIndex
	{
		///<summary>CouponId. </summary>
		CouponId,
		///<summary>DiscountAmount. </summary>
		DiscountAmount,
		///<summary>OrderId. </summary>
		OrderId,
		///<summary>UsageId. </summary>
		UsageId,
		///<summary>UsedAt. </summary>
		UsedAt,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: CouponUsage. </summary>
	public partial class CouponUsageRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between CouponUsageEntity and UserEntity over the m:1 relation they have, using the relation between the fields: CouponUsage.UserId - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.UserId, CouponUsageFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between CouponUsageEntity and CouponEntity over the m:1 relation they have, using the relation between the fields: CouponUsage.CouponId - Coupon.CouponId</summary>
		public virtual IEntityRelation CouponEntityUsingCouponId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Coupon", false, new[] { CouponFields.CouponId, CouponUsageFields.CouponId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between CouponUsageEntity and OrderEntity over the m:1 relation they have, using the relation between the fields: CouponUsage.OrderId - Order.OrderId</summary>
		public virtual IEntityRelation OrderEntityUsingOrderId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Order", false, new[] { OrderFields.OrderId, CouponUsageFields.OrderId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticCouponUsageRelations
	{
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new CouponUsageRelations().UserEntityUsingUserId;
		internal static readonly IEntityRelation CouponEntityUsingCouponIdStatic = new CouponUsageRelations().CouponEntityUsingCouponId;
		internal static readonly IEntityRelation OrderEntityUsingOrderIdStatic = new CouponUsageRelations().OrderEntityUsingOrderId;

		/// <summary>CTor</summary>
		static StaticCouponUsageRelations() { }
	}
}
