//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'EmailTemplate'.<br/><br/></summary>
	[Serializable]
	public partial class EmailTemplateEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static EmailTemplateEntityStaticMetaData _staticMetaData = new EmailTemplateEntityStaticMetaData();
		private static EmailTemplateRelations _relationsFactory = new EmailTemplateRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class EmailTemplateEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public EmailTemplateEntityStaticMetaData()
			{
				SetEntityCoreInfo("EmailTemplateEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.EmailTemplateEntity, typeof(EmailTemplateEntity), typeof(EmailTemplateEntityFactory), false);
			}
		}

		/// <summary>Static ctor</summary>
		static EmailTemplateEntity()
		{
		}

		/// <summary> CTor</summary>
		public EmailTemplateEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public EmailTemplateEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this EmailTemplateEntity</param>
		public EmailTemplateEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="templateId">PK value for EmailTemplate which data should be fetched into this EmailTemplate object</param>
		public EmailTemplateEntity(System.Guid templateId) : this(templateId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="templateId">PK value for EmailTemplate which data should be fetched into this EmailTemplate object</param>
		/// <param name="validator">The custom validator object for this EmailTemplateEntity</param>
		public EmailTemplateEntity(System.Guid templateId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.TemplateId = templateId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected EmailTemplateEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this EmailTemplateEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static EmailTemplateRelations Relations { get { return _relationsFactory; } }

		/// <summary>The Body property of the Entity EmailTemplate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "email_templates"."body".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Body
		{
			get { return (System.String)GetValue((int)EmailTemplateFieldIndex.Body, true); }
			set { SetValue((int)EmailTemplateFieldIndex.Body, value); }
		}

		/// <summary>The CreatedAt property of the Entity EmailTemplate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "email_templates"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)EmailTemplateFieldIndex.CreatedAt, true); }
			set { SetValue((int)EmailTemplateFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Language property of the Entity EmailTemplate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "email_templates"."language".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 10.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Language
		{
			get { return (System.String)GetValue((int)EmailTemplateFieldIndex.Language, true); }
			set { SetValue((int)EmailTemplateFieldIndex.Language, value); }
		}

		/// <summary>The Name property of the Entity EmailTemplate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "email_templates"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)EmailTemplateFieldIndex.Name, true); }
			set { SetValue((int)EmailTemplateFieldIndex.Name, value); }
		}

		/// <summary>The Subject property of the Entity EmailTemplate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "email_templates"."subject".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Subject
		{
			get { return (System.String)GetValue((int)EmailTemplateFieldIndex.Subject, true); }
			set { SetValue((int)EmailTemplateFieldIndex.Subject, value); }
		}

		/// <summary>The TemplateId property of the Entity EmailTemplate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "email_templates"."template_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid TemplateId
		{
			get { return (System.Guid)GetValue((int)EmailTemplateFieldIndex.TemplateId, true); }
			set { SetValue((int)EmailTemplateFieldIndex.TemplateId, value); }
		}

		/// <summary>The UpdatedAt property of the Entity EmailTemplate<br/><br/></summary>
		/// <remarks>Mapped on  table field: "email_templates"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)EmailTemplateFieldIndex.UpdatedAt, false); }
			set { SetValue((int)EmailTemplateFieldIndex.UpdatedAt, value); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace GroceryEcommerce
{
	public enum EmailTemplateFieldIndex
	{
		///<summary>Body. </summary>
		Body,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Language. </summary>
		Language,
		///<summary>Name. </summary>
		Name,
		///<summary>Subject. </summary>
		Subject,
		///<summary>TemplateId. </summary>
		TemplateId,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: EmailTemplate. </summary>
	public partial class EmailTemplateRelations: RelationFactory
	{

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticEmailTemplateRelations
	{

		/// <summary>CTor</summary>
		static StaticEmailTemplateRelations() { }
	}
}
