//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'Order'.<br/><br/></summary>
	[Serializable]
	public partial class OrderEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<CouponUsageEntity> _couponUsages;
		private EntityCollection<ProductReviewEntity> _productReviews;
		private EntityCollection<OrderItemEntity> _orderItems;
		private EntityCollection<OrderPaymentEntity> _orderPayments;
		private EntityCollection<OrderRefundEntity> _orderRefunds;
		private EntityCollection<OrderShipmentEntity> _orderShipments;
		private EntityCollection<OrderStatusHistoryEntity> _orderStatusHistories;
		private UserEntity _user;
		private UserEntity _user1;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static OrderEntityStaticMetaData _staticMetaData = new OrderEntityStaticMetaData();
		private static OrderRelations _relationsFactory = new OrderRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
			/// <summary>Member name User1</summary>
			public static readonly string User1 = "User1";
			/// <summary>Member name CouponUsages</summary>
			public static readonly string CouponUsages = "CouponUsages";
			/// <summary>Member name ProductReviews</summary>
			public static readonly string ProductReviews = "ProductReviews";
			/// <summary>Member name OrderItems</summary>
			public static readonly string OrderItems = "OrderItems";
			/// <summary>Member name OrderPayments</summary>
			public static readonly string OrderPayments = "OrderPayments";
			/// <summary>Member name OrderRefunds</summary>
			public static readonly string OrderRefunds = "OrderRefunds";
			/// <summary>Member name OrderShipments</summary>
			public static readonly string OrderShipments = "OrderShipments";
			/// <summary>Member name OrderStatusHistories</summary>
			public static readonly string OrderStatusHistories = "OrderStatusHistories";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class OrderEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public OrderEntityStaticMetaData()
			{
				SetEntityCoreInfo("OrderEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.OrderEntity, typeof(OrderEntity), typeof(OrderEntityFactory), false);
				AddNavigatorMetaData<OrderEntity, EntityCollection<CouponUsageEntity>>("CouponUsages", a => a._couponUsages, (a, b) => a._couponUsages = b, a => a.CouponUsages, () => new OrderRelations().CouponUsageEntityUsingOrderId, typeof(CouponUsageEntity), (int)GroceryEcommerce.EntityType.CouponUsageEntity);
				AddNavigatorMetaData<OrderEntity, EntityCollection<ProductReviewEntity>>("ProductReviews", a => a._productReviews, (a, b) => a._productReviews = b, a => a.ProductReviews, () => new OrderRelations().ProductReviewEntityUsingOrderId, typeof(ProductReviewEntity), (int)GroceryEcommerce.EntityType.ProductReviewEntity);
				AddNavigatorMetaData<OrderEntity, EntityCollection<OrderItemEntity>>("OrderItems", a => a._orderItems, (a, b) => a._orderItems = b, a => a.OrderItems, () => new OrderRelations().OrderItemEntityUsingOrderId, typeof(OrderItemEntity), (int)GroceryEcommerce.EntityType.OrderItemEntity);
				AddNavigatorMetaData<OrderEntity, EntityCollection<OrderPaymentEntity>>("OrderPayments", a => a._orderPayments, (a, b) => a._orderPayments = b, a => a.OrderPayments, () => new OrderRelations().OrderPaymentEntityUsingOrderId, typeof(OrderPaymentEntity), (int)GroceryEcommerce.EntityType.OrderPaymentEntity);
				AddNavigatorMetaData<OrderEntity, EntityCollection<OrderRefundEntity>>("OrderRefunds", a => a._orderRefunds, (a, b) => a._orderRefunds = b, a => a.OrderRefunds, () => new OrderRelations().OrderRefundEntityUsingOrderId, typeof(OrderRefundEntity), (int)GroceryEcommerce.EntityType.OrderRefundEntity);
				AddNavigatorMetaData<OrderEntity, EntityCollection<OrderShipmentEntity>>("OrderShipments", a => a._orderShipments, (a, b) => a._orderShipments = b, a => a.OrderShipments, () => new OrderRelations().OrderShipmentEntityUsingOrderId, typeof(OrderShipmentEntity), (int)GroceryEcommerce.EntityType.OrderShipmentEntity);
				AddNavigatorMetaData<OrderEntity, EntityCollection<OrderStatusHistoryEntity>>("OrderStatusHistories", a => a._orderStatusHistories, (a, b) => a._orderStatusHistories = b, a => a.OrderStatusHistories, () => new OrderRelations().OrderStatusHistoryEntityUsingOrderId, typeof(OrderStatusHistoryEntity), (int)GroceryEcommerce.EntityType.OrderStatusHistoryEntity);
				AddNavigatorMetaData<OrderEntity, UserEntity>("User", "Orders", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, GroceryEcommerce.RelationClasses.StaticOrderRelations.UserEntityUsingCreatedByStatic, ()=>new OrderRelations().UserEntityUsingCreatedBy, null, new int[] { (int)OrderFieldIndex.CreatedBy }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
				AddNavigatorMetaData<OrderEntity, UserEntity>("User1", "Orders1", (a, b) => a._user1 = b, a => a._user1, (a, b) => a.User1 = b, GroceryEcommerce.RelationClasses.StaticOrderRelations.UserEntityUsingUserIdStatic, ()=>new OrderRelations().UserEntityUsingUserId, null, new int[] { (int)OrderFieldIndex.UserId }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static OrderEntity()
		{
		}

		/// <summary> CTor</summary>
		public OrderEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public OrderEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this OrderEntity</param>
		public OrderEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="orderId">PK value for Order which data should be fetched into this Order object</param>
		public OrderEntity(System.Guid orderId) : this(orderId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="orderId">PK value for Order which data should be fetched into this Order object</param>
		/// <param name="validator">The custom validator object for this OrderEntity</param>
		public OrderEntity(System.Guid orderId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.OrderId = orderId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected OrderEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: OrderNumber .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCOrderNumber()
		{
			var filter = new PredicateExpression();
			filter.Add(GroceryEcommerce.HelperClasses.OrderFields.OrderNumber == this.Fields.GetCurrentValue((int)OrderFieldIndex.OrderNumber));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'CouponUsage' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCouponUsages() { return CreateRelationInfoForNavigator("CouponUsages"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ProductReview' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductReviews() { return CreateRelationInfoForNavigator("ProductReviews"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'OrderItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrderItems() { return CreateRelationInfoForNavigator("OrderItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'OrderPayment' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrderPayments() { return CreateRelationInfoForNavigator("OrderPayments"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'OrderRefund' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrderRefunds() { return CreateRelationInfoForNavigator("OrderRefunds"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'OrderShipment' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrderShipments() { return CreateRelationInfoForNavigator("OrderShipments"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'OrderStatusHistory' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrderStatusHistories() { return CreateRelationInfoForNavigator("OrderStatusHistories"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser1() { return CreateRelationInfoForNavigator("User1"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this OrderEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static OrderRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'CouponUsage' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCouponUsages { get { return _staticMetaData.GetPrefetchPathElement("CouponUsages", CommonEntityBase.CreateEntityCollection<CouponUsageEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductReview' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductReviews { get { return _staticMetaData.GetPrefetchPathElement("ProductReviews", CommonEntityBase.CreateEntityCollection<ProductReviewEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'OrderItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrderItems { get { return _staticMetaData.GetPrefetchPathElement("OrderItems", CommonEntityBase.CreateEntityCollection<OrderItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'OrderPayment' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrderPayments { get { return _staticMetaData.GetPrefetchPathElement("OrderPayments", CommonEntityBase.CreateEntityCollection<OrderPaymentEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'OrderRefund' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrderRefunds { get { return _staticMetaData.GetPrefetchPathElement("OrderRefunds", CommonEntityBase.CreateEntityCollection<OrderRefundEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'OrderShipment' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrderShipments { get { return _staticMetaData.GetPrefetchPathElement("OrderShipments", CommonEntityBase.CreateEntityCollection<OrderShipmentEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'OrderStatusHistory' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrderStatusHistories { get { return _staticMetaData.GetPrefetchPathElement("OrderStatusHistories", CommonEntityBase.CreateEntityCollection<OrderStatusHistoryEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser1 { get { return _staticMetaData.GetPrefetchPathElement("User1", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The BillingAddress property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."billing_address".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String BillingAddress
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.BillingAddress, true); }
			set { SetValue((int)OrderFieldIndex.BillingAddress, value); }
		}

		/// <summary>The BillingCity property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."billing_city".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String BillingCity
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.BillingCity, true); }
			set { SetValue((int)OrderFieldIndex.BillingCity, value); }
		}

		/// <summary>The BillingCountry property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."billing_country".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String BillingCountry
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.BillingCountry, true); }
			set { SetValue((int)OrderFieldIndex.BillingCountry, value); }
		}

		/// <summary>The BillingEmail property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."billing_email".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String BillingEmail
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.BillingEmail, true); }
			set { SetValue((int)OrderFieldIndex.BillingEmail, value); }
		}

		/// <summary>The BillingFirstName property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."billing_first_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String BillingFirstName
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.BillingFirstName, true); }
			set { SetValue((int)OrderFieldIndex.BillingFirstName, value); }
		}

		/// <summary>The BillingLastName property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."billing_last_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String BillingLastName
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.BillingLastName, true); }
			set { SetValue((int)OrderFieldIndex.BillingLastName, value); }
		}

		/// <summary>The BillingPhone property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."billing_phone".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String BillingPhone
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.BillingPhone, true); }
			set { SetValue((int)OrderFieldIndex.BillingPhone, value); }
		}

		/// <summary>The BillingState property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."billing_state".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String BillingState
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.BillingState, true); }
			set { SetValue((int)OrderFieldIndex.BillingState, value); }
		}

		/// <summary>The BillingZipCode property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."billing_zip_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String BillingZipCode
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.BillingZipCode, true); }
			set { SetValue((int)OrderFieldIndex.BillingZipCode, value); }
		}

		/// <summary>The CreatedAt property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)OrderFieldIndex.CreatedAt, true); }
			set { SetValue((int)OrderFieldIndex.CreatedAt, value); }
		}

		/// <summary>The CreatedBy property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."created_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> CreatedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)OrderFieldIndex.CreatedBy, false); }
			set { SetValue((int)OrderFieldIndex.CreatedBy, value); }
		}

		/// <summary>The DeliveredAt property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."delivered_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> DeliveredAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)OrderFieldIndex.DeliveredAt, false); }
			set { SetValue((int)OrderFieldIndex.DeliveredAt, value); }
		}

		/// <summary>The DiscountAmount property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."discount_amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal DiscountAmount
		{
			get { return (System.Decimal)GetValue((int)OrderFieldIndex.DiscountAmount, true); }
			set { SetValue((int)OrderFieldIndex.DiscountAmount, value); }
		}

		/// <summary>The EstimatedDeliveryDate property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."estimated_delivery_date".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> EstimatedDeliveryDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)OrderFieldIndex.EstimatedDeliveryDate, false); }
			set { SetValue((int)OrderFieldIndex.EstimatedDeliveryDate, value); }
		}

		/// <summary>The Notes property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."notes".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Notes
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.Notes, true); }
			set { SetValue((int)OrderFieldIndex.Notes, value); }
		}

		/// <summary>The OrderDate property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."order_date".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime OrderDate
		{
			get { return (System.DateTime)GetValue((int)OrderFieldIndex.OrderDate, true); }
			set { SetValue((int)OrderFieldIndex.OrderDate, value); }
		}

		/// <summary>The OrderId property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."order_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid OrderId
		{
			get { return (System.Guid)GetValue((int)OrderFieldIndex.OrderId, true); }
			set { SetValue((int)OrderFieldIndex.OrderId, value); }
		}

		/// <summary>The OrderNumber property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."order_number".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String OrderNumber
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.OrderNumber, true); }
			set { SetValue((int)OrderFieldIndex.OrderNumber, value); }
		}

		/// <summary>The PaymentMethod property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."payment_method".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 PaymentMethod
		{
			get { return (System.Int16)GetValue((int)OrderFieldIndex.PaymentMethod, true); }
			set { SetValue((int)OrderFieldIndex.PaymentMethod, value); }
		}

		/// <summary>The PaymentStatus property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."payment_status".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 PaymentStatus
		{
			get { return (System.Int16)GetValue((int)OrderFieldIndex.PaymentStatus, true); }
			set { SetValue((int)OrderFieldIndex.PaymentStatus, value); }
		}

		/// <summary>The ShippingAddress property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."shipping_address".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ShippingAddress
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.ShippingAddress, true); }
			set { SetValue((int)OrderFieldIndex.ShippingAddress, value); }
		}

		/// <summary>The ShippingAmount property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."shipping_amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal ShippingAmount
		{
			get { return (System.Decimal)GetValue((int)OrderFieldIndex.ShippingAmount, true); }
			set { SetValue((int)OrderFieldIndex.ShippingAmount, value); }
		}

		/// <summary>The ShippingCity property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."shipping_city".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ShippingCity
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.ShippingCity, true); }
			set { SetValue((int)OrderFieldIndex.ShippingCity, value); }
		}

		/// <summary>The ShippingCountry property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."shipping_country".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ShippingCountry
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.ShippingCountry, true); }
			set { SetValue((int)OrderFieldIndex.ShippingCountry, value); }
		}

		/// <summary>The ShippingEmail property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."shipping_email".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ShippingEmail
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.ShippingEmail, true); }
			set { SetValue((int)OrderFieldIndex.ShippingEmail, value); }
		}

		/// <summary>The ShippingFirstName property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."shipping_first_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ShippingFirstName
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.ShippingFirstName, true); }
			set { SetValue((int)OrderFieldIndex.ShippingFirstName, value); }
		}

		/// <summary>The ShippingLastName property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."shipping_last_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ShippingLastName
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.ShippingLastName, true); }
			set { SetValue((int)OrderFieldIndex.ShippingLastName, value); }
		}

		/// <summary>The ShippingPhone property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."shipping_phone".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ShippingPhone
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.ShippingPhone, true); }
			set { SetValue((int)OrderFieldIndex.ShippingPhone, value); }
		}

		/// <summary>The ShippingState property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."shipping_state".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ShippingState
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.ShippingState, true); }
			set { SetValue((int)OrderFieldIndex.ShippingState, value); }
		}

		/// <summary>The ShippingZipCode property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."shipping_zip_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ShippingZipCode
		{
			get { return (System.String)GetValue((int)OrderFieldIndex.ShippingZipCode, true); }
			set { SetValue((int)OrderFieldIndex.ShippingZipCode, value); }
		}

		/// <summary>The Status property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."status".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 Status
		{
			get { return (System.Int16)GetValue((int)OrderFieldIndex.Status, true); }
			set { SetValue((int)OrderFieldIndex.Status, value); }
		}

		/// <summary>The SubTotal property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."sub_total".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal SubTotal
		{
			get { return (System.Decimal)GetValue((int)OrderFieldIndex.SubTotal, true); }
			set { SetValue((int)OrderFieldIndex.SubTotal, value); }
		}

		/// <summary>The TaxAmount property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."tax_amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal TaxAmount
		{
			get { return (System.Decimal)GetValue((int)OrderFieldIndex.TaxAmount, true); }
			set { SetValue((int)OrderFieldIndex.TaxAmount, value); }
		}

		/// <summary>The TotalAmount property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."total_amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal TotalAmount
		{
			get { return (System.Decimal)GetValue((int)OrderFieldIndex.TotalAmount, true); }
			set { SetValue((int)OrderFieldIndex.TotalAmount, value); }
		}

		/// <summary>The UpdatedAt property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)OrderFieldIndex.UpdatedAt, false); }
			set { SetValue((int)OrderFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UserId property of the Entity Order<br/><br/></summary>
		/// <remarks>Mapped on  table field: "orders"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)OrderFieldIndex.UserId, true); }
			set { SetValue((int)OrderFieldIndex.UserId, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'CouponUsageEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(CouponUsageEntity))]
		public virtual EntityCollection<CouponUsageEntity> CouponUsages { get { return GetOrCreateEntityCollection<CouponUsageEntity, CouponUsageEntityFactory>("Order", true, false, ref _couponUsages); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'ProductReviewEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProductReviewEntity))]
		public virtual EntityCollection<ProductReviewEntity> ProductReviews { get { return GetOrCreateEntityCollection<ProductReviewEntity, ProductReviewEntityFactory>("Order", true, false, ref _productReviews); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'OrderItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(OrderItemEntity))]
		public virtual EntityCollection<OrderItemEntity> OrderItems { get { return GetOrCreateEntityCollection<OrderItemEntity, OrderItemEntityFactory>("Order", true, false, ref _orderItems); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'OrderPaymentEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(OrderPaymentEntity))]
		public virtual EntityCollection<OrderPaymentEntity> OrderPayments { get { return GetOrCreateEntityCollection<OrderPaymentEntity, OrderPaymentEntityFactory>("Order", true, false, ref _orderPayments); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'OrderRefundEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(OrderRefundEntity))]
		public virtual EntityCollection<OrderRefundEntity> OrderRefunds { get { return GetOrCreateEntityCollection<OrderRefundEntity, OrderRefundEntityFactory>("Order", true, false, ref _orderRefunds); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'OrderShipmentEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(OrderShipmentEntity))]
		public virtual EntityCollection<OrderShipmentEntity> OrderShipments { get { return GetOrCreateEntityCollection<OrderShipmentEntity, OrderShipmentEntityFactory>("Order", true, false, ref _orderShipments); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'OrderStatusHistoryEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(OrderStatusHistoryEntity))]
		public virtual EntityCollection<OrderStatusHistoryEntity> OrderStatusHistories { get { return GetOrCreateEntityCollection<OrderStatusHistoryEntity, OrderStatusHistoryEntityFactory>("Order", true, false, ref _orderStatusHistories); } }

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User1
		{
			get { return _user1; }
			set { SetSingleRelatedEntityNavigator(value, "User1"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace GroceryEcommerce
{
	public enum OrderFieldIndex
	{
		///<summary>BillingAddress. </summary>
		BillingAddress,
		///<summary>BillingCity. </summary>
		BillingCity,
		///<summary>BillingCountry. </summary>
		BillingCountry,
		///<summary>BillingEmail. </summary>
		BillingEmail,
		///<summary>BillingFirstName. </summary>
		BillingFirstName,
		///<summary>BillingLastName. </summary>
		BillingLastName,
		///<summary>BillingPhone. </summary>
		BillingPhone,
		///<summary>BillingState. </summary>
		BillingState,
		///<summary>BillingZipCode. </summary>
		BillingZipCode,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>CreatedBy. </summary>
		CreatedBy,
		///<summary>DeliveredAt. </summary>
		DeliveredAt,
		///<summary>DiscountAmount. </summary>
		DiscountAmount,
		///<summary>EstimatedDeliveryDate. </summary>
		EstimatedDeliveryDate,
		///<summary>Notes. </summary>
		Notes,
		///<summary>OrderDate. </summary>
		OrderDate,
		///<summary>OrderId. </summary>
		OrderId,
		///<summary>OrderNumber. </summary>
		OrderNumber,
		///<summary>PaymentMethod. </summary>
		PaymentMethod,
		///<summary>PaymentStatus. </summary>
		PaymentStatus,
		///<summary>ShippingAddress. </summary>
		ShippingAddress,
		///<summary>ShippingAmount. </summary>
		ShippingAmount,
		///<summary>ShippingCity. </summary>
		ShippingCity,
		///<summary>ShippingCountry. </summary>
		ShippingCountry,
		///<summary>ShippingEmail. </summary>
		ShippingEmail,
		///<summary>ShippingFirstName. </summary>
		ShippingFirstName,
		///<summary>ShippingLastName. </summary>
		ShippingLastName,
		///<summary>ShippingPhone. </summary>
		ShippingPhone,
		///<summary>ShippingState. </summary>
		ShippingState,
		///<summary>ShippingZipCode. </summary>
		ShippingZipCode,
		///<summary>Status. </summary>
		Status,
		///<summary>SubTotal. </summary>
		SubTotal,
		///<summary>TaxAmount. </summary>
		TaxAmount,
		///<summary>TotalAmount. </summary>
		TotalAmount,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Order. </summary>
	public partial class OrderRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between OrderEntity and CouponUsageEntity over the 1:n relation they have, using the relation between the fields: Order.OrderId - CouponUsage.OrderId</summary>
		public virtual IEntityRelation CouponUsageEntityUsingOrderId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "CouponUsages", true, new[] { OrderFields.OrderId, CouponUsageFields.OrderId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderEntity and ProductReviewEntity over the 1:n relation they have, using the relation between the fields: Order.OrderId - ProductReview.OrderId</summary>
		public virtual IEntityRelation ProductReviewEntityUsingOrderId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ProductReviews", true, new[] { OrderFields.OrderId, ProductReviewFields.OrderId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderEntity and OrderItemEntity over the 1:n relation they have, using the relation between the fields: Order.OrderId - OrderItem.OrderId</summary>
		public virtual IEntityRelation OrderItemEntityUsingOrderId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "OrderItems", true, new[] { OrderFields.OrderId, OrderItemFields.OrderId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderEntity and OrderPaymentEntity over the 1:n relation they have, using the relation between the fields: Order.OrderId - OrderPayment.OrderId</summary>
		public virtual IEntityRelation OrderPaymentEntityUsingOrderId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "OrderPayments", true, new[] { OrderFields.OrderId, OrderPaymentFields.OrderId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderEntity and OrderRefundEntity over the 1:n relation they have, using the relation between the fields: Order.OrderId - OrderRefund.OrderId</summary>
		public virtual IEntityRelation OrderRefundEntityUsingOrderId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "OrderRefunds", true, new[] { OrderFields.OrderId, OrderRefundFields.OrderId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderEntity and OrderShipmentEntity over the 1:n relation they have, using the relation between the fields: Order.OrderId - OrderShipment.OrderId</summary>
		public virtual IEntityRelation OrderShipmentEntityUsingOrderId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "OrderShipments", true, new[] { OrderFields.OrderId, OrderShipmentFields.OrderId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderEntity and OrderStatusHistoryEntity over the 1:n relation they have, using the relation between the fields: Order.OrderId - OrderStatusHistory.OrderId</summary>
		public virtual IEntityRelation OrderStatusHistoryEntityUsingOrderId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "OrderStatusHistories", true, new[] { OrderFields.OrderId, OrderStatusHistoryFields.OrderId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Order.CreatedBy - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingCreatedBy
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.UserId, OrderFields.CreatedBy }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Order.UserId - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User1", false, new[] { UserFields.UserId, OrderFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticOrderRelations
	{
		internal static readonly IEntityRelation CouponUsageEntityUsingOrderIdStatic = new OrderRelations().CouponUsageEntityUsingOrderId;
		internal static readonly IEntityRelation ProductReviewEntityUsingOrderIdStatic = new OrderRelations().ProductReviewEntityUsingOrderId;
		internal static readonly IEntityRelation OrderItemEntityUsingOrderIdStatic = new OrderRelations().OrderItemEntityUsingOrderId;
		internal static readonly IEntityRelation OrderPaymentEntityUsingOrderIdStatic = new OrderRelations().OrderPaymentEntityUsingOrderId;
		internal static readonly IEntityRelation OrderRefundEntityUsingOrderIdStatic = new OrderRelations().OrderRefundEntityUsingOrderId;
		internal static readonly IEntityRelation OrderShipmentEntityUsingOrderIdStatic = new OrderRelations().OrderShipmentEntityUsingOrderId;
		internal static readonly IEntityRelation OrderStatusHistoryEntityUsingOrderIdStatic = new OrderRelations().OrderStatusHistoryEntityUsingOrderId;
		internal static readonly IEntityRelation UserEntityUsingCreatedByStatic = new OrderRelations().UserEntityUsingCreatedBy;
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new OrderRelations().UserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticOrderRelations() { }
	}
}
