//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'OrderItem'.<br/><br/></summary>
	[Serializable]
	public partial class OrderItemEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<ShipmentItemEntity> _shipmentItems;
		private ProductEntity _product;
		private ProductVariantEntity _productVariant;
		private OrderEntity _order;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static OrderItemEntityStaticMetaData _staticMetaData = new OrderItemEntityStaticMetaData();
		private static OrderItemRelations _relationsFactory = new OrderItemRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Product</summary>
			public static readonly string Product = "Product";
			/// <summary>Member name ProductVariant</summary>
			public static readonly string ProductVariant = "ProductVariant";
			/// <summary>Member name Order</summary>
			public static readonly string Order = "Order";
			/// <summary>Member name ShipmentItems</summary>
			public static readonly string ShipmentItems = "ShipmentItems";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class OrderItemEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public OrderItemEntityStaticMetaData()
			{
				SetEntityCoreInfo("OrderItemEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.OrderItemEntity, typeof(OrderItemEntity), typeof(OrderItemEntityFactory), false);
				AddNavigatorMetaData<OrderItemEntity, EntityCollection<ShipmentItemEntity>>("ShipmentItems", a => a._shipmentItems, (a, b) => a._shipmentItems = b, a => a.ShipmentItems, () => new OrderItemRelations().ShipmentItemEntityUsingOrderItemId, typeof(ShipmentItemEntity), (int)GroceryEcommerce.EntityType.ShipmentItemEntity);
				AddNavigatorMetaData<OrderItemEntity, ProductEntity>("Product", "OrderItems", (a, b) => a._product = b, a => a._product, (a, b) => a.Product = b, GroceryEcommerce.RelationClasses.StaticOrderItemRelations.ProductEntityUsingProductIdStatic, ()=>new OrderItemRelations().ProductEntityUsingProductId, null, new int[] { (int)OrderItemFieldIndex.ProductId }, null, true, (int)GroceryEcommerce.EntityType.ProductEntity);
				AddNavigatorMetaData<OrderItemEntity, ProductVariantEntity>("ProductVariant", "OrderItems", (a, b) => a._productVariant = b, a => a._productVariant, (a, b) => a.ProductVariant = b, GroceryEcommerce.RelationClasses.StaticOrderItemRelations.ProductVariantEntityUsingProductVariantIdStatic, ()=>new OrderItemRelations().ProductVariantEntityUsingProductVariantId, null, new int[] { (int)OrderItemFieldIndex.ProductVariantId }, null, true, (int)GroceryEcommerce.EntityType.ProductVariantEntity);
				AddNavigatorMetaData<OrderItemEntity, OrderEntity>("Order", "OrderItems", (a, b) => a._order = b, a => a._order, (a, b) => a.Order = b, GroceryEcommerce.RelationClasses.StaticOrderItemRelations.OrderEntityUsingOrderIdStatic, ()=>new OrderItemRelations().OrderEntityUsingOrderId, null, new int[] { (int)OrderItemFieldIndex.OrderId }, null, true, (int)GroceryEcommerce.EntityType.OrderEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static OrderItemEntity()
		{
		}

		/// <summary> CTor</summary>
		public OrderItemEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public OrderItemEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this OrderItemEntity</param>
		public OrderItemEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="orderItemId">PK value for OrderItem which data should be fetched into this OrderItem object</param>
		public OrderItemEntity(System.Guid orderItemId) : this(orderItemId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="orderItemId">PK value for OrderItem which data should be fetched into this OrderItem object</param>
		/// <param name="validator">The custom validator object for this OrderItemEntity</param>
		public OrderItemEntity(System.Guid orderItemId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.OrderItemId = orderItemId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected OrderItemEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ShipmentItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoShipmentItems() { return CreateRelationInfoForNavigator("ShipmentItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Product' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProduct() { return CreateRelationInfoForNavigator("Product"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ProductVariant' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductVariant() { return CreateRelationInfoForNavigator("ProductVariant"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Order' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrder() { return CreateRelationInfoForNavigator("Order"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this OrderItemEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static OrderItemRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ShipmentItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathShipmentItems { get { return _staticMetaData.GetPrefetchPathElement("ShipmentItems", CommonEntityBase.CreateEntityCollection<ShipmentItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Product' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProduct { get { return _staticMetaData.GetPrefetchPathElement("Product", CommonEntityBase.CreateEntityCollection<ProductEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductVariant' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductVariant { get { return _staticMetaData.GetPrefetchPathElement("ProductVariant", CommonEntityBase.CreateEntityCollection<ProductVariantEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Order' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrder { get { return _staticMetaData.GetPrefetchPathElement("Order", CommonEntityBase.CreateEntityCollection<OrderEntity>()); } }

		/// <summary>The OrderId property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."order_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid OrderId
		{
			get { return (System.Guid)GetValue((int)OrderItemFieldIndex.OrderId, true); }
			set { SetValue((int)OrderItemFieldIndex.OrderId, value); }
		}

		/// <summary>The OrderItemId property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."order_item_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid OrderItemId
		{
			get { return (System.Guid)GetValue((int)OrderItemFieldIndex.OrderItemId, true); }
			set { SetValue((int)OrderItemFieldIndex.OrderItemId, value); }
		}

		/// <summary>The ProductId property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."product_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid ProductId
		{
			get { return (System.Guid)GetValue((int)OrderItemFieldIndex.ProductId, true); }
			set { SetValue((int)OrderItemFieldIndex.ProductId, value); }
		}

		/// <summary>The ProductName property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."product_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ProductName
		{
			get { return (System.String)GetValue((int)OrderItemFieldIndex.ProductName, true); }
			set { SetValue((int)OrderItemFieldIndex.ProductName, value); }
		}

		/// <summary>The ProductSku property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."product_sku".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ProductSku
		{
			get { return (System.String)GetValue((int)OrderItemFieldIndex.ProductSku, true); }
			set { SetValue((int)OrderItemFieldIndex.ProductSku, value); }
		}

		/// <summary>The ProductVariantId property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."product_variant_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> ProductVariantId
		{
			get { return (Nullable<System.Guid>)GetValue((int)OrderItemFieldIndex.ProductVariantId, false); }
			set { SetValue((int)OrderItemFieldIndex.ProductVariantId, value); }
		}

		/// <summary>The Quantity property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."quantity".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 Quantity
		{
			get { return (System.Int32)GetValue((int)OrderItemFieldIndex.Quantity, true); }
			set { SetValue((int)OrderItemFieldIndex.Quantity, value); }
		}

		/// <summary>The TotalPrice property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."total_price".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal TotalPrice
		{
			get { return (System.Decimal)GetValue((int)OrderItemFieldIndex.TotalPrice, true); }
			set { SetValue((int)OrderItemFieldIndex.TotalPrice, value); }
		}

		/// <summary>The UnitPrice property of the Entity OrderItem<br/><br/></summary>
		/// <remarks>Mapped on  table field: "order_items"."unit_price".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal UnitPrice
		{
			get { return (System.Decimal)GetValue((int)OrderItemFieldIndex.UnitPrice, true); }
			set { SetValue((int)OrderItemFieldIndex.UnitPrice, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'ShipmentItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ShipmentItemEntity))]
		public virtual EntityCollection<ShipmentItemEntity> ShipmentItems { get { return GetOrCreateEntityCollection<ShipmentItemEntity, ShipmentItemEntityFactory>("OrderItem", true, false, ref _shipmentItems); } }

		/// <summary>Gets / sets related entity of type 'ProductEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductEntity Product
		{
			get { return _product; }
			set { SetSingleRelatedEntityNavigator(value, "Product"); }
		}

		/// <summary>Gets / sets related entity of type 'ProductVariantEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductVariantEntity ProductVariant
		{
			get { return _productVariant; }
			set { SetSingleRelatedEntityNavigator(value, "ProductVariant"); }
		}

		/// <summary>Gets / sets related entity of type 'OrderEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual OrderEntity Order
		{
			get { return _order; }
			set { SetSingleRelatedEntityNavigator(value, "Order"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace GroceryEcommerce
{
	public enum OrderItemFieldIndex
	{
		///<summary>OrderId. </summary>
		OrderId,
		///<summary>OrderItemId. </summary>
		OrderItemId,
		///<summary>ProductId. </summary>
		ProductId,
		///<summary>ProductName. </summary>
		ProductName,
		///<summary>ProductSku. </summary>
		ProductSku,
		///<summary>ProductVariantId. </summary>
		ProductVariantId,
		///<summary>Quantity. </summary>
		Quantity,
		///<summary>TotalPrice. </summary>
		TotalPrice,
		///<summary>UnitPrice. </summary>
		UnitPrice,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: OrderItem. </summary>
	public partial class OrderItemRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between OrderItemEntity and ShipmentItemEntity over the 1:n relation they have, using the relation between the fields: OrderItem.OrderItemId - ShipmentItem.OrderItemId</summary>
		public virtual IEntityRelation ShipmentItemEntityUsingOrderItemId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ShipmentItems", true, new[] { OrderItemFields.OrderItemId, ShipmentItemFields.OrderItemId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderItemEntity and ProductEntity over the m:1 relation they have, using the relation between the fields: OrderItem.ProductId - Product.ProductId</summary>
		public virtual IEntityRelation ProductEntityUsingProductId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Product", false, new[] { ProductFields.ProductId, OrderItemFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderItemEntity and ProductVariantEntity over the m:1 relation they have, using the relation between the fields: OrderItem.ProductVariantId - ProductVariant.VariantId</summary>
		public virtual IEntityRelation ProductVariantEntityUsingProductVariantId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ProductVariant", false, new[] { ProductVariantFields.VariantId, OrderItemFields.ProductVariantId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderItemEntity and OrderEntity over the m:1 relation they have, using the relation between the fields: OrderItem.OrderId - Order.OrderId</summary>
		public virtual IEntityRelation OrderEntityUsingOrderId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Order", false, new[] { OrderFields.OrderId, OrderItemFields.OrderId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticOrderItemRelations
	{
		internal static readonly IEntityRelation ShipmentItemEntityUsingOrderItemIdStatic = new OrderItemRelations().ShipmentItemEntityUsingOrderItemId;
		internal static readonly IEntityRelation ProductEntityUsingProductIdStatic = new OrderItemRelations().ProductEntityUsingProductId;
		internal static readonly IEntityRelation ProductVariantEntityUsingProductVariantIdStatic = new OrderItemRelations().ProductVariantEntityUsingProductVariantId;
		internal static readonly IEntityRelation OrderEntityUsingOrderIdStatic = new OrderItemRelations().OrderEntityUsingOrderId;

		/// <summary>CTor</summary>
		static StaticOrderItemRelations() { }
	}
}
