//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'ProductVariant'.<br/><br/></summary>
	[Serializable]
	public partial class ProductVariantEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<ShoppingCartItemEntity> _shoppingCartItems;
		private EntityCollection<WishlistItemEntity> _wishlistItems;
		private EntityCollection<PurchaseOrderItemEntity> _purchaseOrderItems;
		private EntityCollection<StockMovementEntity> _stockMovements;
		private EntityCollection<OrderItemEntity> _orderItems;
		private ProductEntity _product;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ProductVariantEntityStaticMetaData _staticMetaData = new ProductVariantEntityStaticMetaData();
		private static ProductVariantRelations _relationsFactory = new ProductVariantRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Product</summary>
			public static readonly string Product = "Product";
			/// <summary>Member name ShoppingCartItems</summary>
			public static readonly string ShoppingCartItems = "ShoppingCartItems";
			/// <summary>Member name WishlistItems</summary>
			public static readonly string WishlistItems = "WishlistItems";
			/// <summary>Member name PurchaseOrderItems</summary>
			public static readonly string PurchaseOrderItems = "PurchaseOrderItems";
			/// <summary>Member name StockMovements</summary>
			public static readonly string StockMovements = "StockMovements";
			/// <summary>Member name OrderItems</summary>
			public static readonly string OrderItems = "OrderItems";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ProductVariantEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ProductVariantEntityStaticMetaData()
			{
				SetEntityCoreInfo("ProductVariantEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.ProductVariantEntity, typeof(ProductVariantEntity), typeof(ProductVariantEntityFactory), false);
				AddNavigatorMetaData<ProductVariantEntity, EntityCollection<ShoppingCartItemEntity>>("ShoppingCartItems", a => a._shoppingCartItems, (a, b) => a._shoppingCartItems = b, a => a.ShoppingCartItems, () => new ProductVariantRelations().ShoppingCartItemEntityUsingProductVariantId, typeof(ShoppingCartItemEntity), (int)GroceryEcommerce.EntityType.ShoppingCartItemEntity);
				AddNavigatorMetaData<ProductVariantEntity, EntityCollection<WishlistItemEntity>>("WishlistItems", a => a._wishlistItems, (a, b) => a._wishlistItems = b, a => a.WishlistItems, () => new ProductVariantRelations().WishlistItemEntityUsingProductVariantId, typeof(WishlistItemEntity), (int)GroceryEcommerce.EntityType.WishlistItemEntity);
				AddNavigatorMetaData<ProductVariantEntity, EntityCollection<PurchaseOrderItemEntity>>("PurchaseOrderItems", a => a._purchaseOrderItems, (a, b) => a._purchaseOrderItems = b, a => a.PurchaseOrderItems, () => new ProductVariantRelations().PurchaseOrderItemEntityUsingVariantId, typeof(PurchaseOrderItemEntity), (int)GroceryEcommerce.EntityType.PurchaseOrderItemEntity);
				AddNavigatorMetaData<ProductVariantEntity, EntityCollection<StockMovementEntity>>("StockMovements", a => a._stockMovements, (a, b) => a._stockMovements = b, a => a.StockMovements, () => new ProductVariantRelations().StockMovementEntityUsingProductVariantId, typeof(StockMovementEntity), (int)GroceryEcommerce.EntityType.StockMovementEntity);
				AddNavigatorMetaData<ProductVariantEntity, EntityCollection<OrderItemEntity>>("OrderItems", a => a._orderItems, (a, b) => a._orderItems = b, a => a.OrderItems, () => new ProductVariantRelations().OrderItemEntityUsingProductVariantId, typeof(OrderItemEntity), (int)GroceryEcommerce.EntityType.OrderItemEntity);
				AddNavigatorMetaData<ProductVariantEntity, ProductEntity>("Product", "ProductVariants", (a, b) => a._product = b, a => a._product, (a, b) => a.Product = b, GroceryEcommerce.RelationClasses.StaticProductVariantRelations.ProductEntityUsingProductIdStatic, ()=>new ProductVariantRelations().ProductEntityUsingProductId, null, new int[] { (int)ProductVariantFieldIndex.ProductId }, null, true, (int)GroceryEcommerce.EntityType.ProductEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ProductVariantEntity()
		{
		}

		/// <summary> CTor</summary>
		public ProductVariantEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ProductVariantEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ProductVariantEntity</param>
		public ProductVariantEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="variantId">PK value for ProductVariant which data should be fetched into this ProductVariant object</param>
		public ProductVariantEntity(System.Guid variantId) : this(variantId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="variantId">PK value for ProductVariant which data should be fetched into this ProductVariant object</param>
		/// <param name="validator">The custom validator object for this ProductVariantEntity</param>
		public ProductVariantEntity(System.Guid variantId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.VariantId = variantId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ProductVariantEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: Sku .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCSku()
		{
			var filter = new PredicateExpression();
			filter.Add(GroceryEcommerce.HelperClasses.ProductVariantFields.Sku == this.Fields.GetCurrentValue((int)ProductVariantFieldIndex.Sku));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ShoppingCartItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoShoppingCartItems() { return CreateRelationInfoForNavigator("ShoppingCartItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'WishlistItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoWishlistItems() { return CreateRelationInfoForNavigator("WishlistItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'PurchaseOrderItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPurchaseOrderItems() { return CreateRelationInfoForNavigator("PurchaseOrderItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'StockMovement' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoStockMovements() { return CreateRelationInfoForNavigator("StockMovements"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'OrderItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrderItems() { return CreateRelationInfoForNavigator("OrderItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Product' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProduct() { return CreateRelationInfoForNavigator("Product"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ProductVariantEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ProductVariantRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ShoppingCartItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathShoppingCartItems { get { return _staticMetaData.GetPrefetchPathElement("ShoppingCartItems", CommonEntityBase.CreateEntityCollection<ShoppingCartItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'WishlistItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathWishlistItems { get { return _staticMetaData.GetPrefetchPathElement("WishlistItems", CommonEntityBase.CreateEntityCollection<WishlistItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'PurchaseOrderItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPurchaseOrderItems { get { return _staticMetaData.GetPrefetchPathElement("PurchaseOrderItems", CommonEntityBase.CreateEntityCollection<PurchaseOrderItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'StockMovement' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathStockMovements { get { return _staticMetaData.GetPrefetchPathElement("StockMovements", CommonEntityBase.CreateEntityCollection<StockMovementEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'OrderItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrderItems { get { return _staticMetaData.GetPrefetchPathElement("OrderItems", CommonEntityBase.CreateEntityCollection<OrderItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Product' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProduct { get { return _staticMetaData.GetPrefetchPathElement("Product", CommonEntityBase.CreateEntityCollection<ProductEntity>()); } }

		/// <summary>The CreatedAt property of the Entity ProductVariant<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_variants"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)ProductVariantFieldIndex.CreatedAt, true); }
			set { SetValue((int)ProductVariantFieldIndex.CreatedAt, value); }
		}

		/// <summary>The DiscountPrice property of the Entity ProductVariant<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_variants"."discount_price".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> DiscountPrice
		{
			get { return (Nullable<System.Decimal>)GetValue((int)ProductVariantFieldIndex.DiscountPrice, false); }
			set { SetValue((int)ProductVariantFieldIndex.DiscountPrice, value); }
		}

		/// <summary>The ImageUrl property of the Entity ProductVariant<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_variants"."image_url".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ImageUrl
		{
			get { return (System.String)GetValue((int)ProductVariantFieldIndex.ImageUrl, true); }
			set { SetValue((int)ProductVariantFieldIndex.ImageUrl, value); }
		}

		/// <summary>The Name property of the Entity ProductVariant<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_variants"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)ProductVariantFieldIndex.Name, true); }
			set { SetValue((int)ProductVariantFieldIndex.Name, value); }
		}

		/// <summary>The Price property of the Entity ProductVariant<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_variants"."price".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Price
		{
			get { return (System.Decimal)GetValue((int)ProductVariantFieldIndex.Price, true); }
			set { SetValue((int)ProductVariantFieldIndex.Price, value); }
		}

		/// <summary>The ProductId property of the Entity ProductVariant<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_variants"."product_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid ProductId
		{
			get { return (System.Guid)GetValue((int)ProductVariantFieldIndex.ProductId, true); }
			set { SetValue((int)ProductVariantFieldIndex.ProductId, value); }
		}

		/// <summary>The Sku property of the Entity ProductVariant<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_variants"."sku".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Sku
		{
			get { return (System.String)GetValue((int)ProductVariantFieldIndex.Sku, true); }
			set { SetValue((int)ProductVariantFieldIndex.Sku, value); }
		}

		/// <summary>The Status property of the Entity ProductVariant<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_variants"."status".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 Status
		{
			get { return (System.Int16)GetValue((int)ProductVariantFieldIndex.Status, true); }
			set { SetValue((int)ProductVariantFieldIndex.Status, value); }
		}

		/// <summary>The StockQuantity property of the Entity ProductVariant<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_variants"."stock_quantity".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 StockQuantity
		{
			get { return (System.Int32)GetValue((int)ProductVariantFieldIndex.StockQuantity, true); }
			set { SetValue((int)ProductVariantFieldIndex.StockQuantity, value); }
		}

		/// <summary>The UpdatedAt property of the Entity ProductVariant<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_variants"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ProductVariantFieldIndex.UpdatedAt, false); }
			set { SetValue((int)ProductVariantFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The VariantId property of the Entity ProductVariant<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_variants"."variant_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid VariantId
		{
			get { return (System.Guid)GetValue((int)ProductVariantFieldIndex.VariantId, true); }
			set { SetValue((int)ProductVariantFieldIndex.VariantId, value); }
		}

		/// <summary>The Weight property of the Entity ProductVariant<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_variants"."weight".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 3, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> Weight
		{
			get { return (Nullable<System.Decimal>)GetValue((int)ProductVariantFieldIndex.Weight, false); }
			set { SetValue((int)ProductVariantFieldIndex.Weight, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'ShoppingCartItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ShoppingCartItemEntity))]
		public virtual EntityCollection<ShoppingCartItemEntity> ShoppingCartItems { get { return GetOrCreateEntityCollection<ShoppingCartItemEntity, ShoppingCartItemEntityFactory>("ProductVariant", true, false, ref _shoppingCartItems); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'WishlistItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(WishlistItemEntity))]
		public virtual EntityCollection<WishlistItemEntity> WishlistItems { get { return GetOrCreateEntityCollection<WishlistItemEntity, WishlistItemEntityFactory>("ProductVariant", true, false, ref _wishlistItems); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'PurchaseOrderItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(PurchaseOrderItemEntity))]
		public virtual EntityCollection<PurchaseOrderItemEntity> PurchaseOrderItems { get { return GetOrCreateEntityCollection<PurchaseOrderItemEntity, PurchaseOrderItemEntityFactory>("ProductVariant", true, false, ref _purchaseOrderItems); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'StockMovementEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(StockMovementEntity))]
		public virtual EntityCollection<StockMovementEntity> StockMovements { get { return GetOrCreateEntityCollection<StockMovementEntity, StockMovementEntityFactory>("ProductVariant", true, false, ref _stockMovements); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'OrderItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(OrderItemEntity))]
		public virtual EntityCollection<OrderItemEntity> OrderItems { get { return GetOrCreateEntityCollection<OrderItemEntity, OrderItemEntityFactory>("ProductVariant", true, false, ref _orderItems); } }

		/// <summary>Gets / sets related entity of type 'ProductEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductEntity Product
		{
			get { return _product; }
			set { SetSingleRelatedEntityNavigator(value, "Product"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace GroceryEcommerce
{
	public enum ProductVariantFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>DiscountPrice. </summary>
		DiscountPrice,
		///<summary>ImageUrl. </summary>
		ImageUrl,
		///<summary>Name. </summary>
		Name,
		///<summary>Price. </summary>
		Price,
		///<summary>ProductId. </summary>
		ProductId,
		///<summary>Sku. </summary>
		Sku,
		///<summary>Status. </summary>
		Status,
		///<summary>StockQuantity. </summary>
		StockQuantity,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>VariantId. </summary>
		VariantId,
		///<summary>Weight. </summary>
		Weight,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ProductVariant. </summary>
	public partial class ProductVariantRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between ProductVariantEntity and ShoppingCartItemEntity over the 1:n relation they have, using the relation between the fields: ProductVariant.VariantId - ShoppingCartItem.ProductVariantId</summary>
		public virtual IEntityRelation ShoppingCartItemEntityUsingProductVariantId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ShoppingCartItems", true, new[] { ProductVariantFields.VariantId, ShoppingCartItemFields.ProductVariantId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductVariantEntity and WishlistItemEntity over the 1:n relation they have, using the relation between the fields: ProductVariant.VariantId - WishlistItem.ProductVariantId</summary>
		public virtual IEntityRelation WishlistItemEntityUsingProductVariantId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "WishlistItems", true, new[] { ProductVariantFields.VariantId, WishlistItemFields.ProductVariantId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductVariantEntity and PurchaseOrderItemEntity over the 1:n relation they have, using the relation between the fields: ProductVariant.VariantId - PurchaseOrderItem.VariantId</summary>
		public virtual IEntityRelation PurchaseOrderItemEntityUsingVariantId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "PurchaseOrderItems", true, new[] { ProductVariantFields.VariantId, PurchaseOrderItemFields.VariantId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductVariantEntity and StockMovementEntity over the 1:n relation they have, using the relation between the fields: ProductVariant.VariantId - StockMovement.ProductVariantId</summary>
		public virtual IEntityRelation StockMovementEntityUsingProductVariantId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "StockMovements", true, new[] { ProductVariantFields.VariantId, StockMovementFields.ProductVariantId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductVariantEntity and OrderItemEntity over the 1:n relation they have, using the relation between the fields: ProductVariant.VariantId - OrderItem.ProductVariantId</summary>
		public virtual IEntityRelation OrderItemEntityUsingProductVariantId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "OrderItems", true, new[] { ProductVariantFields.VariantId, OrderItemFields.ProductVariantId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductVariantEntity and ProductEntity over the m:1 relation they have, using the relation between the fields: ProductVariant.ProductId - Product.ProductId</summary>
		public virtual IEntityRelation ProductEntityUsingProductId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Product", false, new[] { ProductFields.ProductId, ProductVariantFields.ProductId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticProductVariantRelations
	{
		internal static readonly IEntityRelation ShoppingCartItemEntityUsingProductVariantIdStatic = new ProductVariantRelations().ShoppingCartItemEntityUsingProductVariantId;
		internal static readonly IEntityRelation WishlistItemEntityUsingProductVariantIdStatic = new ProductVariantRelations().WishlistItemEntityUsingProductVariantId;
		internal static readonly IEntityRelation PurchaseOrderItemEntityUsingVariantIdStatic = new ProductVariantRelations().PurchaseOrderItemEntityUsingVariantId;
		internal static readonly IEntityRelation StockMovementEntityUsingProductVariantIdStatic = new ProductVariantRelations().StockMovementEntityUsingProductVariantId;
		internal static readonly IEntityRelation OrderItemEntityUsingProductVariantIdStatic = new ProductVariantRelations().OrderItemEntityUsingProductVariantId;
		internal static readonly IEntityRelation ProductEntityUsingProductIdStatic = new ProductVariantRelations().ProductEntityUsingProductId;

		/// <summary>CTor</summary>
		static StaticProductVariantRelations() { }
	}
}
