//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'ProductTag'.<br/><br/></summary>
	[Serializable]
	public partial class ProductTagEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private EntityCollection<ProductTagAssignmentEntity> _productTagAssignments;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ProductTagEntityStaticMetaData _staticMetaData = new ProductTagEntityStaticMetaData();
		private static ProductTagRelations _relationsFactory = new ProductTagRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name ProductTagAssignments</summary>
			public static readonly string ProductTagAssignments = "ProductTagAssignments";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ProductTagEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ProductTagEntityStaticMetaData()
			{
				SetEntityCoreInfo("ProductTagEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.ProductTagEntity, typeof(ProductTagEntity), typeof(ProductTagEntityFactory), false);
				AddNavigatorMetaData<ProductTagEntity, EntityCollection<ProductTagAssignmentEntity>>("ProductTagAssignments", a => a._productTagAssignments, (a, b) => a._productTagAssignments = b, a => a.ProductTagAssignments, () => new ProductTagRelations().ProductTagAssignmentEntityUsingTagId, typeof(ProductTagAssignmentEntity), (int)GroceryEcommerce.EntityType.ProductTagAssignmentEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ProductTagEntity()
		{
		}

		/// <summary> CTor</summary>
		public ProductTagEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ProductTagEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ProductTagEntity</param>
		public ProductTagEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="tagId">PK value for ProductTag which data should be fetched into this ProductTag object</param>
		public ProductTagEntity(System.Guid tagId) : this(tagId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="tagId">PK value for ProductTag which data should be fetched into this ProductTag object</param>
		/// <param name="validator">The custom validator object for this ProductTagEntity</param>
		public ProductTagEntity(System.Guid tagId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.TagId = tagId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ProductTagEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: Name .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCName()
		{
			var filter = new PredicateExpression();
			filter.Add(GroceryEcommerce.HelperClasses.ProductTagFields.Name == this.Fields.GetCurrentValue((int)ProductTagFieldIndex.Name));
 			return filter;
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: Slug .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCSlug()
		{
			var filter = new PredicateExpression();
			filter.Add(GroceryEcommerce.HelperClasses.ProductTagFields.Slug == this.Fields.GetCurrentValue((int)ProductTagFieldIndex.Slug));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ProductTagAssignment' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductTagAssignments() { return CreateRelationInfoForNavigator("ProductTagAssignments"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ProductTagEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ProductTagRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductTagAssignment' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductTagAssignments { get { return _staticMetaData.GetPrefetchPathElement("ProductTagAssignments", CommonEntityBase.CreateEntityCollection<ProductTagAssignmentEntity>()); } }

		/// <summary>The Name property of the Entity ProductTag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_tags"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)ProductTagFieldIndex.Name, true); }
			set { SetValue((int)ProductTagFieldIndex.Name, value); }
		}

		/// <summary>The Slug property of the Entity ProductTag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_tags"."slug".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 150.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Slug
		{
			get { return (System.String)GetValue((int)ProductTagFieldIndex.Slug, true); }
			set { SetValue((int)ProductTagFieldIndex.Slug, value); }
		}

		/// <summary>The TagId property of the Entity ProductTag<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_tags"."tag_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid TagId
		{
			get { return (System.Guid)GetValue((int)ProductTagFieldIndex.TagId, true); }
			set { SetValue((int)ProductTagFieldIndex.TagId, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'ProductTagAssignmentEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProductTagAssignmentEntity))]
		public virtual EntityCollection<ProductTagAssignmentEntity> ProductTagAssignments { get { return GetOrCreateEntityCollection<ProductTagAssignmentEntity, ProductTagAssignmentEntityFactory>("ProductTag", true, false, ref _productTagAssignments); } }

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace GroceryEcommerce
{
	public enum ProductTagFieldIndex
	{
		///<summary>Name. </summary>
		Name,
		///<summary>Slug. </summary>
		Slug,
		///<summary>TagId. </summary>
		TagId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ProductTag. </summary>
	public partial class ProductTagRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between ProductTagEntity and ProductTagAssignmentEntity over the 1:n relation they have, using the relation between the fields: ProductTag.TagId - ProductTagAssignment.TagId</summary>
		public virtual IEntityRelation ProductTagAssignmentEntityUsingTagId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ProductTagAssignments", true, new[] { ProductTagFields.TagId, ProductTagAssignmentFields.TagId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticProductTagRelations
	{
		internal static readonly IEntityRelation ProductTagAssignmentEntityUsingTagIdStatic = new ProductTagRelations().ProductTagAssignmentEntityUsingTagId;

		/// <summary>CTor</summary>
		static StaticProductTagRelations() { }
	}
}
