//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'ProductAttribute'.<br/><br/></summary>
	[Serializable]
	public partial class ProductAttributeEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<ProductAttributeValueEntity> _productAttributeValues;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ProductAttributeEntityStaticMetaData _staticMetaData = new ProductAttributeEntityStaticMetaData();
		private static ProductAttributeRelations _relationsFactory = new ProductAttributeRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name ProductAttributeValues</summary>
			public static readonly string ProductAttributeValues = "ProductAttributeValues";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ProductAttributeEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ProductAttributeEntityStaticMetaData()
			{
				SetEntityCoreInfo("ProductAttributeEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.ProductAttributeEntity, typeof(ProductAttributeEntity), typeof(ProductAttributeEntityFactory), false);
				AddNavigatorMetaData<ProductAttributeEntity, EntityCollection<ProductAttributeValueEntity>>("ProductAttributeValues", a => a._productAttributeValues, (a, b) => a._productAttributeValues = b, a => a.ProductAttributeValues, () => new ProductAttributeRelations().ProductAttributeValueEntityUsingAttributeId, typeof(ProductAttributeValueEntity), (int)GroceryEcommerce.EntityType.ProductAttributeValueEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ProductAttributeEntity()
		{
		}

		/// <summary> CTor</summary>
		public ProductAttributeEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ProductAttributeEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ProductAttributeEntity</param>
		public ProductAttributeEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="attributeId">PK value for ProductAttribute which data should be fetched into this ProductAttribute object</param>
		public ProductAttributeEntity(System.Guid attributeId) : this(attributeId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="attributeId">PK value for ProductAttribute which data should be fetched into this ProductAttribute object</param>
		/// <param name="validator">The custom validator object for this ProductAttributeEntity</param>
		public ProductAttributeEntity(System.Guid attributeId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.AttributeId = attributeId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ProductAttributeEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ProductAttributeValue' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductAttributeValues() { return CreateRelationInfoForNavigator("ProductAttributeValues"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ProductAttributeEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ProductAttributeRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductAttributeValue' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductAttributeValues { get { return _staticMetaData.GetPrefetchPathElement("ProductAttributeValues", CommonEntityBase.CreateEntityCollection<ProductAttributeValueEntity>()); } }

		/// <summary>The AttributeId property of the Entity ProductAttribute<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_attributes"."attribute_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid AttributeId
		{
			get { return (System.Guid)GetValue((int)ProductAttributeFieldIndex.AttributeId, true); }
			set { SetValue((int)ProductAttributeFieldIndex.AttributeId, value); }
		}

		/// <summary>The AttributeType property of the Entity ProductAttribute<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_attributes"."attribute_type".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 AttributeType
		{
			get { return (System.Int16)GetValue((int)ProductAttributeFieldIndex.AttributeType, true); }
			set { SetValue((int)ProductAttributeFieldIndex.AttributeType, value); }
		}

		/// <summary>The CreatedAt property of the Entity ProductAttribute<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_attributes"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)ProductAttributeFieldIndex.CreatedAt, true); }
			set { SetValue((int)ProductAttributeFieldIndex.CreatedAt, value); }
		}

		/// <summary>The DisplayName property of the Entity ProductAttribute<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_attributes"."display_name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String DisplayName
		{
			get { return (System.String)GetValue((int)ProductAttributeFieldIndex.DisplayName, true); }
			set { SetValue((int)ProductAttributeFieldIndex.DisplayName, value); }
		}

		/// <summary>The DisplayOrder property of the Entity ProductAttribute<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_attributes"."display_order".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 DisplayOrder
		{
			get { return (System.Int32)GetValue((int)ProductAttributeFieldIndex.DisplayOrder, true); }
			set { SetValue((int)ProductAttributeFieldIndex.DisplayOrder, value); }
		}

		/// <summary>The IsRequired property of the Entity ProductAttribute<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_attributes"."is_required".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsRequired
		{
			get { return (System.Boolean)GetValue((int)ProductAttributeFieldIndex.IsRequired, true); }
			set { SetValue((int)ProductAttributeFieldIndex.IsRequired, value); }
		}

		/// <summary>The Name property of the Entity ProductAttribute<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_attributes"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)ProductAttributeFieldIndex.Name, true); }
			set { SetValue((int)ProductAttributeFieldIndex.Name, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'ProductAttributeValueEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProductAttributeValueEntity))]
		public virtual EntityCollection<ProductAttributeValueEntity> ProductAttributeValues { get { return GetOrCreateEntityCollection<ProductAttributeValueEntity, ProductAttributeValueEntityFactory>("ProductAttribute", true, false, ref _productAttributeValues); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace GroceryEcommerce
{
	public enum ProductAttributeFieldIndex
	{
		///<summary>AttributeId. </summary>
		AttributeId,
		///<summary>AttributeType. </summary>
		AttributeType,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>DisplayName. </summary>
		DisplayName,
		///<summary>DisplayOrder. </summary>
		DisplayOrder,
		///<summary>IsRequired. </summary>
		IsRequired,
		///<summary>Name. </summary>
		Name,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ProductAttribute. </summary>
	public partial class ProductAttributeRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between ProductAttributeEntity and ProductAttributeValueEntity over the 1:n relation they have, using the relation between the fields: ProductAttribute.AttributeId - ProductAttributeValue.AttributeId</summary>
		public virtual IEntityRelation ProductAttributeValueEntityUsingAttributeId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ProductAttributeValues", true, new[] { ProductAttributeFields.AttributeId, ProductAttributeValueFields.AttributeId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticProductAttributeRelations
	{
		internal static readonly IEntityRelation ProductAttributeValueEntityUsingAttributeIdStatic = new ProductAttributeRelations().ProductAttributeValueEntityUsingAttributeId;

		/// <summary>CTor</summary>
		static StaticProductAttributeRelations() { }
	}
}
