//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Product'.<br/><br/></summary>
	[Serializable]
	public partial class ProductEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<ShoppingCartItemEntity> _shoppingCartItems;
		private EntityCollection<WishlistItemEntity> _wishlistItems;
		private EntityCollection<ProductAttributeValueEntity> _productAttributeValues;
		private EntityCollection<ProductImageEntity> _productImages;
		private EntityCollection<ProductQuestionEntity> _productQuestions;
		private EntityCollection<ProductTagAssignmentEntity> _productTagAssignments;
		private EntityCollection<ProductVariantEntity> _productVariants;
		private EntityCollection<PurchaseOrderItemEntity> _purchaseOrderItems;
		private EntityCollection<StockMovementEntity> _stockMovements;
		private EntityCollection<ProductReviewEntity> _productReviews;
		private EntityCollection<OrderItemEntity> _orderItems;
		private UserEntity _user;
		private UserEntity _user1;
		private BrandEntity _brand;
		private CategoryEntity _category;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ProductEntityStaticMetaData _staticMetaData = new ProductEntityStaticMetaData();
		private static ProductRelations _relationsFactory = new ProductRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
			/// <summary>Member name User1</summary>
			public static readonly string User1 = "User1";
			/// <summary>Member name Brand</summary>
			public static readonly string Brand = "Brand";
			/// <summary>Member name Category</summary>
			public static readonly string Category = "Category";
			/// <summary>Member name ShoppingCartItems</summary>
			public static readonly string ShoppingCartItems = "ShoppingCartItems";
			/// <summary>Member name WishlistItems</summary>
			public static readonly string WishlistItems = "WishlistItems";
			/// <summary>Member name ProductAttributeValues</summary>
			public static readonly string ProductAttributeValues = "ProductAttributeValues";
			/// <summary>Member name ProductImages</summary>
			public static readonly string ProductImages = "ProductImages";
			/// <summary>Member name ProductQuestions</summary>
			public static readonly string ProductQuestions = "ProductQuestions";
			/// <summary>Member name ProductTagAssignments</summary>
			public static readonly string ProductTagAssignments = "ProductTagAssignments";
			/// <summary>Member name ProductVariants</summary>
			public static readonly string ProductVariants = "ProductVariants";
			/// <summary>Member name PurchaseOrderItems</summary>
			public static readonly string PurchaseOrderItems = "PurchaseOrderItems";
			/// <summary>Member name StockMovements</summary>
			public static readonly string StockMovements = "StockMovements";
			/// <summary>Member name ProductReviews</summary>
			public static readonly string ProductReviews = "ProductReviews";
			/// <summary>Member name OrderItems</summary>
			public static readonly string OrderItems = "OrderItems";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ProductEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ProductEntityStaticMetaData()
			{
				SetEntityCoreInfo("ProductEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.ProductEntity, typeof(ProductEntity), typeof(ProductEntityFactory), false);
				AddNavigatorMetaData<ProductEntity, EntityCollection<ShoppingCartItemEntity>>("ShoppingCartItems", a => a._shoppingCartItems, (a, b) => a._shoppingCartItems = b, a => a.ShoppingCartItems, () => new ProductRelations().ShoppingCartItemEntityUsingProductId, typeof(ShoppingCartItemEntity), (int)GroceryEcommerce.EntityType.ShoppingCartItemEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<WishlistItemEntity>>("WishlistItems", a => a._wishlistItems, (a, b) => a._wishlistItems = b, a => a.WishlistItems, () => new ProductRelations().WishlistItemEntityUsingProductId, typeof(WishlistItemEntity), (int)GroceryEcommerce.EntityType.WishlistItemEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<ProductAttributeValueEntity>>("ProductAttributeValues", a => a._productAttributeValues, (a, b) => a._productAttributeValues = b, a => a.ProductAttributeValues, () => new ProductRelations().ProductAttributeValueEntityUsingProductId, typeof(ProductAttributeValueEntity), (int)GroceryEcommerce.EntityType.ProductAttributeValueEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<ProductImageEntity>>("ProductImages", a => a._productImages, (a, b) => a._productImages = b, a => a.ProductImages, () => new ProductRelations().ProductImageEntityUsingProductId, typeof(ProductImageEntity), (int)GroceryEcommerce.EntityType.ProductImageEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<ProductQuestionEntity>>("ProductQuestions", a => a._productQuestions, (a, b) => a._productQuestions = b, a => a.ProductQuestions, () => new ProductRelations().ProductQuestionEntityUsingProductId, typeof(ProductQuestionEntity), (int)GroceryEcommerce.EntityType.ProductQuestionEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<ProductTagAssignmentEntity>>("ProductTagAssignments", a => a._productTagAssignments, (a, b) => a._productTagAssignments = b, a => a.ProductTagAssignments, () => new ProductRelations().ProductTagAssignmentEntityUsingProductId, typeof(ProductTagAssignmentEntity), (int)GroceryEcommerce.EntityType.ProductTagAssignmentEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<ProductVariantEntity>>("ProductVariants", a => a._productVariants, (a, b) => a._productVariants = b, a => a.ProductVariants, () => new ProductRelations().ProductVariantEntityUsingProductId, typeof(ProductVariantEntity), (int)GroceryEcommerce.EntityType.ProductVariantEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<PurchaseOrderItemEntity>>("PurchaseOrderItems", a => a._purchaseOrderItems, (a, b) => a._purchaseOrderItems = b, a => a.PurchaseOrderItems, () => new ProductRelations().PurchaseOrderItemEntityUsingProductId, typeof(PurchaseOrderItemEntity), (int)GroceryEcommerce.EntityType.PurchaseOrderItemEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<StockMovementEntity>>("StockMovements", a => a._stockMovements, (a, b) => a._stockMovements = b, a => a.StockMovements, () => new ProductRelations().StockMovementEntityUsingProductId, typeof(StockMovementEntity), (int)GroceryEcommerce.EntityType.StockMovementEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<ProductReviewEntity>>("ProductReviews", a => a._productReviews, (a, b) => a._productReviews = b, a => a.ProductReviews, () => new ProductRelations().ProductReviewEntityUsingProductId, typeof(ProductReviewEntity), (int)GroceryEcommerce.EntityType.ProductReviewEntity);
				AddNavigatorMetaData<ProductEntity, EntityCollection<OrderItemEntity>>("OrderItems", a => a._orderItems, (a, b) => a._orderItems = b, a => a.OrderItems, () => new ProductRelations().OrderItemEntityUsingProductId, typeof(OrderItemEntity), (int)GroceryEcommerce.EntityType.OrderItemEntity);
				AddNavigatorMetaData<ProductEntity, UserEntity>("User", "Products", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, GroceryEcommerce.RelationClasses.StaticProductRelations.UserEntityUsingCreatedByStatic, ()=>new ProductRelations().UserEntityUsingCreatedBy, null, new int[] { (int)ProductFieldIndex.CreatedBy }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
				AddNavigatorMetaData<ProductEntity, UserEntity>("User1", "Products1", (a, b) => a._user1 = b, a => a._user1, (a, b) => a.User1 = b, GroceryEcommerce.RelationClasses.StaticProductRelations.UserEntityUsingUpdatedByStatic, ()=>new ProductRelations().UserEntityUsingUpdatedBy, null, new int[] { (int)ProductFieldIndex.UpdatedBy }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
				AddNavigatorMetaData<ProductEntity, BrandEntity>("Brand", "Products", (a, b) => a._brand = b, a => a._brand, (a, b) => a.Brand = b, GroceryEcommerce.RelationClasses.StaticProductRelations.BrandEntityUsingBrandIdStatic, ()=>new ProductRelations().BrandEntityUsingBrandId, null, new int[] { (int)ProductFieldIndex.BrandId }, null, true, (int)GroceryEcommerce.EntityType.BrandEntity);
				AddNavigatorMetaData<ProductEntity, CategoryEntity>("Category", "Products", (a, b) => a._category = b, a => a._category, (a, b) => a.Category = b, GroceryEcommerce.RelationClasses.StaticProductRelations.CategoryEntityUsingCategoryIdStatic, ()=>new ProductRelations().CategoryEntityUsingCategoryId, null, new int[] { (int)ProductFieldIndex.CategoryId }, null, true, (int)GroceryEcommerce.EntityType.CategoryEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ProductEntity()
		{
		}

		/// <summary> CTor</summary>
		public ProductEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ProductEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ProductEntity</param>
		public ProductEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="productId">PK value for Product which data should be fetched into this Product object</param>
		public ProductEntity(System.Guid productId) : this(productId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="productId">PK value for Product which data should be fetched into this Product object</param>
		/// <param name="validator">The custom validator object for this ProductEntity</param>
		public ProductEntity(System.Guid productId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.ProductId = productId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ProductEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: Sku .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCSku()
		{
			var filter = new PredicateExpression();
			filter.Add(GroceryEcommerce.HelperClasses.ProductFields.Sku == this.Fields.GetCurrentValue((int)ProductFieldIndex.Sku));
 			return filter;
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: Slug .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCSlug()
		{
			var filter = new PredicateExpression();
			filter.Add(GroceryEcommerce.HelperClasses.ProductFields.Slug == this.Fields.GetCurrentValue((int)ProductFieldIndex.Slug));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ShoppingCartItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoShoppingCartItems() { return CreateRelationInfoForNavigator("ShoppingCartItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'WishlistItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoWishlistItems() { return CreateRelationInfoForNavigator("WishlistItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ProductAttributeValue' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductAttributeValues() { return CreateRelationInfoForNavigator("ProductAttributeValues"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ProductImage' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductImages() { return CreateRelationInfoForNavigator("ProductImages"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ProductQuestion' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductQuestions() { return CreateRelationInfoForNavigator("ProductQuestions"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ProductTagAssignment' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductTagAssignments() { return CreateRelationInfoForNavigator("ProductTagAssignments"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ProductVariant' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductVariants() { return CreateRelationInfoForNavigator("ProductVariants"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'PurchaseOrderItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPurchaseOrderItems() { return CreateRelationInfoForNavigator("PurchaseOrderItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'StockMovement' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoStockMovements() { return CreateRelationInfoForNavigator("StockMovements"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'ProductReview' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductReviews() { return CreateRelationInfoForNavigator("ProductReviews"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'OrderItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrderItems() { return CreateRelationInfoForNavigator("OrderItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser1() { return CreateRelationInfoForNavigator("User1"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Brand' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoBrand() { return CreateRelationInfoForNavigator("Brand"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Category' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoCategory() { return CreateRelationInfoForNavigator("Category"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ProductEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ProductRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ShoppingCartItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathShoppingCartItems { get { return _staticMetaData.GetPrefetchPathElement("ShoppingCartItems", CommonEntityBase.CreateEntityCollection<ShoppingCartItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'WishlistItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathWishlistItems { get { return _staticMetaData.GetPrefetchPathElement("WishlistItems", CommonEntityBase.CreateEntityCollection<WishlistItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductAttributeValue' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductAttributeValues { get { return _staticMetaData.GetPrefetchPathElement("ProductAttributeValues", CommonEntityBase.CreateEntityCollection<ProductAttributeValueEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductImage' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductImages { get { return _staticMetaData.GetPrefetchPathElement("ProductImages", CommonEntityBase.CreateEntityCollection<ProductImageEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductQuestion' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductQuestions { get { return _staticMetaData.GetPrefetchPathElement("ProductQuestions", CommonEntityBase.CreateEntityCollection<ProductQuestionEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductTagAssignment' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductTagAssignments { get { return _staticMetaData.GetPrefetchPathElement("ProductTagAssignments", CommonEntityBase.CreateEntityCollection<ProductTagAssignmentEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductVariant' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductVariants { get { return _staticMetaData.GetPrefetchPathElement("ProductVariants", CommonEntityBase.CreateEntityCollection<ProductVariantEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'PurchaseOrderItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPurchaseOrderItems { get { return _staticMetaData.GetPrefetchPathElement("PurchaseOrderItems", CommonEntityBase.CreateEntityCollection<PurchaseOrderItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'StockMovement' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathStockMovements { get { return _staticMetaData.GetPrefetchPathElement("StockMovements", CommonEntityBase.CreateEntityCollection<StockMovementEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductReview' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductReviews { get { return _staticMetaData.GetPrefetchPathElement("ProductReviews", CommonEntityBase.CreateEntityCollection<ProductReviewEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'OrderItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrderItems { get { return _staticMetaData.GetPrefetchPathElement("OrderItems", CommonEntityBase.CreateEntityCollection<OrderItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser1 { get { return _staticMetaData.GetPrefetchPathElement("User1", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Brand' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathBrand { get { return _staticMetaData.GetPrefetchPathElement("Brand", CommonEntityBase.CreateEntityCollection<BrandEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Category' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathCategory { get { return _staticMetaData.GetPrefetchPathElement("Category", CommonEntityBase.CreateEntityCollection<CategoryEntity>()); } }

		/// <summary>The BrandId property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."brand_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> BrandId
		{
			get { return (Nullable<System.Guid>)GetValue((int)ProductFieldIndex.BrandId, false); }
			set { SetValue((int)ProductFieldIndex.BrandId, value); }
		}

		/// <summary>The CategoryId property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."category_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid CategoryId
		{
			get { return (System.Guid)GetValue((int)ProductFieldIndex.CategoryId, true); }
			set { SetValue((int)ProductFieldIndex.CategoryId, value); }
		}

		/// <summary>The Cost property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."cost".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> Cost
		{
			get { return (Nullable<System.Decimal>)GetValue((int)ProductFieldIndex.Cost, false); }
			set { SetValue((int)ProductFieldIndex.Cost, value); }
		}

		/// <summary>The CreatedAt property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)ProductFieldIndex.CreatedAt, true); }
			set { SetValue((int)ProductFieldIndex.CreatedAt, value); }
		}

		/// <summary>The CreatedBy property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."created_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid CreatedBy
		{
			get { return (System.Guid)GetValue((int)ProductFieldIndex.CreatedBy, true); }
			set { SetValue((int)ProductFieldIndex.CreatedBy, value); }
		}

		/// <summary>The Description property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."description".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Description
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.Description, true); }
			set { SetValue((int)ProductFieldIndex.Description, value); }
		}

		/// <summary>The Dimensions property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."dimensions".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 50.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Dimensions
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.Dimensions, true); }
			set { SetValue((int)ProductFieldIndex.Dimensions, value); }
		}

		/// <summary>The DiscountPrice property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."discount_price".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> DiscountPrice
		{
			get { return (Nullable<System.Decimal>)GetValue((int)ProductFieldIndex.DiscountPrice, false); }
			set { SetValue((int)ProductFieldIndex.DiscountPrice, value); }
		}

		/// <summary>The IsDigital property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."is_digital".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsDigital
		{
			get { return (System.Boolean)GetValue((int)ProductFieldIndex.IsDigital, true); }
			set { SetValue((int)ProductFieldIndex.IsDigital, value); }
		}

		/// <summary>The IsFeatured property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."is_featured".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsFeatured
		{
			get { return (System.Boolean)GetValue((int)ProductFieldIndex.IsFeatured, true); }
			set { SetValue((int)ProductFieldIndex.IsFeatured, value); }
		}

		/// <summary>The MetaDescription property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."meta_description".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MetaDescription
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.MetaDescription, true); }
			set { SetValue((int)ProductFieldIndex.MetaDescription, value); }
		}

		/// <summary>The MetaTitle property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."meta_title".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String MetaTitle
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.MetaTitle, true); }
			set { SetValue((int)ProductFieldIndex.MetaTitle, value); }
		}

		/// <summary>The MinStockLevel property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."min_stock_level".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 MinStockLevel
		{
			get { return (System.Int32)GetValue((int)ProductFieldIndex.MinStockLevel, true); }
			set { SetValue((int)ProductFieldIndex.MinStockLevel, value); }
		}

		/// <summary>The Name property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."name".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Name
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.Name, true); }
			set { SetValue((int)ProductFieldIndex.Name, value); }
		}

		/// <summary>The Price property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."price".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal Price
		{
			get { return (System.Decimal)GetValue((int)ProductFieldIndex.Price, true); }
			set { SetValue((int)ProductFieldIndex.Price, value); }
		}

		/// <summary>The ProductId property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."product_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid ProductId
		{
			get { return (System.Guid)GetValue((int)ProductFieldIndex.ProductId, true); }
			set { SetValue((int)ProductFieldIndex.ProductId, value); }
		}

		/// <summary>The ShortDescription property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."short_description".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String ShortDescription
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.ShortDescription, true); }
			set { SetValue((int)ProductFieldIndex.ShortDescription, value); }
		}

		/// <summary>The Sku property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."sku".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Sku
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.Sku, true); }
			set { SetValue((int)ProductFieldIndex.Sku, value); }
		}

		/// <summary>The Slug property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."slug".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Slug
		{
			get { return (System.String)GetValue((int)ProductFieldIndex.Slug, true); }
			set { SetValue((int)ProductFieldIndex.Slug, value); }
		}

		/// <summary>The Status property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."status".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 Status
		{
			get { return (System.Int16)GetValue((int)ProductFieldIndex.Status, true); }
			set { SetValue((int)ProductFieldIndex.Status, value); }
		}

		/// <summary>The StockQuantity property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."stock_quantity".<br/>Table field type characteristics (type, precision, scale, length): Integer, 10, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int32 StockQuantity
		{
			get { return (System.Int32)GetValue((int)ProductFieldIndex.StockQuantity, true); }
			set { SetValue((int)ProductFieldIndex.StockQuantity, value); }
		}

		/// <summary>The UpdatedAt property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ProductFieldIndex.UpdatedAt, false); }
			set { SetValue((int)ProductFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UpdatedBy property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."updated_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> UpdatedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)ProductFieldIndex.UpdatedBy, false); }
			set { SetValue((int)ProductFieldIndex.UpdatedBy, value); }
		}

		/// <summary>The Weight property of the Entity Product<br/><br/></summary>
		/// <remarks>Mapped on  table field: "products"."weight".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 10, 3, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Decimal> Weight
		{
			get { return (Nullable<System.Decimal>)GetValue((int)ProductFieldIndex.Weight, false); }
			set { SetValue((int)ProductFieldIndex.Weight, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'ShoppingCartItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ShoppingCartItemEntity))]
		public virtual EntityCollection<ShoppingCartItemEntity> ShoppingCartItems { get { return GetOrCreateEntityCollection<ShoppingCartItemEntity, ShoppingCartItemEntityFactory>("Product", true, false, ref _shoppingCartItems); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'WishlistItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(WishlistItemEntity))]
		public virtual EntityCollection<WishlistItemEntity> WishlistItems { get { return GetOrCreateEntityCollection<WishlistItemEntity, WishlistItemEntityFactory>("Product", true, false, ref _wishlistItems); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'ProductAttributeValueEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProductAttributeValueEntity))]
		public virtual EntityCollection<ProductAttributeValueEntity> ProductAttributeValues { get { return GetOrCreateEntityCollection<ProductAttributeValueEntity, ProductAttributeValueEntityFactory>("Product", true, false, ref _productAttributeValues); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'ProductImageEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProductImageEntity))]
		public virtual EntityCollection<ProductImageEntity> ProductImages { get { return GetOrCreateEntityCollection<ProductImageEntity, ProductImageEntityFactory>("Product", true, false, ref _productImages); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'ProductQuestionEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProductQuestionEntity))]
		public virtual EntityCollection<ProductQuestionEntity> ProductQuestions { get { return GetOrCreateEntityCollection<ProductQuestionEntity, ProductQuestionEntityFactory>("Product", true, false, ref _productQuestions); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'ProductTagAssignmentEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProductTagAssignmentEntity))]
		public virtual EntityCollection<ProductTagAssignmentEntity> ProductTagAssignments { get { return GetOrCreateEntityCollection<ProductTagAssignmentEntity, ProductTagAssignmentEntityFactory>("Product", true, false, ref _productTagAssignments); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'ProductVariantEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProductVariantEntity))]
		public virtual EntityCollection<ProductVariantEntity> ProductVariants { get { return GetOrCreateEntityCollection<ProductVariantEntity, ProductVariantEntityFactory>("Product", true, false, ref _productVariants); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'PurchaseOrderItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(PurchaseOrderItemEntity))]
		public virtual EntityCollection<PurchaseOrderItemEntity> PurchaseOrderItems { get { return GetOrCreateEntityCollection<PurchaseOrderItemEntity, PurchaseOrderItemEntityFactory>("Product", true, false, ref _purchaseOrderItems); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'StockMovementEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(StockMovementEntity))]
		public virtual EntityCollection<StockMovementEntity> StockMovements { get { return GetOrCreateEntityCollection<StockMovementEntity, StockMovementEntityFactory>("Product", true, false, ref _stockMovements); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'ProductReviewEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(ProductReviewEntity))]
		public virtual EntityCollection<ProductReviewEntity> ProductReviews { get { return GetOrCreateEntityCollection<ProductReviewEntity, ProductReviewEntityFactory>("Product", true, false, ref _productReviews); } }

		/// <summary>Gets the EntityCollection with the related entities of type 'OrderItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(OrderItemEntity))]
		public virtual EntityCollection<OrderItemEntity> OrderItems { get { return GetOrCreateEntityCollection<OrderItemEntity, OrderItemEntityFactory>("Product", true, false, ref _orderItems); } }

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User1
		{
			get { return _user1; }
			set { SetSingleRelatedEntityNavigator(value, "User1"); }
		}

		/// <summary>Gets / sets related entity of type 'BrandEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual BrandEntity Brand
		{
			get { return _brand; }
			set { SetSingleRelatedEntityNavigator(value, "Brand"); }
		}

		/// <summary>Gets / sets related entity of type 'CategoryEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual CategoryEntity Category
		{
			get { return _category; }
			set { SetSingleRelatedEntityNavigator(value, "Category"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace GroceryEcommerce
{
	public enum ProductFieldIndex
	{
		///<summary>BrandId. </summary>
		BrandId,
		///<summary>CategoryId. </summary>
		CategoryId,
		///<summary>Cost. </summary>
		Cost,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>CreatedBy. </summary>
		CreatedBy,
		///<summary>Description. </summary>
		Description,
		///<summary>Dimensions. </summary>
		Dimensions,
		///<summary>DiscountPrice. </summary>
		DiscountPrice,
		///<summary>IsDigital. </summary>
		IsDigital,
		///<summary>IsFeatured. </summary>
		IsFeatured,
		///<summary>MetaDescription. </summary>
		MetaDescription,
		///<summary>MetaTitle. </summary>
		MetaTitle,
		///<summary>MinStockLevel. </summary>
		MinStockLevel,
		///<summary>Name. </summary>
		Name,
		///<summary>Price. </summary>
		Price,
		///<summary>ProductId. </summary>
		ProductId,
		///<summary>ShortDescription. </summary>
		ShortDescription,
		///<summary>Sku. </summary>
		Sku,
		///<summary>Slug. </summary>
		Slug,
		///<summary>Status. </summary>
		Status,
		///<summary>StockQuantity. </summary>
		StockQuantity,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UpdatedBy. </summary>
		UpdatedBy,
		///<summary>Weight. </summary>
		Weight,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Product. </summary>
	public partial class ProductRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between ProductEntity and ShoppingCartItemEntity over the 1:n relation they have, using the relation between the fields: Product.ProductId - ShoppingCartItem.ProductId</summary>
		public virtual IEntityRelation ShoppingCartItemEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ShoppingCartItems", true, new[] { ProductFields.ProductId, ShoppingCartItemFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and WishlistItemEntity over the 1:n relation they have, using the relation between the fields: Product.ProductId - WishlistItem.ProductId</summary>
		public virtual IEntityRelation WishlistItemEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "WishlistItems", true, new[] { ProductFields.ProductId, WishlistItemFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and ProductAttributeValueEntity over the 1:n relation they have, using the relation between the fields: Product.ProductId - ProductAttributeValue.ProductId</summary>
		public virtual IEntityRelation ProductAttributeValueEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ProductAttributeValues", true, new[] { ProductFields.ProductId, ProductAttributeValueFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and ProductImageEntity over the 1:n relation they have, using the relation between the fields: Product.ProductId - ProductImage.ProductId</summary>
		public virtual IEntityRelation ProductImageEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ProductImages", true, new[] { ProductFields.ProductId, ProductImageFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and ProductQuestionEntity over the 1:n relation they have, using the relation between the fields: Product.ProductId - ProductQuestion.ProductId</summary>
		public virtual IEntityRelation ProductQuestionEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ProductQuestions", true, new[] { ProductFields.ProductId, ProductQuestionFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and ProductTagAssignmentEntity over the 1:n relation they have, using the relation between the fields: Product.ProductId - ProductTagAssignment.ProductId</summary>
		public virtual IEntityRelation ProductTagAssignmentEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ProductTagAssignments", true, new[] { ProductFields.ProductId, ProductTagAssignmentFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and ProductVariantEntity over the 1:n relation they have, using the relation between the fields: Product.ProductId - ProductVariant.ProductId</summary>
		public virtual IEntityRelation ProductVariantEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ProductVariants", true, new[] { ProductFields.ProductId, ProductVariantFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and PurchaseOrderItemEntity over the 1:n relation they have, using the relation between the fields: Product.ProductId - PurchaseOrderItem.ProductId</summary>
		public virtual IEntityRelation PurchaseOrderItemEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "PurchaseOrderItems", true, new[] { ProductFields.ProductId, PurchaseOrderItemFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and StockMovementEntity over the 1:n relation they have, using the relation between the fields: Product.ProductId - StockMovement.ProductId</summary>
		public virtual IEntityRelation StockMovementEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "StockMovements", true, new[] { ProductFields.ProductId, StockMovementFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and ProductReviewEntity over the 1:n relation they have, using the relation between the fields: Product.ProductId - ProductReview.ProductId</summary>
		public virtual IEntityRelation ProductReviewEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "ProductReviews", true, new[] { ProductFields.ProductId, ProductReviewFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and OrderItemEntity over the 1:n relation they have, using the relation between the fields: Product.ProductId - OrderItem.ProductId</summary>
		public virtual IEntityRelation OrderItemEntityUsingProductId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "OrderItems", true, new[] { ProductFields.ProductId, OrderItemFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Product.CreatedBy - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingCreatedBy
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.UserId, ProductFields.CreatedBy }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and UserEntity over the m:1 relation they have, using the relation between the fields: Product.UpdatedBy - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingUpdatedBy
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User1", false, new[] { UserFields.UserId, ProductFields.UpdatedBy }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and BrandEntity over the m:1 relation they have, using the relation between the fields: Product.BrandId - Brand.BrandId</summary>
		public virtual IEntityRelation BrandEntityUsingBrandId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Brand", false, new[] { BrandFields.BrandId, ProductFields.BrandId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductEntity and CategoryEntity over the m:1 relation they have, using the relation between the fields: Product.CategoryId - Category.CategoryId</summary>
		public virtual IEntityRelation CategoryEntityUsingCategoryId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Category", false, new[] { CategoryFields.CategoryId, ProductFields.CategoryId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticProductRelations
	{
		internal static readonly IEntityRelation ShoppingCartItemEntityUsingProductIdStatic = new ProductRelations().ShoppingCartItemEntityUsingProductId;
		internal static readonly IEntityRelation WishlistItemEntityUsingProductIdStatic = new ProductRelations().WishlistItemEntityUsingProductId;
		internal static readonly IEntityRelation ProductAttributeValueEntityUsingProductIdStatic = new ProductRelations().ProductAttributeValueEntityUsingProductId;
		internal static readonly IEntityRelation ProductImageEntityUsingProductIdStatic = new ProductRelations().ProductImageEntityUsingProductId;
		internal static readonly IEntityRelation ProductQuestionEntityUsingProductIdStatic = new ProductRelations().ProductQuestionEntityUsingProductId;
		internal static readonly IEntityRelation ProductTagAssignmentEntityUsingProductIdStatic = new ProductRelations().ProductTagAssignmentEntityUsingProductId;
		internal static readonly IEntityRelation ProductVariantEntityUsingProductIdStatic = new ProductRelations().ProductVariantEntityUsingProductId;
		internal static readonly IEntityRelation PurchaseOrderItemEntityUsingProductIdStatic = new ProductRelations().PurchaseOrderItemEntityUsingProductId;
		internal static readonly IEntityRelation StockMovementEntityUsingProductIdStatic = new ProductRelations().StockMovementEntityUsingProductId;
		internal static readonly IEntityRelation ProductReviewEntityUsingProductIdStatic = new ProductRelations().ProductReviewEntityUsingProductId;
		internal static readonly IEntityRelation OrderItemEntityUsingProductIdStatic = new ProductRelations().OrderItemEntityUsingProductId;
		internal static readonly IEntityRelation UserEntityUsingCreatedByStatic = new ProductRelations().UserEntityUsingCreatedBy;
		internal static readonly IEntityRelation UserEntityUsingUpdatedByStatic = new ProductRelations().UserEntityUsingUpdatedBy;
		internal static readonly IEntityRelation BrandEntityUsingBrandIdStatic = new ProductRelations().BrandEntityUsingBrandId;
		internal static readonly IEntityRelation CategoryEntityUsingCategoryIdStatic = new ProductRelations().CategoryEntityUsingCategoryId;

		/// <summary>CTor</summary>
		static StaticProductRelations() { }
	}
}
