//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'ProductTagAssignment'.<br/><br/></summary>
	[Serializable]
	public partial class ProductTagAssignmentEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private ProductEntity _product;
		private ProductTagEntity _productTag;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ProductTagAssignmentEntityStaticMetaData _staticMetaData = new ProductTagAssignmentEntityStaticMetaData();
		private static ProductTagAssignmentRelations _relationsFactory = new ProductTagAssignmentRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Product</summary>
			public static readonly string Product = "Product";
			/// <summary>Member name ProductTag</summary>
			public static readonly string ProductTag = "ProductTag";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ProductTagAssignmentEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ProductTagAssignmentEntityStaticMetaData()
			{
				SetEntityCoreInfo("ProductTagAssignmentEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.ProductTagAssignmentEntity, typeof(ProductTagAssignmentEntity), typeof(ProductTagAssignmentEntityFactory), false);
				AddNavigatorMetaData<ProductTagAssignmentEntity, ProductEntity>("Product", "ProductTagAssignments", (a, b) => a._product = b, a => a._product, (a, b) => a.Product = b, GroceryEcommerce.RelationClasses.StaticProductTagAssignmentRelations.ProductEntityUsingProductIdStatic, ()=>new ProductTagAssignmentRelations().ProductEntityUsingProductId, null, new int[] { (int)ProductTagAssignmentFieldIndex.ProductId }, null, true, (int)GroceryEcommerce.EntityType.ProductEntity);
				AddNavigatorMetaData<ProductTagAssignmentEntity, ProductTagEntity>("ProductTag", "ProductTagAssignments", (a, b) => a._productTag = b, a => a._productTag, (a, b) => a.ProductTag = b, GroceryEcommerce.RelationClasses.StaticProductTagAssignmentRelations.ProductTagEntityUsingTagIdStatic, ()=>new ProductTagAssignmentRelations().ProductTagEntityUsingTagId, null, new int[] { (int)ProductTagAssignmentFieldIndex.TagId }, null, true, (int)GroceryEcommerce.EntityType.ProductTagEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ProductTagAssignmentEntity()
		{
		}

		/// <summary> CTor</summary>
		public ProductTagAssignmentEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ProductTagAssignmentEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ProductTagAssignmentEntity</param>
		public ProductTagAssignmentEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="productId">PK value for ProductTagAssignment which data should be fetched into this ProductTagAssignment object</param>
		/// <param name="tagId">PK value for ProductTagAssignment which data should be fetched into this ProductTagAssignment object</param>
		public ProductTagAssignmentEntity(System.Guid productId, System.Guid tagId) : this(productId, tagId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="productId">PK value for ProductTagAssignment which data should be fetched into this ProductTagAssignment object</param>
		/// <param name="tagId">PK value for ProductTagAssignment which data should be fetched into this ProductTagAssignment object</param>
		/// <param name="validator">The custom validator object for this ProductTagAssignmentEntity</param>
		public ProductTagAssignmentEntity(System.Guid productId, System.Guid tagId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.ProductId = productId;
			this.TagId = tagId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ProductTagAssignmentEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Product' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProduct() { return CreateRelationInfoForNavigator("Product"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ProductTag' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductTag() { return CreateRelationInfoForNavigator("ProductTag"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ProductTagAssignmentEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ProductTagAssignmentRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Product' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProduct { get { return _staticMetaData.GetPrefetchPathElement("Product", CommonEntityBase.CreateEntityCollection<ProductEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductTag' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductTag { get { return _staticMetaData.GetPrefetchPathElement("ProductTag", CommonEntityBase.CreateEntityCollection<ProductTagEntity>()); } }

		/// <summary>The ProductId property of the Entity ProductTagAssignment<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_tag_assignments"."product_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid ProductId
		{
			get { return (System.Guid)GetValue((int)ProductTagAssignmentFieldIndex.ProductId, true); }
			set { SetValue((int)ProductTagAssignmentFieldIndex.ProductId, value); }
		}

		/// <summary>The TagId property of the Entity ProductTagAssignment<br/><br/></summary>
		/// <remarks>Mapped on  table field: "product_tag_assignments"."tag_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid TagId
		{
			get { return (System.Guid)GetValue((int)ProductTagAssignmentFieldIndex.TagId, true); }
			set { SetValue((int)ProductTagAssignmentFieldIndex.TagId, value); }
		}

		/// <summary>Gets / sets related entity of type 'ProductEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductEntity Product
		{
			get { return _product; }
			set { SetSingleRelatedEntityNavigator(value, "Product"); }
		}

		/// <summary>Gets / sets related entity of type 'ProductTagEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductTagEntity ProductTag
		{
			get { return _productTag; }
			set { SetSingleRelatedEntityNavigator(value, "ProductTag"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace GroceryEcommerce
{
	public enum ProductTagAssignmentFieldIndex
	{
		///<summary>ProductId. </summary>
		ProductId,
		///<summary>TagId. </summary>
		TagId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ProductTagAssignment. </summary>
	public partial class ProductTagAssignmentRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ProductTagAssignmentEntity and ProductEntity over the m:1 relation they have, using the relation between the fields: ProductTagAssignment.ProductId - Product.ProductId</summary>
		public virtual IEntityRelation ProductEntityUsingProductId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Product", false, new[] { ProductFields.ProductId, ProductTagAssignmentFields.ProductId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ProductTagAssignmentEntity and ProductTagEntity over the m:1 relation they have, using the relation between the fields: ProductTagAssignment.TagId - ProductTag.TagId</summary>
		public virtual IEntityRelation ProductTagEntityUsingTagId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ProductTag", false, new[] { ProductTagFields.TagId, ProductTagAssignmentFields.TagId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticProductTagAssignmentRelations
	{
		internal static readonly IEntityRelation ProductEntityUsingProductIdStatic = new ProductTagAssignmentRelations().ProductEntityUsingProductId;
		internal static readonly IEntityRelation ProductTagEntityUsingTagIdStatic = new ProductTagAssignmentRelations().ProductTagEntityUsingTagId;

		/// <summary>CTor</summary>
		static StaticProductTagAssignmentRelations() { }
	}
}
