//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'PurchaseOrder'.<br/><br/></summary>
	[Serializable]
	public partial class PurchaseOrderEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<PurchaseOrderItemEntity> _purchaseOrderItems;
		private UserEntity _user;
		private SupplierEntity _supplier;
		private WarehouseEntity _warehouse;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static PurchaseOrderEntityStaticMetaData _staticMetaData = new PurchaseOrderEntityStaticMetaData();
		private static PurchaseOrderRelations _relationsFactory = new PurchaseOrderRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
			/// <summary>Member name Supplier</summary>
			public static readonly string Supplier = "Supplier";
			/// <summary>Member name Warehouse</summary>
			public static readonly string Warehouse = "Warehouse";
			/// <summary>Member name PurchaseOrderItems</summary>
			public static readonly string PurchaseOrderItems = "PurchaseOrderItems";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class PurchaseOrderEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public PurchaseOrderEntityStaticMetaData()
			{
				SetEntityCoreInfo("PurchaseOrderEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.PurchaseOrderEntity, typeof(PurchaseOrderEntity), typeof(PurchaseOrderEntityFactory), false);
				AddNavigatorMetaData<PurchaseOrderEntity, EntityCollection<PurchaseOrderItemEntity>>("PurchaseOrderItems", a => a._purchaseOrderItems, (a, b) => a._purchaseOrderItems = b, a => a.PurchaseOrderItems, () => new PurchaseOrderRelations().PurchaseOrderItemEntityUsingPurchaseOrderId, typeof(PurchaseOrderItemEntity), (int)GroceryEcommerce.EntityType.PurchaseOrderItemEntity);
				AddNavigatorMetaData<PurchaseOrderEntity, UserEntity>("User", "PurchaseOrders", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, GroceryEcommerce.RelationClasses.StaticPurchaseOrderRelations.UserEntityUsingCreatedByStatic, ()=>new PurchaseOrderRelations().UserEntityUsingCreatedBy, null, new int[] { (int)PurchaseOrderFieldIndex.CreatedBy }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
				AddNavigatorMetaData<PurchaseOrderEntity, SupplierEntity>("Supplier", "PurchaseOrders", (a, b) => a._supplier = b, a => a._supplier, (a, b) => a.Supplier = b, GroceryEcommerce.RelationClasses.StaticPurchaseOrderRelations.SupplierEntityUsingSupplierIdStatic, ()=>new PurchaseOrderRelations().SupplierEntityUsingSupplierId, null, new int[] { (int)PurchaseOrderFieldIndex.SupplierId }, null, true, (int)GroceryEcommerce.EntityType.SupplierEntity);
				AddNavigatorMetaData<PurchaseOrderEntity, WarehouseEntity>("Warehouse", "PurchaseOrders", (a, b) => a._warehouse = b, a => a._warehouse, (a, b) => a.Warehouse = b, GroceryEcommerce.RelationClasses.StaticPurchaseOrderRelations.WarehouseEntityUsingWarehouseIdStatic, ()=>new PurchaseOrderRelations().WarehouseEntityUsingWarehouseId, null, new int[] { (int)PurchaseOrderFieldIndex.WarehouseId }, null, true, (int)GroceryEcommerce.EntityType.WarehouseEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static PurchaseOrderEntity()
		{
		}

		/// <summary> CTor</summary>
		public PurchaseOrderEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public PurchaseOrderEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this PurchaseOrderEntity</param>
		public PurchaseOrderEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="purchaseOrderId">PK value for PurchaseOrder which data should be fetched into this PurchaseOrder object</param>
		public PurchaseOrderEntity(System.Guid purchaseOrderId) : this(purchaseOrderId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="purchaseOrderId">PK value for PurchaseOrder which data should be fetched into this PurchaseOrder object</param>
		/// <param name="validator">The custom validator object for this PurchaseOrderEntity</param>
		public PurchaseOrderEntity(System.Guid purchaseOrderId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.PurchaseOrderId = purchaseOrderId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected PurchaseOrderEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Method which will construct a filter (predicate expression) for the unique constraint defined on the fields: OrderNumber .</summary>
		/// <returns>true if succeeded and the contents is read, false otherwise</returns>
		public IPredicateExpression ConstructFilterForUCOrderNumber()
		{
			var filter = new PredicateExpression();
			filter.Add(GroceryEcommerce.HelperClasses.PurchaseOrderFields.OrderNumber == this.Fields.GetCurrentValue((int)PurchaseOrderFieldIndex.OrderNumber));
 			return filter;
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'PurchaseOrderItem' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPurchaseOrderItems() { return CreateRelationInfoForNavigator("PurchaseOrderItems"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Supplier' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoSupplier() { return CreateRelationInfoForNavigator("Supplier"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Warehouse' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoWarehouse() { return CreateRelationInfoForNavigator("Warehouse"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this PurchaseOrderEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static PurchaseOrderRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'PurchaseOrderItem' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPurchaseOrderItems { get { return _staticMetaData.GetPrefetchPathElement("PurchaseOrderItems", CommonEntityBase.CreateEntityCollection<PurchaseOrderItemEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Supplier' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathSupplier { get { return _staticMetaData.GetPrefetchPathElement("Supplier", CommonEntityBase.CreateEntityCollection<SupplierEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Warehouse' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathWarehouse { get { return _staticMetaData.GetPrefetchPathElement("Warehouse", CommonEntityBase.CreateEntityCollection<WarehouseEntity>()); } }

		/// <summary>The CreatedAt property of the Entity PurchaseOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "purchase_orders"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)PurchaseOrderFieldIndex.CreatedAt, true); }
			set { SetValue((int)PurchaseOrderFieldIndex.CreatedAt, value); }
		}

		/// <summary>The CreatedBy property of the Entity PurchaseOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "purchase_orders"."created_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> CreatedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)PurchaseOrderFieldIndex.CreatedBy, false); }
			set { SetValue((int)PurchaseOrderFieldIndex.CreatedBy, value); }
		}

		/// <summary>The ExpectedDate property of the Entity PurchaseOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "purchase_orders"."expected_date".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> ExpectedDate
		{
			get { return (Nullable<System.DateTime>)GetValue((int)PurchaseOrderFieldIndex.ExpectedDate, false); }
			set { SetValue((int)PurchaseOrderFieldIndex.ExpectedDate, value); }
		}

		/// <summary>The OrderDate property of the Entity PurchaseOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "purchase_orders"."order_date".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime OrderDate
		{
			get { return (System.DateTime)GetValue((int)PurchaseOrderFieldIndex.OrderDate, true); }
			set { SetValue((int)PurchaseOrderFieldIndex.OrderDate, value); }
		}

		/// <summary>The OrderNumber property of the Entity PurchaseOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "purchase_orders"."order_number".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String OrderNumber
		{
			get { return (System.String)GetValue((int)PurchaseOrderFieldIndex.OrderNumber, true); }
			set { SetValue((int)PurchaseOrderFieldIndex.OrderNumber, value); }
		}

		/// <summary>The PurchaseOrderId property of the Entity PurchaseOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "purchase_orders"."purchase_order_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid PurchaseOrderId
		{
			get { return (System.Guid)GetValue((int)PurchaseOrderFieldIndex.PurchaseOrderId, true); }
			set { SetValue((int)PurchaseOrderFieldIndex.PurchaseOrderId, value); }
		}

		/// <summary>The Status property of the Entity PurchaseOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "purchase_orders"."status".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 Status
		{
			get { return (System.Int16)GetValue((int)PurchaseOrderFieldIndex.Status, true); }
			set { SetValue((int)PurchaseOrderFieldIndex.Status, value); }
		}

		/// <summary>The SupplierId property of the Entity PurchaseOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "purchase_orders"."supplier_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid SupplierId
		{
			get { return (System.Guid)GetValue((int)PurchaseOrderFieldIndex.SupplierId, true); }
			set { SetValue((int)PurchaseOrderFieldIndex.SupplierId, value); }
		}

		/// <summary>The TotalAmount property of the Entity PurchaseOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "purchase_orders"."total_amount".<br/>Table field type characteristics (type, precision, scale, length): Numeric, 18, 2, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Decimal TotalAmount
		{
			get { return (System.Decimal)GetValue((int)PurchaseOrderFieldIndex.TotalAmount, true); }
			set { SetValue((int)PurchaseOrderFieldIndex.TotalAmount, value); }
		}

		/// <summary>The UpdatedAt property of the Entity PurchaseOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "purchase_orders"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)PurchaseOrderFieldIndex.UpdatedAt, false); }
			set { SetValue((int)PurchaseOrderFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The WarehouseId property of the Entity PurchaseOrder<br/><br/></summary>
		/// <remarks>Mapped on  table field: "purchase_orders"."warehouse_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> WarehouseId
		{
			get { return (Nullable<System.Guid>)GetValue((int)PurchaseOrderFieldIndex.WarehouseId, false); }
			set { SetValue((int)PurchaseOrderFieldIndex.WarehouseId, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'PurchaseOrderItemEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(PurchaseOrderItemEntity))]
		public virtual EntityCollection<PurchaseOrderItemEntity> PurchaseOrderItems { get { return GetOrCreateEntityCollection<PurchaseOrderItemEntity, PurchaseOrderItemEntityFactory>("PurchaseOrder", true, false, ref _purchaseOrderItems); } }

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		/// <summary>Gets / sets related entity of type 'SupplierEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual SupplierEntity Supplier
		{
			get { return _supplier; }
			set { SetSingleRelatedEntityNavigator(value, "Supplier"); }
		}

		/// <summary>Gets / sets related entity of type 'WarehouseEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual WarehouseEntity Warehouse
		{
			get { return _warehouse; }
			set { SetSingleRelatedEntityNavigator(value, "Warehouse"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace GroceryEcommerce
{
	public enum PurchaseOrderFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>CreatedBy. </summary>
		CreatedBy,
		///<summary>ExpectedDate. </summary>
		ExpectedDate,
		///<summary>OrderDate. </summary>
		OrderDate,
		///<summary>OrderNumber. </summary>
		OrderNumber,
		///<summary>PurchaseOrderId. </summary>
		PurchaseOrderId,
		///<summary>Status. </summary>
		Status,
		///<summary>SupplierId. </summary>
		SupplierId,
		///<summary>TotalAmount. </summary>
		TotalAmount,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>WarehouseId. </summary>
		WarehouseId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: PurchaseOrder. </summary>
	public partial class PurchaseOrderRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between PurchaseOrderEntity and PurchaseOrderItemEntity over the 1:n relation they have, using the relation between the fields: PurchaseOrder.PurchaseOrderId - PurchaseOrderItem.PurchaseOrderId</summary>
		public virtual IEntityRelation PurchaseOrderItemEntityUsingPurchaseOrderId
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "PurchaseOrderItems", true, new[] { PurchaseOrderFields.PurchaseOrderId, PurchaseOrderItemFields.PurchaseOrderId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PurchaseOrderEntity and UserEntity over the m:1 relation they have, using the relation between the fields: PurchaseOrder.CreatedBy - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingCreatedBy
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.UserId, PurchaseOrderFields.CreatedBy }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PurchaseOrderEntity and SupplierEntity over the m:1 relation they have, using the relation between the fields: PurchaseOrder.SupplierId - Supplier.SupplierId</summary>
		public virtual IEntityRelation SupplierEntityUsingSupplierId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Supplier", false, new[] { SupplierFields.SupplierId, PurchaseOrderFields.SupplierId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PurchaseOrderEntity and WarehouseEntity over the m:1 relation they have, using the relation between the fields: PurchaseOrder.WarehouseId - Warehouse.WarehouseId</summary>
		public virtual IEntityRelation WarehouseEntityUsingWarehouseId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Warehouse", false, new[] { WarehouseFields.WarehouseId, PurchaseOrderFields.WarehouseId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticPurchaseOrderRelations
	{
		internal static readonly IEntityRelation PurchaseOrderItemEntityUsingPurchaseOrderIdStatic = new PurchaseOrderRelations().PurchaseOrderItemEntityUsingPurchaseOrderId;
		internal static readonly IEntityRelation UserEntityUsingCreatedByStatic = new PurchaseOrderRelations().UserEntityUsingCreatedBy;
		internal static readonly IEntityRelation SupplierEntityUsingSupplierIdStatic = new PurchaseOrderRelations().SupplierEntityUsingSupplierId;
		internal static readonly IEntityRelation WarehouseEntityUsingWarehouseIdStatic = new PurchaseOrderRelations().WarehouseEntityUsingWarehouseId;

		/// <summary>CTor</summary>
		static StaticPurchaseOrderRelations() { }
	}
}
