//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'ReviewReport'.<br/><br/></summary>
	[Serializable]
	public partial class ReviewReportEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private UserEntity _user;
		private UserEntity _user1;
		private ProductReviewEntity _productReview;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ReviewReportEntityStaticMetaData _staticMetaData = new ReviewReportEntityStaticMetaData();
		private static ReviewReportRelations _relationsFactory = new ReviewReportRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
			/// <summary>Member name User1</summary>
			public static readonly string User1 = "User1";
			/// <summary>Member name ProductReview</summary>
			public static readonly string ProductReview = "ProductReview";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ReviewReportEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ReviewReportEntityStaticMetaData()
			{
				SetEntityCoreInfo("ReviewReportEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.ReviewReportEntity, typeof(ReviewReportEntity), typeof(ReviewReportEntityFactory), false);
				AddNavigatorMetaData<ReviewReportEntity, UserEntity>("User", "ReviewReports", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, GroceryEcommerce.RelationClasses.StaticReviewReportRelations.UserEntityUsingProcessedByStatic, ()=>new ReviewReportRelations().UserEntityUsingProcessedBy, null, new int[] { (int)ReviewReportFieldIndex.ProcessedBy }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
				AddNavigatorMetaData<ReviewReportEntity, UserEntity>("User1", "ReviewReports1", (a, b) => a._user1 = b, a => a._user1, (a, b) => a.User1 = b, GroceryEcommerce.RelationClasses.StaticReviewReportRelations.UserEntityUsingUserIdStatic, ()=>new ReviewReportRelations().UserEntityUsingUserId, null, new int[] { (int)ReviewReportFieldIndex.UserId }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
				AddNavigatorMetaData<ReviewReportEntity, ProductReviewEntity>("ProductReview", "ReviewReports", (a, b) => a._productReview = b, a => a._productReview, (a, b) => a.ProductReview = b, GroceryEcommerce.RelationClasses.StaticReviewReportRelations.ProductReviewEntityUsingReviewIdStatic, ()=>new ReviewReportRelations().ProductReviewEntityUsingReviewId, null, new int[] { (int)ReviewReportFieldIndex.ReviewId }, null, true, (int)GroceryEcommerce.EntityType.ProductReviewEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ReviewReportEntity()
		{
		}

		/// <summary> CTor</summary>
		public ReviewReportEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ReviewReportEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ReviewReportEntity</param>
		public ReviewReportEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="reportId">PK value for ReviewReport which data should be fetched into this ReviewReport object</param>
		public ReviewReportEntity(System.Guid reportId) : this(reportId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="reportId">PK value for ReviewReport which data should be fetched into this ReviewReport object</param>
		/// <param name="validator">The custom validator object for this ReviewReportEntity</param>
		public ReviewReportEntity(System.Guid reportId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.ReportId = reportId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ReviewReportEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser1() { return CreateRelationInfoForNavigator("User1"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ProductReview' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductReview() { return CreateRelationInfoForNavigator("ProductReview"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ReviewReportEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ReviewReportRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser1 { get { return _staticMetaData.GetPrefetchPathElement("User1", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductReview' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductReview { get { return _staticMetaData.GetPrefetchPathElement("ProductReview", CommonEntityBase.CreateEntityCollection<ProductReviewEntity>()); } }

		/// <summary>The CreatedAt property of the Entity ReviewReport<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_reports"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)ReviewReportFieldIndex.CreatedAt, true); }
			set { SetValue((int)ReviewReportFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Processed property of the Entity ReviewReport<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_reports"."processed".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Processed
		{
			get { return (System.Boolean)GetValue((int)ReviewReportFieldIndex.Processed, true); }
			set { SetValue((int)ReviewReportFieldIndex.Processed, value); }
		}

		/// <summary>The ProcessedAt property of the Entity ReviewReport<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_reports"."processed_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> ProcessedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)ReviewReportFieldIndex.ProcessedAt, false); }
			set { SetValue((int)ReviewReportFieldIndex.ProcessedAt, value); }
		}

		/// <summary>The ProcessedBy property of the Entity ReviewReport<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_reports"."processed_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.Guid> ProcessedBy
		{
			get { return (Nullable<System.Guid>)GetValue((int)ReviewReportFieldIndex.ProcessedBy, false); }
			set { SetValue((int)ReviewReportFieldIndex.ProcessedBy, value); }
		}

		/// <summary>The Reason property of the Entity ReviewReport<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_reports"."reason".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String Reason
		{
			get { return (System.String)GetValue((int)ReviewReportFieldIndex.Reason, true); }
			set { SetValue((int)ReviewReportFieldIndex.Reason, value); }
		}

		/// <summary>The ReportId property of the Entity ReviewReport<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_reports"."report_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid ReportId
		{
			get { return (System.Guid)GetValue((int)ReviewReportFieldIndex.ReportId, true); }
			set { SetValue((int)ReviewReportFieldIndex.ReportId, value); }
		}

		/// <summary>The ReviewId property of the Entity ReviewReport<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_reports"."review_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid ReviewId
		{
			get { return (System.Guid)GetValue((int)ReviewReportFieldIndex.ReviewId, true); }
			set { SetValue((int)ReviewReportFieldIndex.ReviewId, value); }
		}

		/// <summary>The UserId property of the Entity ReviewReport<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_reports"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)ReviewReportFieldIndex.UserId, true); }
			set { SetValue((int)ReviewReportFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User1
		{
			get { return _user1; }
			set { SetSingleRelatedEntityNavigator(value, "User1"); }
		}

		/// <summary>Gets / sets related entity of type 'ProductReviewEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductReviewEntity ProductReview
		{
			get { return _productReview; }
			set { SetSingleRelatedEntityNavigator(value, "ProductReview"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace GroceryEcommerce
{
	public enum ReviewReportFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Processed. </summary>
		Processed,
		///<summary>ProcessedAt. </summary>
		ProcessedAt,
		///<summary>ProcessedBy. </summary>
		ProcessedBy,
		///<summary>Reason. </summary>
		Reason,
		///<summary>ReportId. </summary>
		ReportId,
		///<summary>ReviewId. </summary>
		ReviewId,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ReviewReport. </summary>
	public partial class ReviewReportRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ReviewReportEntity and UserEntity over the m:1 relation they have, using the relation between the fields: ReviewReport.ProcessedBy - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingProcessedBy
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.UserId, ReviewReportFields.ProcessedBy }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ReviewReportEntity and UserEntity over the m:1 relation they have, using the relation between the fields: ReviewReport.UserId - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User1", false, new[] { UserFields.UserId, ReviewReportFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ReviewReportEntity and ProductReviewEntity over the m:1 relation they have, using the relation between the fields: ReviewReport.ReviewId - ProductReview.ReviewId</summary>
		public virtual IEntityRelation ProductReviewEntityUsingReviewId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ProductReview", false, new[] { ProductReviewFields.ReviewId, ReviewReportFields.ReviewId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticReviewReportRelations
	{
		internal static readonly IEntityRelation UserEntityUsingProcessedByStatic = new ReviewReportRelations().UserEntityUsingProcessedBy;
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new ReviewReportRelations().UserEntityUsingUserId;
		internal static readonly IEntityRelation ProductReviewEntityUsingReviewIdStatic = new ReviewReportRelations().ProductReviewEntityUsingReviewId;

		/// <summary>CTor</summary>
		static StaticReviewReportRelations() { }
	}
}
