//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'ReviewVote'.<br/><br/></summary>
	[Serializable]
	public partial class ReviewVoteEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private UserEntity _user;
		private ProductReviewEntity _productReview;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static ReviewVoteEntityStaticMetaData _staticMetaData = new ReviewVoteEntityStaticMetaData();
		private static ReviewVoteRelations _relationsFactory = new ReviewVoteRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
			/// <summary>Member name ProductReview</summary>
			public static readonly string ProductReview = "ProductReview";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ReviewVoteEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ReviewVoteEntityStaticMetaData()
			{
				SetEntityCoreInfo("ReviewVoteEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.ReviewVoteEntity, typeof(ReviewVoteEntity), typeof(ReviewVoteEntityFactory), false);
				AddNavigatorMetaData<ReviewVoteEntity, UserEntity>("User", "ReviewVotes", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, GroceryEcommerce.RelationClasses.StaticReviewVoteRelations.UserEntityUsingUserIdStatic, ()=>new ReviewVoteRelations().UserEntityUsingUserId, null, new int[] { (int)ReviewVoteFieldIndex.UserId }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
				AddNavigatorMetaData<ReviewVoteEntity, ProductReviewEntity>("ProductReview", "ReviewVotes", (a, b) => a._productReview = b, a => a._productReview, (a, b) => a.ProductReview = b, GroceryEcommerce.RelationClasses.StaticReviewVoteRelations.ProductReviewEntityUsingReviewIdStatic, ()=>new ReviewVoteRelations().ProductReviewEntityUsingReviewId, null, new int[] { (int)ReviewVoteFieldIndex.ReviewId }, null, true, (int)GroceryEcommerce.EntityType.ProductReviewEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ReviewVoteEntity()
		{
		}

		/// <summary> CTor</summary>
		public ReviewVoteEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ReviewVoteEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ReviewVoteEntity</param>
		public ReviewVoteEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="voteId">PK value for ReviewVote which data should be fetched into this ReviewVote object</param>
		public ReviewVoteEntity(System.Guid voteId) : this(voteId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="voteId">PK value for ReviewVote which data should be fetched into this ReviewVote object</param>
		/// <param name="validator">The custom validator object for this ReviewVoteEntity</param>
		public ReviewVoteEntity(System.Guid voteId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.VoteId = voteId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ReviewVoteEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ProductReview' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductReview() { return CreateRelationInfoForNavigator("ProductReview"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ReviewVoteEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ReviewVoteRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductReview' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductReview { get { return _staticMetaData.GetPrefetchPathElement("ProductReview", CommonEntityBase.CreateEntityCollection<ProductReviewEntity>()); } }

		/// <summary>The CreatedAt property of the Entity ReviewVote<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_votes"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)ReviewVoteFieldIndex.CreatedAt, true); }
			set { SetValue((int)ReviewVoteFieldIndex.CreatedAt, value); }
		}

		/// <summary>The Helpful property of the Entity ReviewVote<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_votes"."helpful".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean Helpful
		{
			get { return (System.Boolean)GetValue((int)ReviewVoteFieldIndex.Helpful, true); }
			set { SetValue((int)ReviewVoteFieldIndex.Helpful, value); }
		}

		/// <summary>The ReviewId property of the Entity ReviewVote<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_votes"."review_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid ReviewId
		{
			get { return (System.Guid)GetValue((int)ReviewVoteFieldIndex.ReviewId, true); }
			set { SetValue((int)ReviewVoteFieldIndex.ReviewId, value); }
		}

		/// <summary>The UserId property of the Entity ReviewVote<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_votes"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)ReviewVoteFieldIndex.UserId, true); }
			set { SetValue((int)ReviewVoteFieldIndex.UserId, value); }
		}

		/// <summary>The VoteId property of the Entity ReviewVote<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_votes"."vote_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid VoteId
		{
			get { return (System.Guid)GetValue((int)ReviewVoteFieldIndex.VoteId, true); }
			set { SetValue((int)ReviewVoteFieldIndex.VoteId, value); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		/// <summary>Gets / sets related entity of type 'ProductReviewEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductReviewEntity ProductReview
		{
			get { return _productReview; }
			set { SetSingleRelatedEntityNavigator(value, "ProductReview"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace GroceryEcommerce
{
	public enum ReviewVoteFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>Helpful. </summary>
		Helpful,
		///<summary>ReviewId. </summary>
		ReviewId,
		///<summary>UserId. </summary>
		UserId,
		///<summary>VoteId. </summary>
		VoteId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ReviewVote. </summary>
	public partial class ReviewVoteRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ReviewVoteEntity and UserEntity over the m:1 relation they have, using the relation between the fields: ReviewVote.UserId - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.UserId, ReviewVoteFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between ReviewVoteEntity and ProductReviewEntity over the m:1 relation they have, using the relation between the fields: ReviewVote.ReviewId - ProductReview.ReviewId</summary>
		public virtual IEntityRelation ProductReviewEntityUsingReviewId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ProductReview", false, new[] { ProductReviewFields.ReviewId, ReviewVoteFields.ReviewId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticReviewVoteRelations
	{
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new ReviewVoteRelations().UserEntityUsingUserId;
		internal static readonly IEntityRelation ProductReviewEntityUsingReviewIdStatic = new ReviewVoteRelations().ProductReviewEntityUsingReviewId;

		/// <summary>CTor</summary>
		static StaticReviewVoteRelations() { }
	}
}
