//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'ReviewImage'.<br/><br/></summary>
	[Serializable]
	public partial class ReviewImageEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private ProductReviewEntity _productReview;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static ReviewImageEntityStaticMetaData _staticMetaData = new ReviewImageEntityStaticMetaData();
		private static ReviewImageRelations _relationsFactory = new ReviewImageRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name ProductReview</summary>
			public static readonly string ProductReview = "ProductReview";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class ReviewImageEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public ReviewImageEntityStaticMetaData()
			{
				SetEntityCoreInfo("ReviewImageEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.ReviewImageEntity, typeof(ReviewImageEntity), typeof(ReviewImageEntityFactory), false);
				AddNavigatorMetaData<ReviewImageEntity, ProductReviewEntity>("ProductReview", "ReviewImages", (a, b) => a._productReview = b, a => a._productReview, (a, b) => a.ProductReview = b, GroceryEcommerce.RelationClasses.StaticReviewImageRelations.ProductReviewEntityUsingReviewIdStatic, ()=>new ReviewImageRelations().ProductReviewEntityUsingReviewId, null, new int[] { (int)ReviewImageFieldIndex.ReviewId }, null, true, (int)GroceryEcommerce.EntityType.ProductReviewEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static ReviewImageEntity()
		{
		}

		/// <summary> CTor</summary>
		public ReviewImageEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public ReviewImageEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this ReviewImageEntity</param>
		public ReviewImageEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="imageId">PK value for ReviewImage which data should be fetched into this ReviewImage object</param>
		public ReviewImageEntity(System.Guid imageId) : this(imageId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="imageId">PK value for ReviewImage which data should be fetched into this ReviewImage object</param>
		/// <param name="validator">The custom validator object for this ReviewImageEntity</param>
		public ReviewImageEntity(System.Guid imageId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.ImageId = imageId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected ReviewImageEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'ProductReview' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoProductReview() { return CreateRelationInfoForNavigator("ProductReview"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this ReviewImageEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static ReviewImageRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'ProductReview' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathProductReview { get { return _staticMetaData.GetPrefetchPathElement("ProductReview", CommonEntityBase.CreateEntityCollection<ProductReviewEntity>()); } }

		/// <summary>The CreatedAt property of the Entity ReviewImage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_images"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)ReviewImageFieldIndex.CreatedAt, true); }
			set { SetValue((int)ReviewImageFieldIndex.CreatedAt, value); }
		}

		/// <summary>The ImageId property of the Entity ReviewImage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_images"."image_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid ImageId
		{
			get { return (System.Guid)GetValue((int)ReviewImageFieldIndex.ImageId, true); }
			set { SetValue((int)ReviewImageFieldIndex.ImageId, value); }
		}

		/// <summary>The ImageUrl property of the Entity ReviewImage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_images"."image_url".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 500.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ImageUrl
		{
			get { return (System.String)GetValue((int)ReviewImageFieldIndex.ImageUrl, true); }
			set { SetValue((int)ReviewImageFieldIndex.ImageUrl, value); }
		}

		/// <summary>The ReviewId property of the Entity ReviewImage<br/><br/></summary>
		/// <remarks>Mapped on  table field: "review_images"."review_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid ReviewId
		{
			get { return (System.Guid)GetValue((int)ReviewImageFieldIndex.ReviewId, true); }
			set { SetValue((int)ReviewImageFieldIndex.ReviewId, value); }
		}

		/// <summary>Gets / sets related entity of type 'ProductReviewEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ProductReviewEntity ProductReview
		{
			get { return _productReview; }
			set { SetSingleRelatedEntityNavigator(value, "ProductReview"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace GroceryEcommerce
{
	public enum ReviewImageFieldIndex
	{
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>ImageId. </summary>
		ImageId,
		///<summary>ImageUrl. </summary>
		ImageUrl,
		///<summary>ReviewId. </summary>
		ReviewId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: ReviewImage. </summary>
	public partial class ReviewImageRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between ReviewImageEntity and ProductReviewEntity over the m:1 relation they have, using the relation between the fields: ReviewImage.ReviewId - ProductReview.ReviewId</summary>
		public virtual IEntityRelation ProductReviewEntityUsingReviewId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "ProductReview", false, new[] { ProductReviewFields.ReviewId, ReviewImageFields.ReviewId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticReviewImageRelations
	{
		internal static readonly IEntityRelation ProductReviewEntityUsingReviewIdStatic = new ReviewImageRelations().ProductReviewEntityUsingReviewId;

		/// <summary>CTor</summary>
		static StaticReviewImageRelations() { }
	}
}
