//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END
	/// <summary>Entity class which represents the entity 'UserRoleAssignment'.<br/><br/></summary>
	[Serializable]
	public partial class UserRoleAssignmentEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END	
	{
		private UserEntity _user;
		private UserEntity _user1;
		private UserRoleEntity _userRole;

		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END
		private static UserRoleAssignmentEntityStaticMetaData _staticMetaData = new UserRoleAssignmentEntityStaticMetaData();
		private static UserRoleAssignmentRelations _relationsFactory = new UserRoleAssignmentRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
			/// <summary>Member name User1</summary>
			public static readonly string User1 = "User1";
			/// <summary>Member name UserRole</summary>
			public static readonly string UserRole = "UserRole";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class UserRoleAssignmentEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public UserRoleAssignmentEntityStaticMetaData()
			{
				SetEntityCoreInfo("UserRoleAssignmentEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.UserRoleAssignmentEntity, typeof(UserRoleAssignmentEntity), typeof(UserRoleAssignmentEntityFactory), false);
				AddNavigatorMetaData<UserRoleAssignmentEntity, UserEntity>("User", "UserRoleAssignments", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, GroceryEcommerce.RelationClasses.StaticUserRoleAssignmentRelations.UserEntityUsingAssignedByStatic, ()=>new UserRoleAssignmentRelations().UserEntityUsingAssignedBy, null, new int[] { (int)UserRoleAssignmentFieldIndex.AssignedBy }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
				AddNavigatorMetaData<UserRoleAssignmentEntity, UserEntity>("User1", "UserRoleAssignments1", (a, b) => a._user1 = b, a => a._user1, (a, b) => a.User1 = b, GroceryEcommerce.RelationClasses.StaticUserRoleAssignmentRelations.UserEntityUsingUserIdStatic, ()=>new UserRoleAssignmentRelations().UserEntityUsingUserId, null, new int[] { (int)UserRoleAssignmentFieldIndex.UserId }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
				AddNavigatorMetaData<UserRoleAssignmentEntity, UserRoleEntity>("UserRole", "UserRoleAssignments", (a, b) => a._userRole = b, a => a._userRole, (a, b) => a.UserRole = b, GroceryEcommerce.RelationClasses.StaticUserRoleAssignmentRelations.UserRoleEntityUsingRoleIdStatic, ()=>new UserRoleAssignmentRelations().UserRoleEntityUsingRoleId, null, new int[] { (int)UserRoleAssignmentFieldIndex.RoleId }, null, true, (int)GroceryEcommerce.EntityType.UserRoleEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static UserRoleAssignmentEntity()
		{
		}

		/// <summary> CTor</summary>
		public UserRoleAssignmentEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public UserRoleAssignmentEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this UserRoleAssignmentEntity</param>
		public UserRoleAssignmentEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="roleId">PK value for UserRoleAssignment which data should be fetched into this UserRoleAssignment object</param>
		/// <param name="userId">PK value for UserRoleAssignment which data should be fetched into this UserRoleAssignment object</param>
		public UserRoleAssignmentEntity(System.Guid roleId, System.Guid userId) : this(roleId, userId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="roleId">PK value for UserRoleAssignment which data should be fetched into this UserRoleAssignment object</param>
		/// <param name="userId">PK value for UserRoleAssignment which data should be fetched into this UserRoleAssignment object</param>
		/// <param name="validator">The custom validator object for this UserRoleAssignmentEntity</param>
		public UserRoleAssignmentEntity(System.Guid roleId, System.Guid userId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.RoleId = roleId;
			this.UserId = userId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected UserRoleAssignmentEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser1() { return CreateRelationInfoForNavigator("User1"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'UserRole' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUserRole() { return CreateRelationInfoForNavigator("UserRole"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END
			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this UserRoleAssignmentEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static UserRoleAssignmentRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser1 { get { return _staticMetaData.GetPrefetchPathElement("User1", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'UserRole' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUserRole { get { return _staticMetaData.GetPrefetchPathElement("UserRole", CommonEntityBase.CreateEntityCollection<UserRoleEntity>()); } }

		/// <summary>The AssignedAt property of the Entity UserRoleAssignment<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_role_assignments"."assigned_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime AssignedAt
		{
			get { return (System.DateTime)GetValue((int)UserRoleAssignmentFieldIndex.AssignedAt, true); }
			set { SetValue((int)UserRoleAssignmentFieldIndex.AssignedAt, value); }
		}

		/// <summary>The AssignedBy property of the Entity UserRoleAssignment<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_role_assignments"."assigned_by".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid AssignedBy
		{
			get { return (System.Guid)GetValue((int)UserRoleAssignmentFieldIndex.AssignedBy, true); }
			set { SetValue((int)UserRoleAssignmentFieldIndex.AssignedBy, value); }
		}

		/// <summary>The RoleId property of the Entity UserRoleAssignment<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_role_assignments"."role_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid RoleId
		{
			get { return (System.Guid)GetValue((int)UserRoleAssignmentFieldIndex.RoleId, true); }
			set { SetValue((int)UserRoleAssignmentFieldIndex.RoleId, value); }
		}

		/// <summary>The UserId property of the Entity UserRoleAssignment<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_role_assignments"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)UserRoleAssignmentFieldIndex.UserId, true); }
			set { SetValue((int)UserRoleAssignmentFieldIndex.UserId, value); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User1
		{
			get { return _user1; }
			set { SetSingleRelatedEntityNavigator(value, "User1"); }
		}

		/// <summary>Gets / sets related entity of type 'UserRoleEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserRoleEntity UserRole
		{
			get { return _userRole; }
			set { SetSingleRelatedEntityNavigator(value, "UserRole"); }
		}

		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END

	}
}

namespace GroceryEcommerce
{
	public enum UserRoleAssignmentFieldIndex
	{
		///<summary>AssignedAt. </summary>
		AssignedAt,
		///<summary>AssignedBy. </summary>
		AssignedBy,
		///<summary>RoleId. </summary>
		RoleId,
		///<summary>UserId. </summary>
		UserId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: UserRoleAssignment. </summary>
	public partial class UserRoleAssignmentRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between UserRoleAssignmentEntity and UserEntity over the m:1 relation they have, using the relation between the fields: UserRoleAssignment.AssignedBy - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingAssignedBy
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.UserId, UserRoleAssignmentFields.AssignedBy }); }
		}

		/// <summary>Returns a new IEntityRelation object, between UserRoleAssignmentEntity and UserEntity over the m:1 relation they have, using the relation between the fields: UserRoleAssignment.UserId - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User1", false, new[] { UserFields.UserId, UserRoleAssignmentFields.UserId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between UserRoleAssignmentEntity and UserRoleEntity over the m:1 relation they have, using the relation between the fields: UserRoleAssignment.RoleId - UserRole.RoleId</summary>
		public virtual IEntityRelation UserRoleEntityUsingRoleId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "UserRole", false, new[] { UserRoleFields.RoleId, UserRoleAssignmentFields.RoleId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticUserRoleAssignmentRelations
	{
		internal static readonly IEntityRelation UserEntityUsingAssignedByStatic = new UserRoleAssignmentRelations().UserEntityUsingAssignedBy;
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new UserRoleAssignmentRelations().UserEntityUsingUserId;
		internal static readonly IEntityRelation UserRoleEntityUsingRoleIdStatic = new UserRoleAssignmentRelations().UserRoleEntityUsingRoleId;

		/// <summary>CTor</summary>
		static StaticUserRoleAssignmentRelations() { }
	}
}
