//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using GroceryEcommerce.HelperClasses;
using GroceryEcommerce.FactoryClasses;
using GroceryEcommerce.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace GroceryEcommerce.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'UserAddress'.<br/><br/></summary>
	[Serializable]
	public partial class UserAddressEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private UserEntity _user;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static UserAddressEntityStaticMetaData _staticMetaData = new UserAddressEntityStaticMetaData();
		private static UserAddressRelations _relationsFactory = new UserAddressRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name User</summary>
			public static readonly string User = "User";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class UserAddressEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public UserAddressEntityStaticMetaData()
			{
				SetEntityCoreInfo("UserAddressEntity", InheritanceHierarchyType.None, false, (int)GroceryEcommerce.EntityType.UserAddressEntity, typeof(UserAddressEntity), typeof(UserAddressEntityFactory), false);
				AddNavigatorMetaData<UserAddressEntity, UserEntity>("User", "UserAddresses", (a, b) => a._user = b, a => a._user, (a, b) => a.User = b, GroceryEcommerce.RelationClasses.StaticUserAddressRelations.UserEntityUsingUserIdStatic, ()=>new UserAddressRelations().UserEntityUsingUserId, null, new int[] { (int)UserAddressFieldIndex.UserId }, null, true, (int)GroceryEcommerce.EntityType.UserEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static UserAddressEntity()
		{
		}

		/// <summary> CTor</summary>
		public UserAddressEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public UserAddressEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this UserAddressEntity</param>
		public UserAddressEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="addressId">PK value for UserAddress which data should be fetched into this UserAddress object</param>
		public UserAddressEntity(System.Guid addressId) : this(addressId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="addressId">PK value for UserAddress which data should be fetched into this UserAddress object</param>
		/// <param name="validator">The custom validator object for this UserAddressEntity</param>
		public UserAddressEntity(System.Guid addressId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.AddressId = addressId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected UserAddressEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'User' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoUser() { return CreateRelationInfoForNavigator("User"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this UserAddressEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static UserAddressRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'User' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathUser { get { return _staticMetaData.GetPrefetchPathElement("User", CommonEntityBase.CreateEntityCollection<UserEntity>()); } }

		/// <summary>The AddressId property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."address_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Guid AddressId
		{
			get { return (System.Guid)GetValue((int)UserAddressFieldIndex.AddressId, true); }
			set { SetValue((int)UserAddressFieldIndex.AddressId, value); }
		}

		/// <summary>The AddressLine1 property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."address_line1".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String AddressLine1
		{
			get { return (System.String)GetValue((int)UserAddressFieldIndex.AddressLine1, true); }
			set { SetValue((int)UserAddressFieldIndex.AddressLine1, value); }
		}

		/// <summary>The AddressLine2 property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."address_line2".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 255.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual System.String AddressLine2
		{
			get { return (System.String)GetValue((int)UserAddressFieldIndex.AddressLine2, true); }
			set { SetValue((int)UserAddressFieldIndex.AddressLine2, value); }
		}

		/// <summary>The AddressType property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."address_type".<br/>Table field type characteristics (type, precision, scale, length): Smallint, 5, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Int16 AddressType
		{
			get { return (System.Int16)GetValue((int)UserAddressFieldIndex.AddressType, true); }
			set { SetValue((int)UserAddressFieldIndex.AddressType, value); }
		}

		/// <summary>The City property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."city".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String City
		{
			get { return (System.String)GetValue((int)UserAddressFieldIndex.City, true); }
			set { SetValue((int)UserAddressFieldIndex.City, value); }
		}

		/// <summary>The Country property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."country".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Country
		{
			get { return (System.String)GetValue((int)UserAddressFieldIndex.Country, true); }
			set { SetValue((int)UserAddressFieldIndex.Country, value); }
		}

		/// <summary>The CreatedAt property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."created_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.DateTime CreatedAt
		{
			get { return (System.DateTime)GetValue((int)UserAddressFieldIndex.CreatedAt, true); }
			set { SetValue((int)UserAddressFieldIndex.CreatedAt, value); }
		}

		/// <summary>The IsDefault property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."is_default".<br/>Table field type characteristics (type, precision, scale, length): Boolean, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Boolean IsDefault
		{
			get { return (System.Boolean)GetValue((int)UserAddressFieldIndex.IsDefault, true); }
			set { SetValue((int)UserAddressFieldIndex.IsDefault, value); }
		}

		/// <summary>The State property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."state".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 100.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String State
		{
			get { return (System.String)GetValue((int)UserAddressFieldIndex.State, true); }
			set { SetValue((int)UserAddressFieldIndex.State, value); }
		}

		/// <summary>The UpdatedAt property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."updated_at".<br/>Table field type characteristics (type, precision, scale, length): TimestampTz, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): true, false, false</remarks>
		public virtual Nullable<System.DateTime> UpdatedAt
		{
			get { return (Nullable<System.DateTime>)GetValue((int)UserAddressFieldIndex.UpdatedAt, false); }
			set { SetValue((int)UserAddressFieldIndex.UpdatedAt, value); }
		}

		/// <summary>The UserId property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."user_id".<br/>Table field type characteristics (type, precision, scale, length): Uuid, 0, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Guid UserId
		{
			get { return (System.Guid)GetValue((int)UserAddressFieldIndex.UserId, true); }
			set { SetValue((int)UserAddressFieldIndex.UserId, value); }
		}

		/// <summary>The ZipCode property of the Entity UserAddress<br/><br/></summary>
		/// <remarks>Mapped on  table field: "user_addresses"."zip_code".<br/>Table field type characteristics (type, precision, scale, length): Varchar, 0, 0, 20.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String ZipCode
		{
			get { return (System.String)GetValue((int)UserAddressFieldIndex.ZipCode, true); }
			set { SetValue((int)UserAddressFieldIndex.ZipCode, value); }
		}

		/// <summary>Gets / sets related entity of type 'UserEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual UserEntity User
		{
			get { return _user; }
			set { SetSingleRelatedEntityNavigator(value, "User"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace GroceryEcommerce
{
	public enum UserAddressFieldIndex
	{
		///<summary>AddressId. </summary>
		AddressId,
		///<summary>AddressLine1. </summary>
		AddressLine1,
		///<summary>AddressLine2. </summary>
		AddressLine2,
		///<summary>AddressType. </summary>
		AddressType,
		///<summary>City. </summary>
		City,
		///<summary>Country. </summary>
		Country,
		///<summary>CreatedAt. </summary>
		CreatedAt,
		///<summary>IsDefault. </summary>
		IsDefault,
		///<summary>State. </summary>
		State,
		///<summary>UpdatedAt. </summary>
		UpdatedAt,
		///<summary>UserId. </summary>
		UserId,
		///<summary>ZipCode. </summary>
		ZipCode,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace GroceryEcommerce.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: UserAddress. </summary>
	public partial class UserAddressRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between UserAddressEntity and UserEntity over the m:1 relation they have, using the relation between the fields: UserAddress.UserId - User.UserId</summary>
		public virtual IEntityRelation UserEntityUsingUserId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "User", false, new[] { UserFields.UserId, UserAddressFields.UserId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticUserAddressRelations
	{
		internal static readonly IEntityRelation UserEntityUsingUserIdStatic = new UserAddressRelations().UserEntityUsingUserId;

		/// <summary>CTor</summary>
		static StaticUserAddressRelations() { }
	}
}
