//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Auth.authAuditLog'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.authAuditLog"/>. </remarks>
	[Serializable]
	public partial class authAuditLogRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="authAuditLogRow"/> class.</summary>
		public authAuditLogRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Action field.</summary>
		public System.String Action { get; set; }
		/// <summary>Gets or sets the AuditId field.</summary>
		public System.Guid AuditId { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the Detail field.</summary>
		public System.String Detail { get; set; }
		/// <summary>Gets or sets the Entity field.</summary>
		public System.String Entity { get; set; }
		/// <summary>Gets or sets the EntityId field.</summary>
		public Nullable<System.Guid> EntityId { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public Nullable<System.Guid> UserId { get; set; }
	}
}

