//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Auth.authUser'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.authUser"/>. </remarks>
	[Serializable]
	public partial class authUserRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="authUserRow"/> class.</summary>
		public authUserRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the DateOfBirth field.</summary>
		public Nullable<System.DateTime> DateOfBirth { get; set; }
		/// <summary>Gets or sets the Email field.</summary>
		public System.String Email { get; set; }
		/// <summary>Gets or sets the EmailVerified field.</summary>
		public System.Boolean EmailVerified { get; set; }
		/// <summary>Gets or sets the FirstName field.</summary>
		public System.String FirstName { get; set; }
		/// <summary>Gets or sets the LastLoginAt field.</summary>
		public Nullable<System.DateTime> LastLoginAt { get; set; }
		/// <summary>Gets or sets the LastName field.</summary>
		public System.String LastName { get; set; }
		/// <summary>Gets or sets the PasswordHash field.</summary>
		public System.String PasswordHash { get; set; }
		/// <summary>Gets or sets the PhoneNumber field.</summary>
		public System.String PhoneNumber { get; set; }
		/// <summary>Gets or sets the PhoneVerified field.</summary>
		public System.Boolean PhoneVerified { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.Int16 Status { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public System.Guid UserId { get; set; }
		/// <summary>Gets or sets the Username field.</summary>
		public System.String Username { get; set; }
	}
}

