//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Auth.authUserAddress'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.authUserAddress"/>. </remarks>
	[Serializable]
	public partial class authUserAddressRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="authUserAddressRow"/> class.</summary>
		public authUserAddressRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the AddressId field.</summary>
		public System.Guid AddressId { get; set; }
		/// <summary>Gets or sets the AddressLine1 field.</summary>
		public System.String AddressLine1 { get; set; }
		/// <summary>Gets or sets the AddressLine2 field.</summary>
		public System.String AddressLine2 { get; set; }
		/// <summary>Gets or sets the AddressType field.</summary>
		public System.Int16 AddressType { get; set; }
		/// <summary>Gets or sets the City field.</summary>
		public System.String City { get; set; }
		/// <summary>Gets or sets the Country field.</summary>
		public System.String Country { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the IsDefault field.</summary>
		public System.Boolean IsDefault { get; set; }
		/// <summary>Gets or sets the State field.</summary>
		public System.String State { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public System.Guid UserId { get; set; }
		/// <summary>Gets or sets the ZipCode field.</summary>
		public System.String ZipCode { get; set; }
	}
}

