//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Cart.cartAbandonedCart'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.cartAbandonedCart"/>. </remarks>
	[Serializable]
	public partial class cartAbandonedCartRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="cartAbandonedCartRow"/> class.</summary>
		public cartAbandonedCartRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the AbandonedAt field.</summary>
		public System.DateTime AbandonedAt { get; set; }
		/// <summary>Gets or sets the AbandonedId field.</summary>
		public System.Guid AbandonedId { get; set; }
		/// <summary>Gets or sets the CartId field.</summary>
		public System.Guid CartId { get; set; }
		/// <summary>Gets or sets the Notified field.</summary>
		public System.Boolean Notified { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public Nullable<System.Guid> UserId { get; set; }
	}
}

