//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Catalog.catalogProductVariant'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.catalogProductVariant"/>. </remarks>
	[Serializable]
	public partial class catalogProductVariantRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="catalogProductVariantRow"/> class.</summary>
		public catalogProductVariantRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the DiscountPrice field.</summary>
		public Nullable<System.Decimal> DiscountPrice { get; set; }
		/// <summary>Gets or sets the ImageUrl field.</summary>
		public System.String ImageUrl { get; set; }
		/// <summary>Gets or sets the Name field.</summary>
		public System.String Name { get; set; }
		/// <summary>Gets or sets the Price field.</summary>
		public System.Decimal Price { get; set; }
		/// <summary>Gets or sets the ProductId field.</summary>
		public System.Guid ProductId { get; set; }
		/// <summary>Gets or sets the Sku field.</summary>
		public System.String Sku { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.Int16 Status { get; set; }
		/// <summary>Gets or sets the StockQuantity field.</summary>
		public System.Int32 StockQuantity { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
		/// <summary>Gets or sets the VariantId field.</summary>
		public System.Guid VariantId { get; set; }
		/// <summary>Gets or sets the Weight field.</summary>
		public Nullable<System.Decimal> Weight { get; set; }
	}
}

