//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Catalog.catalogCategory'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.catalogCategory"/>. </remarks>
	[Serializable]
	public partial class catalogCategoryRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="catalogCategoryRow"/> class.</summary>
		public catalogCategoryRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CategoryId field.</summary>
		public System.Guid CategoryId { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the CreatedBy field.</summary>
		public System.Guid CreatedBy { get; set; }
		/// <summary>Gets or sets the Description field.</summary>
		public System.String Description { get; set; }
		/// <summary>Gets or sets the DisplayOrder field.</summary>
		public System.Int32 DisplayOrder { get; set; }
		/// <summary>Gets or sets the ImageUrl field.</summary>
		public System.String ImageUrl { get; set; }
		/// <summary>Gets or sets the MetaDescription field.</summary>
		public System.String MetaDescription { get; set; }
		/// <summary>Gets or sets the MetaTitle field.</summary>
		public System.String MetaTitle { get; set; }
		/// <summary>Gets or sets the Name field.</summary>
		public System.String Name { get; set; }
		/// <summary>Gets or sets the ParentCategoryId field.</summary>
		public Nullable<System.Guid> ParentCategoryId { get; set; }
		/// <summary>Gets or sets the Slug field.</summary>
		public System.String Slug { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.Int16 Status { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
		/// <summary>Gets or sets the UpdatedBy field.</summary>
		public Nullable<System.Guid> UpdatedBy { get; set; }
	}
}

