//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Inventory.inventoryPurchaseOrder'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.inventoryPurchaseOrder"/>. </remarks>
	[Serializable]
	public partial class inventoryPurchaseOrderRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="inventoryPurchaseOrderRow"/> class.</summary>
		public inventoryPurchaseOrderRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the CreatedBy field.</summary>
		public Nullable<System.Guid> CreatedBy { get; set; }
		/// <summary>Gets or sets the ExpectedDate field.</summary>
		public Nullable<System.DateTime> ExpectedDate { get; set; }
		/// <summary>Gets or sets the OrderDate field.</summary>
		public System.DateTime OrderDate { get; set; }
		/// <summary>Gets or sets the OrderNumber field.</summary>
		public System.String OrderNumber { get; set; }
		/// <summary>Gets or sets the PurchaseOrderId field.</summary>
		public System.Guid PurchaseOrderId { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.Int16 Status { get; set; }
		/// <summary>Gets or sets the SupplierId field.</summary>
		public System.Guid SupplierId { get; set; }
		/// <summary>Gets or sets the TotalAmount field.</summary>
		public System.Decimal TotalAmount { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
		/// <summary>Gets or sets the WarehouseId field.</summary>
		public Nullable<System.Guid> WarehouseId { get; set; }
	}
}

