//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Inventory.inventoryPurchaseOrderItem'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.inventoryPurchaseOrderItem"/>. </remarks>
	[Serializable]
	public partial class inventoryPurchaseOrderItemRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="inventoryPurchaseOrderItemRow"/> class.</summary>
		public inventoryPurchaseOrderItemRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the PoiId field.</summary>
		public System.Guid PoiId { get; set; }
		/// <summary>Gets or sets the ProductId field.</summary>
		public System.Guid ProductId { get; set; }
		/// <summary>Gets or sets the PurchaseOrderId field.</summary>
		public System.Guid PurchaseOrderId { get; set; }
		/// <summary>Gets or sets the Quantity field.</summary>
		public System.Int32 Quantity { get; set; }
		/// <summary>Gets or sets the TotalCost field.</summary>
		public System.Decimal TotalCost { get; set; }
		/// <summary>Gets or sets the UnitCost field.</summary>
		public System.Decimal UnitCost { get; set; }
		/// <summary>Gets or sets the VariantId field.</summary>
		public Nullable<System.Guid> VariantId { get; set; }
	}
}

