//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Marketing.marketingCoupon'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.marketingCoupon"/>. </remarks>
	[Serializable]
	public partial class marketingCouponRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="marketingCouponRow"/> class.</summary>
		public marketingCouponRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Code field.</summary>
		public System.String Code { get; set; }
		/// <summary>Gets or sets the CouponId field.</summary>
		public System.Guid CouponId { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the CreatedBy field.</summary>
		public System.Guid CreatedBy { get; set; }
		/// <summary>Gets or sets the Description field.</summary>
		public System.String Description { get; set; }
		/// <summary>Gets or sets the DiscountType field.</summary>
		public System.Int16 DiscountType { get; set; }
		/// <summary>Gets or sets the DiscountValue field.</summary>
		public System.Decimal DiscountValue { get; set; }
		/// <summary>Gets or sets the MaxDiscountAmount field.</summary>
		public Nullable<System.Decimal> MaxDiscountAmount { get; set; }
		/// <summary>Gets or sets the MinOrderAmount field.</summary>
		public Nullable<System.Decimal> MinOrderAmount { get; set; }
		/// <summary>Gets or sets the Name field.</summary>
		public System.String Name { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.Int16 Status { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
		/// <summary>Gets or sets the UpdatedBy field.</summary>
		public Nullable<System.Guid> UpdatedBy { get; set; }
		/// <summary>Gets or sets the UsageCount field.</summary>
		public System.Int32 UsageCount { get; set; }
		/// <summary>Gets or sets the UsageLimit field.</summary>
		public Nullable<System.Int32> UsageLimit { get; set; }
		/// <summary>Gets or sets the UserUsageLimit field.</summary>
		public Nullable<System.Int32> UserUsageLimit { get; set; }
		/// <summary>Gets or sets the ValidFrom field.</summary>
		public System.DateTime ValidFrom { get; set; }
		/// <summary>Gets or sets the ValidTo field.</summary>
		public System.DateTime ValidTo { get; set; }
	}
}

