//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Marketing.marketingRewardPoint'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.marketingRewardPoint"/>. </remarks>
	[Serializable]
	public partial class marketingRewardPointRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="marketingRewardPointRow"/> class.</summary>
		public marketingRewardPointRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the ExpiresAt field.</summary>
		public Nullable<System.DateTime> ExpiresAt { get; set; }
		/// <summary>Gets or sets the Points field.</summary>
		public System.Int32 Points { get; set; }
		/// <summary>Gets or sets the Reason field.</summary>
		public System.String Reason { get; set; }
		/// <summary>Gets or sets the RewardId field.</summary>
		public System.Guid RewardId { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public System.Guid UserId { get; set; }
	}
}

