//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Reviews.reviewsReviewImage'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.reviewsReviewImage"/>. </remarks>
	[Serializable]
	public partial class reviewsReviewImageRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="reviewsReviewImageRow"/> class.</summary>
		public reviewsReviewImageRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the ImageId field.</summary>
		public System.Guid ImageId { get; set; }
		/// <summary>Gets or sets the ImageUrl field.</summary>
		public System.String ImageUrl { get; set; }
		/// <summary>Gets or sets the ReviewId field.</summary>
		public System.Guid ReviewId { get; set; }
	}
}

