//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Sales.salesShipmentItem'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.salesShipmentItem"/>. </remarks>
	[Serializable]
	public partial class salesShipmentItemRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="salesShipmentItemRow"/> class.</summary>
		public salesShipmentItemRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the OrderItemId field.</summary>
		public System.Guid OrderItemId { get; set; }
		/// <summary>Gets or sets the Quantity field.</summary>
		public System.Int32 Quantity { get; set; }
		/// <summary>Gets or sets the ShipmentId field.</summary>
		public System.Guid ShipmentId { get; set; }
		/// <summary>Gets or sets the ShipmentItemId field.</summary>
		public System.Guid ShipmentItemId { get; set; }
	}
}

