//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Sales.salesOrder'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.salesOrder"/>. </remarks>
	[Serializable]
	public partial class salesOrderRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="salesOrderRow"/> class.</summary>
		public salesOrderRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the BillingAddress field.</summary>
		public System.String BillingAddress { get; set; }
		/// <summary>Gets or sets the BillingCity field.</summary>
		public System.String BillingCity { get; set; }
		/// <summary>Gets or sets the BillingCountry field.</summary>
		public System.String BillingCountry { get; set; }
		/// <summary>Gets or sets the BillingEmail field.</summary>
		public System.String BillingEmail { get; set; }
		/// <summary>Gets or sets the BillingFirstName field.</summary>
		public System.String BillingFirstName { get; set; }
		/// <summary>Gets or sets the BillingLastName field.</summary>
		public System.String BillingLastName { get; set; }
		/// <summary>Gets or sets the BillingPhone field.</summary>
		public System.String BillingPhone { get; set; }
		/// <summary>Gets or sets the BillingState field.</summary>
		public System.String BillingState { get; set; }
		/// <summary>Gets or sets the BillingZipCode field.</summary>
		public System.String BillingZipCode { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the CreatedBy field.</summary>
		public Nullable<System.Guid> CreatedBy { get; set; }
		/// <summary>Gets or sets the DeliveredAt field.</summary>
		public Nullable<System.DateTime> DeliveredAt { get; set; }
		/// <summary>Gets or sets the DiscountAmount field.</summary>
		public System.Decimal DiscountAmount { get; set; }
		/// <summary>Gets or sets the EstimatedDeliveryDate field.</summary>
		public Nullable<System.DateTime> EstimatedDeliveryDate { get; set; }
		/// <summary>Gets or sets the Notes field.</summary>
		public System.String Notes { get; set; }
		/// <summary>Gets or sets the OrderDate field.</summary>
		public System.DateTime OrderDate { get; set; }
		/// <summary>Gets or sets the OrderId field.</summary>
		public System.Guid OrderId { get; set; }
		/// <summary>Gets or sets the OrderNumber field.</summary>
		public System.String OrderNumber { get; set; }
		/// <summary>Gets or sets the PaymentMethod field.</summary>
		public System.Int16 PaymentMethod { get; set; }
		/// <summary>Gets or sets the PaymentStatus field.</summary>
		public System.Int16 PaymentStatus { get; set; }
		/// <summary>Gets or sets the ShippingAddress field.</summary>
		public System.String ShippingAddress { get; set; }
		/// <summary>Gets or sets the ShippingAmount field.</summary>
		public System.Decimal ShippingAmount { get; set; }
		/// <summary>Gets or sets the ShippingCity field.</summary>
		public System.String ShippingCity { get; set; }
		/// <summary>Gets or sets the ShippingCountry field.</summary>
		public System.String ShippingCountry { get; set; }
		/// <summary>Gets or sets the ShippingEmail field.</summary>
		public System.String ShippingEmail { get; set; }
		/// <summary>Gets or sets the ShippingFirstName field.</summary>
		public System.String ShippingFirstName { get; set; }
		/// <summary>Gets or sets the ShippingLastName field.</summary>
		public System.String ShippingLastName { get; set; }
		/// <summary>Gets or sets the ShippingPhone field.</summary>
		public System.String ShippingPhone { get; set; }
		/// <summary>Gets or sets the ShippingState field.</summary>
		public System.String ShippingState { get; set; }
		/// <summary>Gets or sets the ShippingZipCode field.</summary>
		public System.String ShippingZipCode { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.Int16 Status { get; set; }
		/// <summary>Gets or sets the SubTotal field.</summary>
		public System.Decimal SubTotal { get; set; }
		/// <summary>Gets or sets the TaxAmount field.</summary>
		public System.Decimal TaxAmount { get; set; }
		/// <summary>Gets or sets the TotalAmount field.</summary>
		public System.Decimal TotalAmount { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
		/// <summary>Gets or sets the UserId field.</summary>
		public System.Guid UserId { get; set; }
	}
}

