//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Sales.salesShipmentCarrier'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.salesShipmentCarrier"/>. </remarks>
	[Serializable]
	public partial class salesShipmentCarrierRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="salesShipmentCarrierRow"/> class.</summary>
		public salesShipmentCarrierRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CarrierId field.</summary>
		public System.Guid CarrierId { get; set; }
		/// <summary>Gets or sets the Code field.</summary>
		public System.String Code { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the Name field.</summary>
		public System.String Name { get; set; }
		/// <summary>Gets or sets the Phone field.</summary>
		public System.String Phone { get; set; }
		/// <summary>Gets or sets the Website field.</summary>
		public System.String Website { get; set; }
	}
}

