//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Sales.salesOrderShipment'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.salesOrderShipment"/>. </remarks>
	[Serializable]
	public partial class salesOrderShipmentRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="salesOrderShipmentRow"/> class.</summary>
		public salesOrderShipmentRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the CarrierId field.</summary>
		public Nullable<System.Guid> CarrierId { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the DeliveredAt field.</summary>
		public Nullable<System.DateTime> DeliveredAt { get; set; }
		/// <summary>Gets or sets the OrderId field.</summary>
		public System.Guid OrderId { get; set; }
		/// <summary>Gets or sets the ShipmentId field.</summary>
		public System.Guid ShipmentId { get; set; }
		/// <summary>Gets or sets the ShipmentNumber field.</summary>
		public System.String ShipmentNumber { get; set; }
		/// <summary>Gets or sets the ShippedAt field.</summary>
		public Nullable<System.DateTime> ShippedAt { get; set; }
		/// <summary>Gets or sets the ShippingCost field.</summary>
		public Nullable<System.Decimal> ShippingCost { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.Int16 Status { get; set; }
		/// <summary>Gets or sets the TrackingNumber field.</summary>
		public System.String TrackingNumber { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
		/// <summary>Gets or sets the WarehouseId field.</summary>
		public Nullable<System.Guid> WarehouseId { get; set; }
	}
}

