//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'Sales.salesOrderPayment'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.salesOrderPayment"/>. </remarks>
	[Serializable]
	public partial class salesOrderPaymentRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="salesOrderPaymentRow"/> class.</summary>
		public salesOrderPaymentRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Amount field.</summary>
		public System.Decimal Amount { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the Currency field.</summary>
		public System.String Currency { get; set; }
		/// <summary>Gets or sets the GatewayResponse field.</summary>
		public System.String GatewayResponse { get; set; }
		/// <summary>Gets or sets the OrderId field.</summary>
		public System.Guid OrderId { get; set; }
		/// <summary>Gets or sets the PaidAt field.</summary>
		public Nullable<System.DateTime> PaidAt { get; set; }
		/// <summary>Gets or sets the PaymentId field.</summary>
		public System.Guid PaymentId { get; set; }
		/// <summary>Gets or sets the PaymentMethod field.</summary>
		public System.Int16 PaymentMethod { get; set; }
		/// <summary>Gets or sets the Status field.</summary>
		public System.Int16 Status { get; set; }
		/// <summary>Gets or sets the TransactionId field.</summary>
		public System.String TransactionId { get; set; }
	}
}

