//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.12.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;

namespace GroceryEcommerce.TypedViewClasses
{
	/// <summary>Class which represents a row in the typed view 'System.systemEmailTemplate'.</summary>
	/// <remarks>This class is a result class for a query, which is produced with the property <see cref="GroceryEcommerce.FactoryClasses.QueryFactory.systemEmailTemplate"/>. </remarks>
	[Serializable]
	public partial class systemEmailTemplateRow 
	{
		partial void OnCreated();
		
		/// <summary>Initializes a new instance of the <see cref="systemEmailTemplateRow"/> class.</summary>
		public systemEmailTemplateRow()
		{
			OnCreated();
		}

		/// <summary>Gets or sets the Body field.</summary>
		public System.String Body { get; set; }
		/// <summary>Gets or sets the CreatedAt field.</summary>
		public System.DateTime CreatedAt { get; set; }
		/// <summary>Gets or sets the Language field.</summary>
		public System.String Language { get; set; }
		/// <summary>Gets or sets the Name field.</summary>
		public System.String Name { get; set; }
		/// <summary>Gets or sets the Subject field.</summary>
		public System.String Subject { get; set; }
		/// <summary>Gets or sets the TemplateId field.</summary>
		public System.Guid TemplateId { get; set; }
		/// <summary>Gets or sets the UpdatedAt field.</summary>
		public Nullable<System.DateTime> UpdatedAt { get; set; }
	}
}

